reframe-hpc/reframe

- writing_checks/README.md
> Correcting the position of the EOF-check in the parser example

- cscs-checks/apps/openfoam-extend/check_openfoam_extend.py
- cscs-checks/apps/openfoam/check_openfoam.py
- cscs-checks/libraries/io/hdf5_compile_run.py
- cscs-checks/tools/io/cdo.py
- cscs-checks/tools/io/nco.py
- cscs-checks/tools/profiling_and_debugging/notool.py
- cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
* Remove the `setup` method when used only to access the `pre_run`
and `post_run` from `job`.
Fixes #112 
Fixes #136
> Remove 'pre_run' and 'post_run' access from 'job'

- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
* Check that the node name is not included in the excluded
node list when counting compatible nodes.
* Create a unittest class to test the flexible node allocation
combined with the `--exclude` option.
Fixes #104
> Make '--exclude' work with flexible allocation

- cscs-checks/microbenchmarks/osu/osu_tests.py
* Add `switches` at the `extra_resources` field of the g2g and
alltoall checks.
Fixes #147
> Add 'switches' for g2g and alltoall tests

- reframe/frontend/executors/policies.py
* Check that `self._a` is not smaller that a minimum allowed value.
Fixes #77
> Fix math domain error in decaying poll rate

- docs/running.rst
- reframe/core/pipeline.py
- Remove references to the obsolete `testcase_name`
- Enhance documentation of the `RegressionTest.info()` method
Fixes #139.
> Update documentation on the 'check_info' logging attribute

- reframe/core/modules.py
- reframe/frontend/cli.py
- unittests/test_cli.py
- Catch errors raised by `init_modules_system` in the CLI and report
nicely to user
> Fix crash when init_modules_system throws

- cscs-checks/apps/espresso/espresso_check.py
> Numerical sanity check in quantum espresso test

- reframe/utility/os.py
* Use command option `-h` with `git ls-remote` to list only
refs/heads reducing the size of the output.
> Fix 'git_repo_exists' bug causing a deadlock

- reframe/frontend/executors/policies.py
- reframe/frontend/statistics.py
- unittests/test_policies.py
- Also add unit tests to verify this behaviour in both the serial and
async execution policy.
Fixes #151.
> Terminate pending task upon abort in serial policy

- reframe/frontend/executors/policies.py
* Set the minimum poll rate for the async execution policy to 0.2
polls/sec.
Closes #208
> Adapt the async poll rate

- docs/advanced.rst
- docs/tutorial.rst
* Make sure that the test is referred as a matrix-vector
multiplication example.
* Use `literalinclude` in the .rst files instead of copying
the content of the tutorial examples.
Closes #222 
Closes #223
> Fix cuda example inconsistencies in tutorial

- reframe/core/pipeline.py
- unittests/test_pipeline.py
* Add support for wildcards in `valid_prog_environs` of a `RegressionTest`.
* Create the corresponding unit tests.
* Update doc for the `valid_prog_environs` field.
Closes #224
> Support wildcards in valid_prog_environs

- reframe/utility/os_ext.py
- unittests/test_utility.py
* Check that the source path is not a parent path of
the destination one.
* Create the corresponding unittest.
Fixes #221.
> Fix infinite recursion bug in 'copytree_virtual'

- reframe/__init__.py
- reframe/frontend/cli.py
* Use `__file__` to get the absolute path of the `cli.py` path and define the default `settings.py` path 
according to it.
Closes #238
> Fix default 'settings.py' path

- reframe/frontend/executors/__init__.py
- unittests/resources/frontend_checks.py
- unittests/test_cli.py
- Fix the crash
- Adapt unit tests to trigger the crash
Fixes #226.
> Fix serial execution policy crash on keyboard interrupt

- cscs-checks/apps/gromacs/gromacs_check.py
The new default version of `GROMACS` on Dom and Piz Daint is `2018` since April 24th and the output format of the energy line has slightly changed with respect to previous versions.
Fixes #270.
> Fix sanity checking for GROMACS test

- reframe/core/schedulers/__init__.py
- unittests/test_schedulers.py
* Remove the `pre_run` and `post_run` fields from class `Job`.
* Remove the corresponding deprecation unit tests.
Fixes #62
> Remove 'post_run' and 'pre_run' from 'Job'

- reframe/frontend/executors/__init__.py
- unittests/test_policies.py
- Add Unit test to expose the bug.
Fixes #216.
> Fix force local execution

- docs/advanced.rst
- reframe/core/decorators.py
- tutorial/advanced/advanced_example8.py
- unittests/resources/checks_unlisted/good.py
- unittests/resources/checks_unlisted/mixed.py
The decorator now accepts a variable argument list, instead of an iterable. This allows for nicer and easier formatting in the common cases.
> Enhance syntax of parameterized_test decorator

- cscs-checks/apps/gromacs/gromacs_check.py
Fixes https://github.com/eth-cscs/reframe-tests/issues/24
> Update gromacs values

- reframe/core/schedulers/slurm.py
* Reduce the `squeue` rate by introducing the constant
`SACCT_SQUEUE_RATIO`.
* Fix some warnings regarding regexes.
Fixes #283
> Add a knob for controlling the 'sacct'/'squeue' ratio in Slurm 'sacct' backend

- cscs-checks/prgenv/src/gpu_direct_acc.F90
> Fix MPI status variable size in GPUDirect OpenACC test

- reframe/frontend/loader.py
- unittests/resources/checks_unlisted/invalid_syntax_check.py
- unittests/test_loader.py
* Raise a `ReframeSyntaxError` with a descriptive message if parsing of
a `RegressionTest` fails.
* Create the corresponding unittest
Fixes #267
> Print filename if a test file contains syntax errors

- reframe/frontend/cli.py
- unittests/test_cli.py
Also:
- Add a unit test exposing the bug.
Fixes #315.
The option was completely ignored!
> Bugfix: Treat '--timestamp' option

- ci-scripts/ci-runner.bash
- config/cscs-pbs.py
- config/cscs.py
- cscs-checks/cuda/cuda_checks.py
- docs/configure.rst
- reframe/__init__.py
- reframe/core/pipeline.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/registry.py
- unittests/test_schedulers.py
Fixes #46 and replaces #277.
To test on Dom, you should do the following:
```bash
export PATH=/apps/dom/UES/karakasv/slurm-wrappers/bin:$PATH
./test_reframe.py --rfm-user-config=config/cscs-pbs.py
```
This special configuration is only valid for Dom and uses `pbs+mpiexec`.
Still todo:
> PBS scheduler backend

- reframe/utility/__init__.py
- unittests/test_utility.py
This implementation first resolves the module file relative to ReFrame. If it is inside ReFrame's top-level dir, it uses the standard Python mechanism (from importlib) to import the module. If not it loads it directly from the file assigning it a module name derived from the file's basename.
> Fix import from file code.

- reframe/utility/__init__.py
- unittests/test_utility.py
> Fix importing module from python file

- reframe/core/schedulers/slurm.py
> Strip the reason details before testing for match

- cscs-checks/tools/profiling_and_debugging/ddt.py
> Fix CUDA DDT check after upgrade to CUDA 9

- reframe/frontend/cli.py
- reframe/utility/__init__.py
- reframe/utility/sanity.py
- unittests/test_cli.py
- unittests/test_sanity_functions.py
- unittests/test_utility.py
* Create the corresponding unit test.
Fixes #244
> Filter out tests with no programming environments

- cscs-checks/libraries/boost/boost_python_check.py
- cscs-checks/libraries/boost/src/Makefile
* Update python3 test from python3.5 to python3.6.
* Use the PYTHONPATH environment variable to extract the python dir.
> Fix paths for Boost Python check

- reframe/core/pipeline.py
- unittests/test_pipeline.py
* Allow setting the above `RegressionTest` fields during setup.
* Create the corresponding unit test.
Closes #44
> Enable setting 'pre_run' and 'post_run' in 'setup'

- cscs-checks/mch/automatic_arrays.py
- cscs-checks/mch/src/automatic_arrays.f90
> Automatic arrays in compiler check

- docs/running.rst
- reframe/core/logging.py
- reframe/frontend/cli.py
- reframe/frontend/printer.py
- reframe/utility/os_ext.py
This PR attempts to add the username and group to perf logging.
This is especially good for grafana logging.
This should capture the name and primary group of the user that has
executed reframe.
REMARKS:
* capturing the username and group is not portable across OSes
* The fields were updated inside the `_update_check_extras`, but they
could be set during the initialization of the `LoggerAdapter`.
> Add log hander attributes for retrieving the OS user and group

- cscs-checks/cuda/cuda_memtest_check.py
> [test] New flexible CUDA memtest check

- config/cscs.py
The current dummy server and port produce errors when trying to log the
performance. For this reason, the corresponding configuration lines are
commented out specially using the `#@` prefix and will be patched
on-the-fly for production runs.
This must be merged asap, cos it's blocking other PRs.
Fixes #349.
> [bugfix] Comment out Graylog handler from CSCS config

- cscs-checks/tools/profiling_and_debugging/notool.py
* Distinguish daint and dom openmp versions after dom maintenance.
* Refactor to new check syntax.
> [bugfix] Fix expected OpenMP versions for Dom

- config/cscs.py
- cscs-checks/prgenv/gpu_direct_acc.py
Also remove workaround in `gpu_direct_acc.py`.
> [test] Update PrgEnv-pgi definitions on Kesch

- ci-scripts/ci-runner.bash
* Find the added/modified regression tests based on diversion from
the master branch.
> [ci] Check added/modified regression tests w.r.t master

- docs/conf.py
- docs/tutorial.rst
* Fix some errors in the tutorial documentation regarding the line
numbers of example1.
Closes #357
> [bugfix] Enable sphinx versioning only for releases

- reframe/frontend/cli.py
This option allows the user to specify whether or not they want to add a 'module purge' to the start of every job, before each module is loaded.
For example, given a sbatch job like so:
```bash
#!/bin/bash
#SBATCH -t 1:0
module load python
python test.py
```
The sbatch script will be output like this instead:
```bash
#!/bin/bash
#SBATCH -t 1:0
module purge
module load python
python test.py
```
The setting is per-system, so it fits next to the `module_system` option.
> [feat] Allow purging modules before running regression tests

- reframe/core/pipeline.py
- unittests/test_pipeline.py
This is a useful feature for tests that check multiple performance values.
Replaces #334.
> [feat] Evaluate and log all performance values before asserting them

- ci-scripts/ci-runner.bash
For the duration of the PE upgrade.
> [ci] Temporarily disable running of checks on Daint

- cscs-checks/apps/tensorflow/tensorflow_check.py
* Use the new regression test syntax.
* Modify the command line options to be in sync with tensorflow 1.7.
Closes #373
> [test] Adapt Tensorflow tests for PE 18.07

- cscs-checks/tools/io/nco.py
* Adapt sanity checks to comply with the output format of the latest nco
version.
* Use the newest syntax for the regression test.
Closes #369
> [test] Adapt the nco test for PE 18.07

- cscs-checks/tools/profiling_and_debugging/nvprof.py
* Use new build system feature
* Use new syntax for test
Related to #397
> [test] Adapt nvprof test to PE 18.07

- cscs-checks/compile/haswell_fma_check.py
> [test] Adapt haswell_fma to buildsystems style

- cscs-checks/libraries/math/scalapack_compile_run.py
* Adapt to new test syntax.
* Reformat to be consistent with the coding style of ReFrame.
Fixes #384
> [test] Adapt the scalapack tests to use build systems

- cscs-checks/libraries/math/dgemm.py
* Adapt dgemm test to use the build systems future.
* Adapt dgemm to the new syntax.
Fixes #383
> [test] Adapt dgemm test to use build systems

- reframe/core/schedulers/slurm.py
- reframe/core/shell.py
- unittests/test_schedulers.py
* Use `filter` to filter out empty strings before finalizing shell.
* User raw string to suppress invalid escape sequence warning.
Fixes #407
> [bugfix] Filter out empty strings before writing preamble

- cscs-checks/cuda/cuda_checks.py
* Adapt cuda regression tests to build systems.
* Change to new regression test syntax.
Closes #394
> [test] Adapt cuda checks to build systems

- cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
- cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_scorep_mpi_omp
* Adapt to build systems.
* Adapt to new syntax.
* Add dependencies in Makefile for F90 to ensure that
Fortran modules are build before used.
Closes #367 
Addresses #397
> [test] Adapt scorep test to PE 18.07

- cscs-checks/compile/libsci_resolve.py
* Adapt to new regression test syntax.
* Adapt to build systems.
Closes #362 
Closes #393
> [test] Adapt libsci_resolve test to PE 18.07

- cscs-checks/libraries/io/hdf5_compile_run.py
* Adapt hdf5 regression tests to build systems.
* Change to new regression test syntax.
Closes #386
> [test] Adapt hdf5 tests to build systems

- cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
* Adapt the cuda_gdb regression test to build systems.
* Use new regression test syntax.
Addresses #397
> [test] Adapt cuda_gdb to build systems

- config/cscs.py
> [ci] New programming environments for Kesch

- cscs-checks/libraries/io/netcdf_compile_run.py
> [test] Adapt netcdf tests to build systems

- reframe/core/pipeline.py
- reframe/core/runtime.py
- reframe/utility/os_ext.py
- unittests/test_cli.py
- unittests/test_pipeline.py
- unittests/test_policies.py
- unittests/test_schedulers.py
- unittests/test_utility.py
> [bugfix] Add a persistent version of rmtree()

- docs/advanced.rst
- docs/reference.rst
- docs/tutorial.rst
- reframe/core/buildsystems.py
- reframe/core/pipeline.py
- tutorial/advanced/advanced_example1.py
- tutorial/advanced/advanced_example4.py
- tutorial/advanced/advanced_example8.py
- tutorial/example2.py
- tutorial/example3.py
- tutorial/example4.py
- tutorial/example7.py
- tutorial/example8.py
> [doc] Update documentation for the build systems feature

- cscs-checks/tools/profiling_and_debugging/perftools.py
- cscs-checks/tools/profiling_and_debugging/src/C++/Makefile_perftools
- cscs-checks/tools/profiling_and_debugging/src/C/Makefile_perftools
- cscs-checks/tools/profiling_and_debugging/src/Cuda/Makefile_perftools
- cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_perftools
* Adapt the perftools test to use build systems.
* Use new regression test syntax.
Solves the test failure due to the following error:
`attempt to set an aggregate field of different type. Required typespec: list[str]`
This is the last regression test that addresses issue #397.
Closes #397
> [test] Adapt perftools to use build systems

- reframe/frontend/cli.py
> [bugfix] Convert message for inexistent test files to warning

- docs/configure.rst
- docs/running.rst
- reframe/core/config.py
- reframe/core/runtime.py
- reframe/core/systems.py
- reframe/frontend/cli.py
- unittests/resources/settings.py
- unittests/test_config.py
- unittests/test_runtime.py
Also:
- The `logdir` system config attribute is deprecated and replaced by the
`perflogdir`.
Fixes #419.
> [bugfix] Fix reading of 'logdir' setting from system config

- docs/advanced.rst
- docs/tutorial.rst
- reframe/core/buildsystems.py
- reframe/core/pipeline.py
- unittests/test_buildsystems.py
- Build system takes care of passing some of the basic CMake flags, such
as the compiler and the compilation flags, by setting them from the
current environment.
- CMake projects are also auto-detected is `sourcepath` contains a
`CMakeLists.txt` file.
Closes #299.
Still todo:
> [feat] Add support for CMake

- ci-scripts/deploy.sh
- ci-scripts/genrelnotes.py
- Script for automatically creating a release.
- Tag and push new release
- Generated documentation and push to `gh-pages` branch
- Script for generating the release notes from the PR info
Fixes #189.
> [ci] Automate deployment and generation of release notes

- cscs-checks/libraries/math/trilinos_compile_run.py
The test fails for `PrgEnv-cray` since the executable gibes a segmentation fault for cray-trilinos/12.12.1.1
Fixes #385 
Fixes #363
> [test] Adapt trilinos regression test to PE18.08 and build systems

- reframe/core/runtime.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/statistics.py
- unittests/test_policies.py
Includes the migration of the `current_run` variable to the class RuntimeContext and related changes.
Closes #403.
> [feat] Use different stage and output directories for different retries of the same test

- config/cscs.py
This is a cleanup and reorganisation of the Kesch settings:
- Three programming environments (Cray, PGI, GNU)
- Two variants (MPI and non-MPI)
It is not final, since we are expecting the CS2M settings, but nonetheless I believe this one must be merged regardless. Only environments that are supposed to be stable must be put in the settings files. All other experiments should be done using the `-M` option or individually changing the settings file.
> [ci] Adapt Kesch settings

- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
- unittests/test_launchers.py
This PR changes basically the `Job` class by changing the default time limit.
- Time limit now defaults to `None`, meaning that the backends should
not impose any time limit on the running job.
- Build jobs do not have any time limit.
Fixes #465.
> [bugfix] Remove time limit from build jobs

- reframe/frontend/loader.py
- unittests/resources/checks/bad/relative_imports.py
> [bugfix] Remove the validation of the name of the test's base classes

- reframe/core/buildsystems.py
- reframe/core/config.py
- reframe/core/environments.py
- reframe/core/fields.py
- reframe/core/launchers/__init__.py
- reframe/core/modules.py
- reframe/core/pipeline.py
- reframe/core/runtime.py
- reframe/core/schedulers/__init__.py
- reframe/core/systems.py
- reframe/utility/typecheck.py
- unittests/test_fields.py
- unittests/test_typecheck.py
This PR offers a type checking facility for aggregate types based on [PEP484](https://www.python.org/dev/peps/pep-0484/) type hints. It also adjusts and simplifies the data validation descriptors (`reframe.core.fields`) by using the new facility.
More specifically, the `reframe.utility.typecheck` module defines types for aggregate data structures, such as lists, dictionaries etc. that you can use with the [`isinstance()`](https://docs.python.org/3.6/library/functions.html#isinstance) builtin function to recursively check the type of all the elements of an aggregate data structure. Suppose you have a list of integers, such as `[1, 2, 3]`, the following checks should hold:
```python
from reframe.utility.typecheck import List
l = [1, 2, 3]
assert isinstance(l, List[int]) == True
assert …
```
> [refactor] Better support for dynamic type checking and field validation

- cscs-checks/apps/espresso/espresso_check.py
Update total energy value: see https://github.com/eth-cscs/reframe/issues/375#event-1886508006
For more information, see the release notes at https://gitlab.com/QEF/q-e/tags/qe-6.2.0
```
- Some constants in the definition of PBE functionals were truncated to
6 significant digits. While not a bug, this could lead to tiny differences
with respect to previous results and other XC implementations (r13592)
```
Fixes #375.
> [test] Adapt QE test to PE18.08

- cscs-checks/apps/lammps/lammps_check.py
* Adapt to new regression test syntax.
Fixes #372
> [test] Adapt the LAMMPS test to PE18.08

- cscs-checks/system/io/ior_check.py
> [test] Adapt IOR checks to build systems

- cscs-checks/mch/collectives_halo.py
Also adjusted the collectives test, so as to combine them in a single test file, since the halo exchange test is almost identical to it.
Fixes #252.
> [test] Add MCH halo exchange benchmark

- cscs-checks/apps/tensorflow/tensorflow_check.py
* Adapt the tensorflow module name to reflect the latest PE, 18.08.
> [test] Adapt the TensorFlow module name for PE 18.08

- docs/advanced.rst
- docs/running.rst
- reframe/core/pipeline.py
- reframe/frontend/cli.py
- unittests/test_cli.py
> [feat] Add new command-line option for more verbose test listing

- cscs-checks/apps/cp2k/cp2k_check.py
Removing read-only files (no symbolic lik)
> [test] Remove read-only files attribute from the CP2K check

- reframe/frontend/statistics.py
- unittests/test_policies.py
> [bugfix] Fix retry report when test fails before the setup phase

- cscs-checks/apps/gromacs/gromacs_check.py
- cscs-checks/cuda/hpcg_check.py
- cscs-checks/libraries/math/dgemm.py
- cscs-checks/libraries/math/scalapack_compile_run.py
- cscs-checks/microbenchmarks/osu/flexible_a2a.py
- cscs-checks/microbenchmarks/osu/osu_tests.py
- cscs-checks/microbenchmarks/stream/stream.py
- cscs-checks/prgenv/helloworld.py
- cscs-checks/system/io/ior_check.py
- Monch-specific tests are commented as obsolete.
Fixes #489.
> [test] Remove Monch from supported systems

- cscs-checks/system/slurm/cscs_usertools.py
> [test] Adapt usertool tests to new syntax

- cscs-checks/libraries/math/trilinos_compile_run.py
> [test] Disable Trilinos tests which fail due to the corresponding module

- reframe/core/schedulers/__init__.py
* If `--flex-alloc-tasks` is an int do not perform further actions,
but directly assign `num_tasks`.
This allows to run on daint with specific number of `--flex-alloc-tasks` until #557 is fixed.
> [bugfix] Directly assign to `num_tasks` if `--flex-alloc-tasks` has an integer value

- cscs-checks/compile/libsci_acc_symlink.py
- cscs-checks/compile/libsci_resolve.py
* In addition, adapt the tests to the new syntax.
Closes #538
> [test] Run libsci_acc and libsci_resolve tests on compute nodes as well

- cscs-checks/apps/namd/namd_check.py
Closes https://github.com/eth-cscs/reframe-tests/issues/35
Closes https://github.com/eth-cscs/reframe-tests/issues/33
Closes #540.
> [test] Update NAMD test

- docs/advanced.rst
- docs/running.rst
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- tutorial/advanced/advanced_example9.py
* Add a tutorial example.
Closes #547
> [doc] Document the `--flex-alloc-tasks` feature

- reframe/core/pipeline.py
- reframe/core/runtime.py
Modifies the behaviour of ReFrame to create stage and output folders as in the following example:
```
/path/to/stage/sys/part/env/testname
/path/to/stage/sys/part/env/testname_retry1
/path/to/stage/sys/part/env/testname_retry2
```
Closes  #536.
> [feat] Update retries stage/output directory naming convention

- config/cscs.py
- docs/running.rst
- docs/tutorial.rst
- reframe/core/logging.py
- reframe/core/pipeline.py
- reframe/frontend/cli.py
- reframe/settings.py
- tutorial/example7.py
- unittests/resources/checks/frontend_checks.py
- unittests/resources/settings.py
- Reference tuple may optionally accept a fourth element specifying the unit of measurement of the performance value.
- The possibility of logging the units is also supplied.
- Unit tests are adjusted.
- CSCS performance logging configuration adjusted to log also the units.
- Documentation is added.
Fixes #321.
> [feat] Add support for units in performance references

- cscs-checks/cuda/cuda_checks.py
- cscs-checks/cuda/multi_gpu.py
- cscs-checks/libraries/io/netcdf_compile_run.py
- cscs-checks/libraries/math/scalapack_compile_run.py
- cscs-checks/mch/automatic_arrays.py
- cscs-checks/mch/check_ruby.py
- cscs-checks/mch/collectives_halo.py
- cscs-checks/mch/cuda_stress_test.py
- cscs-checks/mch/g2g_meteoswiss_check.py
- cscs-checks/mch/gpu_direct_acc.py
- cscs-checks/mch/gpu_direct_cuda.py
- cscs-checks/mch/openacc_cuda_mpi_cppstd.py
- cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
- cscs-checks/microbenchmarks/mpi/mpi_helloworld.py
- cscs-checks/microbenchmarks/osu/flexible_a2a.py
- cscs-checks/microbenchmarks/osu/osu_tests.py
- cscs-checks/microbenchmarks/stream/stream.py
- cscs-checks/prgenv/helloworld.py
- cscs-checks/prgenv/openacc_checks.py
- cscs-checks/system/slurm/slurm.py
- cscs-checks/tools/io/cdo.py
- cscs-checks/tools/io/nco.py
- cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
- cscs-checks/tools/profiling_and_debugging/ddt.py
- cscs-checks/tools/profiling_and_debugging/nvprof.py
The private tests have to be changed accordingly.
Partially addresses #589
> [test] Set `exclusive_access` for Kesch tests

- cscs-checks/mch/openacc_cuda_mpi_cppstd.py
This reduce the complexity, and forces to compile with MPI
If refremce does not need a version that can run without MPI, I suggest to integrate this change, otherwise just close the PR
> [test] Remove `ifdef USE_MPI` from the MCH OpenACC/CUDA/MPI/C++ test

- README.md
- docs/index.rst
> [doc] Move SC18 presentation & demo to docs

- reframe/utility/os_ext.py
* Replace `wait` with `communicate` for a spawned subprocess which
doesn't block when the output is relatively large.
Closes #557
> [bugfix] Fix deadlock in the flexible task allocation when the node list output is too large

- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
* The `SlurmNode` attibutes: partitions, active_features and `state` can
now be `None`.
* Throw a `JobError` when the `nodename` cannot be extracted.
* Adjust the unit tests to reflect the above changes.
Fixes #605
> [bugfix] Do not crash if Slurm node does not contain partition information

- cscs-checks/libraries/math/dgemm.py
- cscs-checks/libraries/math/src/dgemm.c
> [test] Promote DGEMM to a multi-node check

- cscs-checks/prgenv/ssh_environ_check.py
Closes https://github.com/eth-cscs/reframe/issues/510
> [test] Testing the environment of the login nodes when accessed remotely over SSH

- reframe/core/exceptions.py
- reframe/core/modules.py
- reframe/frontend/cli.py
- reframe/frontend/printer.py
- unittests/test_exceptions.py
> [feat] Print error information when a modules system operation fails

- docs/conf.py
Include Google Analytics tracking capabilities to the documentation. 
The information on how to do it was taken from [here](
https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#project-wide-configuration).
> [docs] Add Google Analytics track to documentation

- reframe/core/decorators.py
- unittests/resources/checks_unlisted/bad_init_check.py
- unittests/test_loader.py
> [bugfix] Improve handling of bad tests to avoid frontend crashing

- docs/advanced.rst
- docs/running.rst
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- unittests/test_schedulers.py
> [feat] Add support for setting a minimum number of required tasks in tests with flexible task allocation

- cscs-checks/microbenchmarks/likwid/likwid.py
Please indicate what group/user to use in line 62.
e.g. `getpwd.getuser()`
> [test] Add Likwid benchmarks for cache, memory and cross-socket bandwidths

- cscs-checks/apps/amber/amber_check.py
- cscs-checks/apps/cpmd/cpmd_check.py
- cscs-checks/apps/espresso/espresso_check.py
- cscs-checks/cuda/hpcg_check.py
- cscs-checks/microbenchmarks/hpcg/hpcg_check.py
- cscs-checks/prgenv/opencl_check.py
This is a first set of remaining tests being ported to the new syntax.
Fixes #592.
> [test] Porting tests to new syntax

- docs/running.rst
- reframe/frontend/cli.py
- Also move `-v` to `misc_options`.
Fixes #659.
> [doc] Document verbosity option

- reframe/core/pipeline.py
- unittests/test_pipeline.py
* Support directories in the `keep_files` field of a `RegressionTest`.
Closes #669 
Closes #668
> [feat] Add support for directories in `keep_files` attribute

- docs/configure.rst
- reframe/core/buildsystems.py
- reframe/core/environments.py
- reframe/core/fields.py
- reframe/frontend/cli.py
- unittests/test_buildsystems.py
- unittests/test_environments.py
This has been deprecated since 2.14. This change will also break configuration files that were setting the compiler flags through simple strings. Currently, a list of strings is required there as well. A message about the type mismatch is now being printed in such cases. This PR also brings a better message for type mismatches in attribute validation.
> [feat] Drop support for setting flags in environment

- reframe/core/config.py
- reframe/core/environments.py
- reframe/frontend/cli.py
- reframe/utility/os_ext.py
- unittests/test_utility.py
- Extend `expandvars()` to support command substitutions.
- Replace almost all usages of `os.path.expandvars()` with our version.
Fixes #682.
I still need to update a bit the documentation. I believe this is a feature rather than a bugfix.
> [feat] Support command substitution in variable expansion

- reframe/core/pipeline.py
- It has been deprecated since 2.14.
This is a follow-up of #678.
> [feat] Remove support for passing options to the `RegressionTest.compile()` method

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
- unittests/test_launchers.py
- unittests/test_schedulers.py
* `SlurmNode` attributes are set to empty sets if they cannot be
retrieved by the corresponding description.
* Create abstract method `get_all_nodes` on the base `Job` class.
* Remove method `get_partition_nodes`.
* Create more unittests for flexible allocation.
Fixes #692
> [bugfix] Fix bug ignoring a partition defined in 'access'

- README.md
- ci-scripts/deploy.sh
- docs/Makefile
- docs/_templates/breadcrumbs.html
- docs/conf.py
- docs/requirements.txt
Modifications based on moving the documentation to [readthedocs.org](reframe-hpc.readthedocs.org)
Closes #688
> [doc] Move documentation to readthedocs.org

- reframe/utility/os_ext.py
* Retry `rmtree` when an `OSError` with `Errno 16` is thrown,
in the custom ReFrame `rmtree` implementation.
Fixes #712
> [bugfix] Fix unit test failure with EBUSY when running on NFS filesystem

- reframe/core/schedulers/slurm.py
Modifying the way the set of available nodes is built in SLURM, in order to prevent erroneous entries (e. g. "not found")
Fixes #694
> [bugfix] Fix Slurm backend failures when trying node lists with inexistent nodes

- reframe/frontend/cli.py
- unittests/test_cli.py
This PR fixes the behaviour of the `-p` option when it is used with regular expressions. The `-p` option has also the effect of restricting the programming environments to run with. Although this still works fine in old-style cases, e.g., `-p PrgEnv-gnu`, it fails to do so when passing regular expressions, for example, `-p PrgEnv-(gnu|pgi)`. Although this will select all the tests that support either `PrgEnv-gnu` or `PrgEnv-pgi`, it will not run them. This PR fixes this.
> [bugfix] Define the set of run environments correctly when `-p` option is used with regular expressions

- reframe/core/systems.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- reframe/frontend/statistics.py
- unittests/test_cli.py
- unittests/test_policies.py
- All the test cases from a test are generated in advance, before calling the `runall()` method of `Runner`. A test case consists of (a clone of) the check, the partition and the environment on which it is running. `Runner` sees now only test cases.  Adaptations were made to the statistics and the retries feature.
- `SystemPartition` is now immutable. As a result, only the check needs to be copied in the test case.
- The redesign improves the retries feature; now only the failing test cases are retried not the whole test.
This step is a prerequisite for supporting dependencies of tests.
Closes https://jira.cscs.ch/browse/UES-281
> [refactor] Refactor frontend to execute directly test cases

- reframe/core/schedulers/__init__.py
- reframe/utility/__init__.py
- unittests/test_utility.py
* Create a list with the contents of `sched_access` and append
the `options` to it.
Fixes #728
> [bugfix] Fix crash in flexible task allocation due to refactoring of `SystemPartition`

- cscs-checks/prgenv/affinity_check.py
This would be my suggestion to fix the test. I sort the list of cores, because arguably
for performance we don't care which OpenMP thread is executed on which core.
It should be enough to check that the list of cores contains no duplicates and the total
number of distinct cores is the same relative to the reference.
> [test] Sort cores list in affinity test before comparing

- docs/tutorial.rst
You now named the variable exclusive_access, and not just exclusive anymore. This needs to be reflected in the documentation
> [doc] Fix reference to `exclusive_access` in tutorial

- reframe/frontend/executors/__init__.py
- reframe/utility/sandbox.py
- unittests/test_fields.py
- This fixes the problem with the duplicate module commands. Essentially, we revert back to the original solution of deep-copying the environments and the partitions. Environments are not immutable, since they hold a state. Similarly, since a partition holds a reference to its local environment, it's not immutable as well.
- This PR removes also the stale `Sandbox` class.
Fixes #737.
> [bugfix] Fix duplicate module commands emitted while executing test cases

- README.md
- ci-scripts/deploy.sh
- setup.py
* Add the `setup.py` script.
* Add the PyPI deployment steps to the deployment script.
Closes #336
> [ci] Prepare ReFrame for deployment to PyPI

- cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Fixes https://jira.cscs.ch/browse/UES-335
> [bugfix] Fix failure in Intel Advisor Roofline check

- ci-scripts/ci-runner.bash
- config/cscs.py
Also
- Temporarily remove `PrgEnv-pgi` from Dom.
> [ci] Disable running modified tests on Daint

- reframe/core/pipeline.py
- reframe/frontend/cli.py
- reframe/frontend/statistics.py
> [feat] Add option to print performance report

- cscs-checks/tools/profiling_and_debugging/perftools.py
https://jira.cscs.ch/browse/MAINT-17
> [test] Update perftools check for CLE7

- reframe/frontend/check_filters.py
- unittests/test_check_filters.py
* Throw a `ReframeError` if an invalid regex is passed to one of the
filtering functions.
* Add corresponding unittests.
Fixes #730
> [bugfix] Do not crash when invalid regular expressions are passed to the test selection options

- cscs-checks/microbenchmarks/shmem/shmem.py
- cscs-checks/microbenchmarks/shmem/src/shmem.cu
> [test] Add CUDA shared memory bandwidth benchmark

- cscs-checks/tools/profiling_and_debugging/berkeley-ert-nvprof.py
> [test] Add ert roofline check (gpu)

- docs/running.rst
- reframe/frontend/cli.py
> [feat] Print task allocation type (standard or flexible) for tests in detailed listing

- cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
The idea of making a test generic is to make no assumption as of what is `self.current_system`. This essentially means the following:
1. If you check against `self.current_system` or `self.current_partition` or `self.current_environ`, make sure you handle the case of an unknown system or environment.
2. If you are running on an unknown system, make sure to include `*` in `self.valid_systems` and `self.valid_prog_environs`.
3. If you are on a performance test, make sure that a `*` entry exists inside the `references` dictionary.   Its value should be `(0, None, None, 'unit')`.
Addresses [UES-339](https://jira.cscs.ch/browse/UES-339)
> [test] Make CUDA kernel latency tests generic

- docs/configure.rst
- reframe/core/modules.py
* Throw `ConfigError` for TMod4 versions older than 4.1.0.
* Throw `ConfigError` for TMod versions older than 3.2.
* Change the corresponding docs.
Fixes #780  
Fixes #781
> [bugfix] Add version checks for TMod and TMod4

- cscs-checks/microbenchmarks/stream/stream.py
Will fix [339](https://jira.cscs.ch/browse/UES-339)
> [test] Make the STREAM test generic

- cscs-checks/microbenchmarks/osu/osu_tests.py
Addresses [UES-339](https://jira.cscs.ch/browse/UES-339)
> [test] Make OSU tests check generic

- reframe/core/pipeline.py
- reframe/utility/sanity.py
* Allow `assert_reference` to accept a `tag` parameter.
* Use the performance tag in `assert_reference` at the
`check_performance` stage.
Fixes #753
> [feat] Print performance variable name in case of performance errors

- ci-scripts/genrelnotes.py
This allows us to get temporary release notes with any tag or `HEAD`, for example:
```
./ci-scripts/genrelnotes.py v2.17 HEAD
```
> [ci] Require full tag names in genrelnotes.py script

- reframe/frontend/dependency.py
- unittests/test_policies.py
This PR adds the validation routine for the test graph. Dependencies are validated at the test level only, so pseudo-dependencies like the following are not allowed:
```
(t0, e1) -> (t1, e1)
(t1, e0) -> (t0, e0)
```
Fixes [UES-283](https://jira.cscs.ch/browse/UES-283).
> [feat] Validate test case graph

- reframe/core/buildsystems.py
- reframe/frontend/executors/__init__.py
- reframe/utility/versioning.py
- unittests/test_buildsystems.py
- unittests/test_modules.py
- unittests/test_schedulers.py
Abstract classes must derive from `abc.ABC`.
> [refactor] Fix abstract class definitions

- cscs-checks/libraries/magma/magma_checks.py
- cscs-checks/libraries/magma/src/patch.txt
> [test] Revise MAGMA library benchmark

- reframe/core/logging.py
> [bugfix] Fix crash when using syslog logging handler with the `-v` option

- cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
> [test] Add `dom:mc` as valid system to `IntelRooflineAdvisorTest`

- cscs-checks/tools/profiling_and_debugging/intel_vtune_roofline.py
> [test] Add Intel Vtune roofline check

- docs/advanced.rst
- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
* Limit the default `max_concurrency` for make based build systems
to `1`.
* Make the corresponding changes to unittests and docs.
Fixes #792
> [feat] Limit concurrent build jobs to `1` by default in build systems

- cscs-checks/tools/profiling_and_debugging/intel_inspector.py
- cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Will fix [MAINT-81](https://jira.cscs.ch/browse/MAINT-81)
> [test] Update Intel tools version on Dom

- cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
- cscs-checks/microbenchmarks/alloc_speed/src/alloc_speed.cpp
> [bugfix] Fix timing in the allocation speed test

- reframe/frontend/dependency.py
- reframe/utility/__init__.py
- unittests/test_policies.py
- unittests/test_typecheck.py
- unittests/test_utility.py
- This is a necessary step for running interdependent tests with the
serial execution policy.
- This commit adds also an implementation of an ordered set.
This data structure is quite useful in several contexts and is indeed
used extensively in implementing the test dependencies. Its
implementation is based on an `OrderedDict`, but it provides the
complete `Set` and `MutableSet` interfaces.
Fixes UES-284.
> [feat] Implement topological sort of the test cases

- cscs-checks/apps/tensorflow/tf_horovod_check.py
@jgphpc found that in this test, doing `export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK` produce the message `libgomp: Invalid value for environment variable OMP_NUM_THREADS` because as `--cpus-per-task` is not defined, `SLURM_CPUS_PER_TASK` has no value. This PR adds `self.num_cpus_per_task = 12` to the test.
> [test] Set `num_cpus_per_task` to the TensorFlow Horovod test

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
Also:
- Remove the `JobState` abstraction, because it does not offer anything for the moment.
- Update Slurm job states.
Fixes #833.
> [bugfix] Fix ReFrame hanging when Slurm job gets OOM killed

- cscs-checks/system/slurm/slurm.py
> [test] Fix DefaultRequestGPUSetsGRES for updated slurm output

- reframe/core/schedulers/slurm.py
> [bugfix] Fix how Slurm states are mapped internally by the Slurm backend

- ci-scripts/ci-runner.bash
- config/cscs-ci.py
- config/cscs.py
This is for reducing the waiting times for the unit tests on Daint.
> [ci] Run unit tests for Daint in the CI partition

- Jenkinsfile
* This solves the problem of the ci trying to interpret github comments of 3rd party tools like codecov/pep8speaks.
* The comment is only taken into account if it starts with "@jenkins-cscs".
> [ci] Ignore irrelevant `@` comments when triggering the CI

- docs/running.rst
- reframe/core/modules.py
- unittests/test_modules.py
> [feat] Allow self loops in module mappings

- config/cscs-ci.py
- config/cscs.py
Updating the environments to account for the new meta-modules, which became necessary to support two different toolchain versions. The config file targets the production PE/17.06.
> [ci] Update system config for Kesch

- docs/configure.rst
- reframe/frontend/cli.py
- reframe/settings.py
We now issue a warning instead of an error and we fall back to a default system configuration, that is generic enough to allow ReFrame to run anywhere. User is pointed to the documentation for configuring ReFrame for her system.
Fixes #832.
> [feat] Fall back to a generic system configuration if system auto-detection fails

- reframe/core/schedulers/slurm.py
* Add logging info when an array job is detected and during file merging.
Related to #840 
Fixes #839
> [bugfix] Change to working directory before merging job array files

- reframe/core/pipeline.py
- unittests/resources/checks/src/code/Makefile
- unittests/test_pipeline.py
* Create corresponding unittest.
Fixes #860
> [bugfix] Do not ignore `sourcepath` if build system is explicitly set

- cscs-checks/apps/icon/rrtmgp_check.py
- Fix also compilation and modules
- Test fails to validate but it is outdated, so it is removed from production.
> [test] Remove RRTMGP from production

- reframe/frontend/cli.py
- This line was producing a fake error message when trying to load user modules
with the `-m` option.
Fixes #885.
> [bugfix] Fix wrong error message emitted when a user module is loaded with the `-m` option

- cscs-checks/mch/src/compute_cuda.cu
- cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
After merging the pull request #888, we are getting the following error:
```
MPI test on GPU with OpenACC using  8 tasks
Result : FAIL
Expected value sum(f3):  55. actual value: 110.
``` 
I think that there is a mistake in the fix submitted by @cosunae: the array that should be checked for the `EXPECTED_CPP_STD_SUM` is `f2` and not `f3`, since only the first one is called as argument in `call_cpp_std`. What do you think @lxavier?
P.S.: I have replaced `cudaThreadSynchronize()` with `cudaDeviceSynchronize()` in `compute_cuda.cu` since the first one is deprecated.
> Fix openacc_cuda_mpi_cppstd.F90

- cscs-checks/mch/automatic_arrays_acc.py
Given the new results after the CLE 7 upgrade, the performance needs to be adapted: 
see https://jira.cscs.ch/browse/MAINT-108
> AutomaticArrays reference performance on Dom

- cscs-checks/microbenchmarks/simd/nsimd.py
Will fix [488](https://jira.cscs.ch/browse/UES-488)
> [test] Add nsimd simd test

- reframe/core/pipeline.py
> [bugfix] Use login shell when building executables

- cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
> [test] Add performance report to Empirical Roofline Tool test

- cscs-checks/cuda/cuda_checks.py
- cscs-checks/microbenchmarks/osu/osu_tests.py
- cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
- cscs-checks/tools/profiling_and_debugging/ddt.py
- cscs-checks/tools/profiling_and_debugging/nvprof.py
We need to change `craype-accel-nvidia35` with `cudatoolkit/8.0.61`, otherwise the first module will load the more recent `cudatoolkit/9.2.148` and the checks will fail. See the results at 
https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-kesch-production-daily/detail/reframe-kesch-production-daily/165/pipeline/
> [test] Fix CUDA checks on Kesch

- reframe/core/environments.py
> [feat] Print compiler commands and flags when showing the environment configuration

- cscs-checks/system/slurm/slurm.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
Slurm was updated on Daint, so we need to back port some fixes of master to the 2.17 running on Daint. This PR back ports the following fixes: #835, #836, #837, #845.
> [bugfix] Back port Slurm fixes to ReFrame 2.17

- docs/reference.rst
- docs/tutorial.rst
- reframe/core/decorators.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- tutorial/advanced/advanced_example8.py
- tutorial/example2.py
- tutorial/example3.py
- tutorial/example4.py
- tutorial/example8.py
- unittests/test_pipeline.py
This PR offers a new syntax for attaching arbitrary regression test methods to pipeline stages. This is achieved using the `@run_before(stage)` or `@run_after(stage)` decorators, where `stage` is a string representing a pipeline stage. Valid pipeline stages are the following: `setup`, `compile`, `run`, `sanity`, `performance` and `cleanup`. This syntax will render less common or even obsolete the overriding of the pipeline methods, such as `setup()` for doing common tasks, such as setting the compilation flags. Users will not have to remember the signatures of the pipeline methods and to always call `super()`. For example, setting the compilation flags based on the programming environment can now be written very nicely as follows:
```python
@rfm.simple_test
class …
```
> [feat] Add new syntax for attaching arbitrary regression test methods to pipeline stages

- cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
> [test] Add performance report to the Intel Advisor test

- cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
> [test] Make the MpiP check generic

- cscs-checks/mch/g2g_meteoswiss_check.py
Update reference value of G2G using the average of last 14 timings in `/project/g110/reframe/perflogs/kesch/cn/G2GMeteoswissTest_1.log`, as discussed in CSCS RT #36752.
See http://jenkins-mch.cscs.ch/view/ReFrame/job/reframe-kesch-production-daily.
> [test] Update reference values of G2G [1] check

- reframe/frontend/dependency.py
- unittests/test_policies.py
1. Algorithm's complexity is now O(V+E). ~~The algorithm is doing a DFS traversal of the nodes and assigns each node a level (i.e., in which step it has been discovered). Then the nodes are arranged by increasing level and the test cases of each node (test) are expanded inline. Tests that are in the same level can be executed in any order (or in parallel).~~
The algorithm is simply doing a DFS traversal of the test graph (the original one, not the reversed) and marks a node as visited after all of its outcoming edges are explored. The visited nodes are kept in an ordered set, essentially providing at the end the topologically sorted tests.
2. ~~Additional information that will help execution policies in executing the test cases is now returned. More specifically, a dictionary that …
> [feat] Improve and simplify the topological sorting of the test cases

- config/cscs-ci.py
- config/cscs-pbs.py
- config/cscs.py
- reframe/frontend/cli.py
- reframe/settings.py
- tutorial/config/settings.py
- unittests/modules/testmod_bar
- unittests/modules/testmod_boo
- unittests/modules/testmod_foo
- unittests/resources/settings.py
- unittests/test_cli.py
- The `reframe_module` configuration option is now ignored; a warning message is issued.
- It is replaced by the `-u|--unload-module MOD` option.
Fixes #821.
> [feat] Replace `reframe_module` configuration option with command line option

- docs/running.rst
- reframe/core/pipeline.py
- reframe/core/runtime.py
- reframe/frontend/cli.py
This  PR adds the option `--non-default-craype` that enables ReFrame to test non-default Cray programming environments. This option causes ReFrame to export properly the `LD_LIBRARY_PATH` after loading any additional user modules. Use as follows:
```
module load cdt/19.09   # load target PE
reframe ... --non-default-craype -r
```
Fixes #895.
> [feat] Enable easy testing of non-default Cray programming environments

- cscs-checks/apps/gromacs/gromacs_check.py
Additionally, I have removed the obsolete Monch tests.
> [test] Update Gromacs reference value

- cscs-checks/mch/automatic_arrays_acc.py
Given the new results after the CLE 7 upgrade, the performance needs to be adapted: see https://jira.cscs.ch/browse/MAINT-108
> [test] Update reference for AutomaticArrays test on Dom

- reframe/core/decorators.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_pipeline.py
- unittests/test_policies.py
This PR provides a mechanism around the low-level `getdep()` function that is used to access information on the dependencies of a test. The syntax follows the paradigm of the `@run_before` and `@run_after` decorators  as introduced in #920. The following shows a more concrete example:
```python
import reframe as rfm
@rfm.simple_test
class T0(rfm.RegressionTest):
def __init__(self):
...
self.x = 1
@rfm.simple_test
class T1(rfm.RegressionTest):
def __init__(self):
...
self.depends_on('T0')
@rfm.require_deps
def sety(self, T0):
self.y = T0().x + 1
```
The `@require_deps` will bind all arguments of the decorated function to the corresponding test dependencies by name. In the above example, the `T0` argument will be bound to the `T0` test, so that its information can be retrieved when the …
> [feat] Add syntax for running functions after dependency resolution

- docs/configure.rst
- reframe/core/launchers/registry.py
- reframe/core/launchers/ssh.py
- unittests/test_launchers.py
This PR adds a "parallel" job launcher that uses directly SSH. Here is how to configure:
```python
'partition_name': {
'scheduler': 'local+ssh',
'access': ['-l admin', 'remote.host'],
'environs': ['builtin'],
}
```
This launcher will use the partition's `access` parameter in order to set up the SSH connection.
The last argument is always the remote host and it is recommended that it is a separate element in the list, since this will allow you to define additional launcher options in your tests, if needed, without surprises. The environment is *not* propagated; the `environs` option is there only for enabling the testing of this partition. Finally, the `ssh` client will be executed with `BatchMode=yes`, so that password-less access to the remote host must have been set up.
Fixes #880. …
> [feat] Add SSH job launcher

- cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
> [test] Update IPM check with new Cray path to PAPI (`PAT_BUILD_PAPI_LIBDIR`)

- reframe/core/environments.py
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/pbs.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- reframe/utility/__init__.py
- unittests/test_cli.py
- unittests/test_environments.py
- unittests/test_modules.py
- unittests/test_pipeline.py
- unittests/test_schedulers.py
- unittests/test_utility.py
This PR introduces two major enhancements.
The job associated with the test is only minimally created inside `setup()`. Any attributes related to its run configuration (e.g., `num_tasks`, `num_tasks_per_node` etc.) are set when preparing the job script and just before launching the test. This change required that these attributes become writeable in `Job`'s interface.
This enhancement allows you to set the `num_tasks` of a test based on the current partition or the environment in a cleaner way anytime after setup. For example:
```python
@rfm.run_before('run')
def set_num_tasks(self):
if self.current_partition.fullname == 'foo:part':
self.num_tasks = 8
else:
self.num_tasks = 4
```
In case of flexible tests, the test's `num_tasks` attribute is set to the actual number of tasks assigned to …
> [feat] Lazy evaluation of job-related attributes and environments

- cscs-checks/cuda/nvml_check.py
- cscs-checks/cuda/src/nvml_example.patch
Will fix UES-567
- Adding `craype` tag
- Removing operation mode, as only compute mode is supported.
> [test] Update NVML with src from cudatoolkit

- cscs-checks/libraries/io/netcdf_compile_run.py
The problem is now fixed and this flag is not needed. It actually makes the test fail.
Will fix MAINT-174
> [test] Remove workaround for NetCDF C++ test with PGI

- cscs-checks/mch/automatic_arrays_acc.py
> [test] Port automatic arrays check to Tiger

- docs/tutorial.rst
- reframe/core/pipeline.py
- unittests/test_pipeline.py
See documentation for more details + unit tests.
Fixes #991.
> [bugfix] Support inheritance in pipeline hooks

- docs/advanced.rst
- docs/configure.rst
- docs/reference.rst
- reframe/core/buildsystems.py
- reframe/core/containers.py
- reframe/core/pipeline.py
- tutorial/advanced/advanced_example10.py
- tutorial/config/settings.py
> [doc] Document the container platforms feature

- reframe/core/containers.py
- This will allow us to easily remove `ShifterNG` backend when it goes out of support and the documentation will not be confusing.
- I also updated the documentation slightly.
> [refactor] Make `Sarus` container platform backend a base class

- config/cscs-ci.py
- config/cscs-pbs.py
- config/cscs.py
- docs/running.rst
- reframe/core/logging.py
- reframe/core/pipeline.py
- reframe/frontend/statistics.py
* Change documentation regarding the performance report format.
Addresses #915.
> [feat] Write the number of tasks in performance report

- cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
- cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
- cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
- cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
- cscs-checks/tools/profiling_and_debugging/src/Cuda/.in.cudagdb
> [test] Minor fixes for CLE7

- cscs-checks/apps/gromacs/gromacs_check.py
```
module load cray-python/3.7.3.2
module use /home/users/vholanda/spack/share/spack/modules/cray-cnl7-ivybridge
mkdir -p /home/users/vholanda/reframe-run
cd reframe-run
../reframe/reframe.py -C ../reframe/config/tiger.py -c ../reframe/cscs-checks/apps/gromacs/gromacs_check.py -n GromacsGPUCheck_small_prod -r
Command line: ../reframe/reframe.py -C ../reframe/config/tiger.py -c ../reframe/cscs-checks/apps/gromacs/gromacs_check.py -n GromacsGPUCheck_small_prod -r
Reframe version: 2.20-dev2
Launched by user: vholanda
Launched on host: tiger
Reframe paths
=============
Check prefix      : 
Check search path : '../reframe/cscs-checks/apps/gromacs/gromacs_check.py'
Stage dir prefix     : /home/users/vholanda/reframe-run/stage/
Output dir prefix    : /home/users/vholanda/reframe-run/output/ …
```
> [daint-gpu] Port Gromacs check to Tiger

- docs/running.rst
> [doc] Fix literal include lines in performance logging documentation

- cscs-checks/compile/libsci_resolve.py
* The flag for tracing the symbol when linking does not produce any
output when xalt 2.7.10 is loaded, thus we used readelf.
Fixes MAINT-210, MAINT-216.
> [test] Fix nvidia and libsci/mkl resolve tests

- config/cscs.py
- cscs-checks/tools/jupyter/jupyter_tests.py
Fixes [UES-522](https://jira.cscs.ch/browse/UES-522).
> [test] Add JupyterHub submission test

- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
* Separate the retrieval of Slurm node descriptions and
creation of `SlurmNode` instances when nodes
in flexible task allocation.
* Make the necessary unittests changes to test for invalid
node descriptions.
Fixes #1031
> [bugfix] Ignore invalid Slurm nodes in flexible task allocation

- cscs-checks/cuda/multi_gpu.py
- docs/deferrables.rst
- reframe/core/deferrable.py
- reframe/core/pipeline.py
- reframe/utility/sanity.py
- unittests/resources/checks_unlisted/deps_complex.py
- unittests/test_deferrable.py
- unittests/test_pipeline.py
- unittests/test_policies.py
- unittests/test_sanity_functions.py
- `make_deferrable()` is renamed to `defer()` and is moved inside
`reframe.utility.sanity`.
- `evaluate()` is moved inside `reframe.utility.sanity`
- The old functions are deprecated.
- Functions are now publicly visible and documentation is updated.
- Tests that were making use of them are adapted.
Fixes #1038.
> [feat] Rename`make_deferrable()` to `defer()` and make it publicly available along with `evaluate()`

- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
This is a standard replacement for the builtin `print()` function. The key difference is that it returns its arguments so that you can chain it inside sanity expressions for debugging. There is a also a little tweak in the default arguments binding, which is explained in the documentation.
Fixes #1030.
> [feat] Add a `print()` sanity function

- docs/configure.rst
- reframe/core/launchers/mpi.py
Fixes #1059.
@rtmclay Can you try this out? It's the same as the one we tried on the fly, but just to be on the safe side.
> [feat] Add support for TACC's ibrun parallel job launcher

- reframe/core/containers.py
- unittests/test_containers.py
> [feat] Allow passing arbitrary options to a container platform

- docs/advanced.rst
- docs/running.rst
- reframe/__init__.py
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/slurm.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- unittests/test_schedulers.py
* Change the command line option `--flex-alloc-tasks` to `--flex-alloc-nodes` and make it work based on node numbers.
* Change classes and unittests.
* Update documentation.
Fixes #1037
> [bugfix] Change command line option --flex-alloc-tasks to --flex-alloc-nodes

- reframe/core/runtime.py
- unittests/test_cli.py
- unittests/test_schedulers.py
> [bugfix] Fix unit test failure for scheduler backends when run alone

- reframe/frontend/cli.py
There is also the '-L' option for 'listing matched regression checks with a detailed description'. Message could also be `No action specified. Please specify '-l'/'-L' for listing or '-r' for running.` to be more accurate.
Closes #1060.
> [feat] Improve error message when no action is specified

- reframe/frontend/statistics.py
> [feat] Add nodelist in failure report

- reframe/core/launchers/__init__.py
- reframe/core/launchers/local.py
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
- unittests/test_launchers.py
- unittests/test_schedulers.py
Scheduler logic is now separated from the job information. The `Job` class still offers the same API to its clients, but it delegates all the scheduler-specific work to a scheduler backend. The advantage of this design is that we can easily and cleanly support custom configurations for the backend schedulers. All scheduler backends inherit from the `JobScheduler` base abstract class. This class is intentionally left without any implementation, because it needs to serve as a pure interface, which the scheduler backends must implement. The key difference of this interface compared to the current one is that these function take the user job as an argument instead referring to it through `self`.
I fixed also a minor bug in the local launcher, that actually didn't ignore `options`, if these …
> [refactor] Redesign job scheduler backends

- reframe/core/launchers/mpi.py
- unittests/test_launchers.py
> [feat] Emit job options to `aprun` command line

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/slurm.py
- unittests/resources/checks/hellocheck.py
- unittests/test_schedulers.py
This introduces a an API for a Node, which the Job talks to for determining
whether the node is available or not. Different backends implement that
differently.
Also made private the `SlurmNode` class and the `create_nodes()` function.
Fixes #1087.
> [bugfix] Fix crash of local scheduler with flexible allocation

- reframe/core/logging.py
- reframe/frontend/cli.py
- reframe/utility/os_ext.py
- unittests/test_utility.py
> [feat] Print repository's revision hash when ReFrame's version is requested

- config/cscs-ci.py
- config/cscs-pbs.py
- config/cscs.py
- docs/configure.rst
- reframe/core/config.py
- tutorial/config/settings.py
- unittests/resources/settings.py
- unittests/test_config.py
- The user specified environments are always of type `ProgEnvironment`.
- Remove the key from all the configuration files.
- Update unit tests
- Update documentation
I am not issuing now a deprecation warning if `type` is specified, because I am planning a redesign of the configuration infrastructure and more things will be deprecated there.
Fixes #1078.
> [bugfix] Remove `type` key from the environment configuration

- reframe/frontend/executors/policies.py
- unittests/resources/checks_unlisted/deps_complex.py
- unittests/test_policies.py
Async policy enters infinite loop when executing dependencies that fail before/after the setup phase.
I also made the dependency unittests more strict so that they check that all cases either were successful or failed. Checking the `num_cases` of `stats` is not enough to make sure a testcase was accounted for in the final summary.
Fixes #1082 .
> [bugfix] Fix dependency bug in async policy

- reframe/frontend/statistics.py
* Do not print the performance report table if no performance report
values are present.
* Put printing of num_tasks in the correct if block.
Fixes #1081
> [bugfix] Fix incomplete printout of the performance report in case of test failures

- reframe/core/pipeline.py
- unittests/test_pipeline.py
* Move the handling of the `extra_resources` during the
`run` phase.
* Change the corresponding unit test to reflect the change.
Fixes #1089
> [feat] Evaluate `extra_resources` just before job submission

- docs/running.rst
- docs/tutorial.rst
- reframe/frontend/cli.py
> [feat] Make the asynchronous execution policy default

- cscs-checks/cuda/cuda_checks.py
- Prefix the executable with `./`. This will allow the test to run on systems with the `aprun` job launcher.
- Remove unnecessary call to base `__init__()`.
Fixes UES-657.
> [test] Make SimpleMpiCheck with CUDA more robust

- docs/running.rst
- reframe/frontend/cli.py
- unittests/test_cli.py
* Deprecate using the checkpath command line option multiple times
and issue a warning.
* Create unittest for colon separated paths.
* Add the change to the documentation.
Fixes #1120.
> [feat] Do not allow chaining of the `-c` option; pass multiple paths as a colon separated list 

- cscs-checks/libraries/io/hdf5_compile_run.py
- cscs-checks/libraries/io/netcdf_compile_run.py
- cscs-checks/libraries/math/scalapack_compile_run.py
- cscs-checks/libraries/petsc/petsc_helloworld.py
- cscs-checks/prgenv/helloworld.py
- Update PETSc test based on new Cray PE defaults
- Modernize syntax of several other tests
Fixes UES-658.
> [test] Improvements and fixes for static linking tests

- cscs-checks/libraries/math/trilinos_compile_run.py
- cscs-checks/mch/g2g_meteoswiss_check.py
- cscs-checks/mch/gpu_direct_cuda.py
- cscs-checks/tools/profiling_and_debugging/perftools.py
I also  updated the syntax in the touched tests.
Fixes UES-649.
> [test] Remove stale FIXME and NOTE tags from tests

- requirements.txt
- schemas/config.json
- schemas/settings.py
This PR introduces only the syntax of the new (upcoming) configuration. The new configuration will be fully JSON compliant and will provide more flexibility.
The whole configuration is now stored (in its Python version) as a JSON object in the `site_configuration` variable. Systems, partitions and environments are now defined as JSON objects inside a JSON array. In the past, these were entries of Python dictionary, whose keys corresponded to the names of the represented objects (systems, partitions, etc.). The name is now a property instead. This will solve the issue of random initialization of systems (see #66). During system auto-detection, ReFrame will now try the system definitions in order and pick the configuration entry that was first matched.
All logging configuration parameters …
> [feat] Introduce new configuration syntax and validation schema

- docs/running.rst
- reframe/core/logging.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/slurm.py
- unittests/test_logging.py
This PR adds a new time formatting directive for log record timestamps, namely the GNU `date` extension `%:z`. This directive will print the time zone difference in fully RFC3339 compliant way, i.e., `+/-HH:MM` instead or `+/-HHMM`, which `%z` prints.
This PR also replaces how `Job`'s completion time is stored and retrieved, also inside the Slurm backend. We use `time.time()` to retrieve the time in seconds from the Epoch instead of `datetime.now()`, because `datetime` does not store time zone information. Also all backends are now required to provide the completion time in seconds from the Epoch, so Slurm backend was modified accordingly.
Fixes #1061.
@brandongc FYI
> [feat] Support RFC3339 compliant time zone formatting when logging time fields

- cscs-checks/libraries/io/hdf5_compile_run.py
- cscs-checks/libraries/io/netcdf_compile_run.py
- cscs-checks/libraries/math/scalapack_compile_run.py
- cscs-checks/prgenv/helloworld.py
* Workaround for Cray Bug #255707.
> [test] Introduce workaround for static linking tests on Dom

- cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
Change of module loaded with the cuda libraries on Kesch to fix https://jira.cscs.ch/browse/UES-718
> [test] Fix cuda module for GpuBurn on Kesch

- cscs-checks/microbenchmarks/dgemm/dgemm.py
I couldn't reproduce the failure of `DGEMMTest` on Kesch reported in  https://jira.cscs.ch/browse/UES-717. I have only adjusted the number of CPUs per task (`num_cpus_per_task`) for Arolla and Tsa.
> [test] Adjust num_cpus_per_task on Arolla and Tsa

- reframe/frontend/cli.py
Instead of printing
```
...
Reframe paths
=============
Check prefix      :
Check search path : '/tmp/str.py'
Current working dir  : /tmp
Stage dir prefix     : /tmp/stage/
Output dir prefix    : /tmp/output/
Perf. logging prefix : /tmp/perflogs
...
```
Reframe now adds the current working dir to the output like
```
...
Reframe paths
=============
Check prefix      :
Check search path : '/tmp/str.py'
Current working dir  : /tmp
Stage dir prefix     : /tmp/stage/
Output dir prefix    : /tmp/output/
Perf. logging prefix : /tmp/perflogs
...
```
> [feat] Print the current working directory in "ReFrame paths" output section

- config/cscs-ci.py
- config/cscs-pbs.py
- config/cscs.py
- config/tiger.py
- reframe/settings.py
- schemas/settings.py
- tutorial/config/settings.py
- unittests/resources/settings.py
Use `check_job_completion_time` with timezone info for performance logging formatting instead of `asctime` attribute.
The changes are applied in the cscs configuration files, the example and the tutorial configuration.
Fixes UES-709.
> [misc] Use `check_job_completion_time` with timezone info for performance logging in all settings files

- cscs-checks/libraries/petsc/petsc_helloworld.py
for static linking the C++ compiler is used until Cray fixes the problem
Cray Bug #255701
> [test] Implement workaround for PETSc test when using PrgEnv-intel and static linking

- unittests/test_policies.py
> [bugfix] Fix random 'test_sigterm' unit test failure

- reframe/core/pipeline.py
- reframe/utility/os_ext.py
- unittests/test_utility.py
* Also create `is_interactive` function in `os_ext` to check whether
the session is interactive.
* Add unittest for the above function.
Fixes #1194
> [bugfix] Fix crash when creating a regression test interactively

- unittests/test_policies.py
* Increase the time of the actual submitted SleepTest.
* Use `multiprocessing.Manager` and communicate with `Namespace`
objects of the `Manager` instance between parent-child processes.
Fixes #1216
> [bugfix] Improve unit tests for the handling of the TERM signal

- .travis.yml
- docs/started.rst
- reframe/__init__.py
- requirements.txt
- setup.py
* Add note regarding dropping support of Python 3.5 in docs.
* Stricter requirements for a newer pytest version.
Fixes #1202
> [feat] Drop support for Python 3.5

- unittests/resources/checks_unlisted/selfkill.py
- unittests/test_policies.py
* Explicitly call `os.kill` from a regression check.
Related to #1217
> [bugfix] Make unit test for TERM signal handling more robust

- cscs-checks/compile/haswell_fma_check.py
- cscs-checks/libraries/hpx/hpx_hello_world.py
- cscs-checks/mch/automatic_arrays_acc.py
- cscs-checks/mch/collectives_halo.py
- cscs-checks/mch/cuda_stress_test.py
- cscs-checks/mch/fieldextra_check.py
- cscs-checks/mch/g2g_meteoswiss_check.py
- cscs-checks/mch/gpu_direct_acc.py
- cscs-checks/prgenv/helloworld.py
- cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
- docs/running.rst
- docs/tutorial.rst
- reframe/core/pipeline.py
- unittests/test_pipeline.py
* Fix checks that don't contain units in performance reference tuples.
* Add unit test.
* Documentation fixes.
Fixes #1147
> [feat] Impose units in performance reference tuple

- reframe/core/schedulers/slurm.py
* Use the submission datetime instead of the current datetime with sacct.
Fixes #1083
> [bugfix] Fix Slurm backend deadlock when ReFrame runs through midnight

- cscs-checks/microbenchmarks/osu/osu_tests.py
Removing `kesch:pn` from `FlexAlltoallTest`, as suggested by @vkarak in https://jira.cscs.ch/browse/UES-740. 
Please note that if we want to keep it, I can just export the correct path for ` MV2_USE_GPUDIRECT_GDRCOPY` in the check, as I have reported in https://jira.cscs.ch/browse/UES-533.
As a matter of fact, `daint:mc`, `dom:mc`, `arolla:pn` and `tsa:pn` are also listed in the check.
> [test] Remove kesch:pn from supported systems of FlexAlltoallTest

- reframe/core/exceptions.py
- reframe/utility/os_ext.py
- unittests/test_exceptions.py
- unittests/test_utility.py
Also:
- Made stricter some unit tests.
- Removed the `grep_command_output()` function, since it was unused.
Fixes #1226
> [bugfix] Fix formatting of the error message when an OS command fails

- reframe/frontend/printer.py
This is a simple bug fix for the progress report. The testcases that print `ERROR` have already printed `OK` before so `_progress_count` should not be updated. The `(x/total)` message will also be omitted.
> [bugfix] Do not update progress count when a test fails with status ERROR

- cscs-checks/apps/cp2k/cp2k_check.py
I have used the performance data stored in `/apps/daint/UES/jenscscs/regression/production/logs/daint/gpu` starting November 7th 2019, after the last upgrade of Piz Daint:
- `Cp2kGpuCheck_small_prod.log`, 139 data points, average `241.3 s`, 95% within 3.1% threshold (nonetheless I propose to use the 5% threshold, since I don't know if it is the case to go below 5%)
- `Cp2kGpuCheck_small_prod.log`, 138 data points, average `199.6 s`, 95% within 6% threshold
> [test] Update CP2K GPU checks

- cscs-checks/apps/cp2k/cp2k_check.py
I have used the performance data stored in `/apps/daint/UES/jenscscs/regression/production/logs/daint/mc` starting November 7th 2019, after the last upgrade of Piz Daint:
- `Cp2kCpuCheck_small_prod.log`, 138 data points, average `180.9 s`, 95% within ~7.5% threshold (rounded to 8%)
> [test] Update CP2K CPU small check

- cscs-checks/apps/espresso/espresso_check.py
I have used the performance data stored in `/apps/daint/UES/jenscscs/regression/production/logs/daint/mc` starting November 7th 2019, after the last upgrade of Piz Daint:
- `QECheck_large.log`, 145 data points, average `149.7 s`, 95% within 52% threshold
- `QECheck_small.log`, 164 data points, average `147.3 s`, 95% within 41% threshold
The thresholds required to reach the 95th percentile are huge, since the standard deviation of the samples is high. 
However, the thresholds would be even higher if I select only recent data points after the last maintenance (January 29th 2020).
> [test] Update QE CPU checks

- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
* Fix `AttributeError` raised when trying to mutate a `SequenceView`
object in the `filternodes` method of the slurm scheduler.
* Add a corresponding unittest.
Fixes #1258
> [bugfix] Fix `AttributeError` in flexible node allocation from the Slurm backend

- cscs-checks/compile/libsci_resolve.py
- cscs-checks/libraries/io/hdf5_compile_run.py
- cscs-checks/libraries/io/netcdf_compile_run.py
- cscs-checks/libraries/math/scalapack_compile_run.py
- cscs-checks/mch/automatic_arrays_acc.py
- cscs-checks/mch/gpu_direct_acc.py
- cscs-checks/microbenchmarks/stream/stream.py
- cscs-checks/prgenv/helloworld.py
- cscs-checks/prgenv/mpi_t.py
- cscs-checks/prgenv/openacc_checks.py
- cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
- cscs-checks/tools/profiling_and_debugging/notool.py
> [test] Implement Cray linker workaround for CLE7.0.UP01.PS09

- cscs-checks/apps/greasy/greasy_check.py
For the current `daint:mc` we need to remove the `'gres': 'craynetwork:72'` resource in case the application is a serial one.
Fixes UES-826.
> [test] Update GREASY test

- reframe/frontend/statistics.py
- unittests/test_cli.py
I have increased the first column from 11 to 13. Because the `compile_wait` has length of 12.
Fixes #1260
> [bugfix] Fix string alignment in failure statistics

- cscs-checks/microbenchmarks/stream/stream.py
I also added `'*'` to all `PrgEnv`s because it makes the tests more generic and capable of running in other centres that have the same nomenclature as ours
Fixes #1254
> [test] Enable units in StreamTest when running with an unknown programming environment

- reframe/core/schedulers/torque.py
- unittests/test_cli.py
I added the code proposed by @ZQyou to the torque scheduler. @ZQyou can you please check if it works for you?
Fixes #1238
> [bugfix] More robust completion check for the Torque scheduler

- docs/running.rst
- reframe/core/logging.py
- unittests/test_cli.py
This PR adds an additional field to the `LoggerAdapter` class [as suggested](https://github.com/eth-cscs/reframe/issues/1261#issuecomment-618281572) by @vkarak. This new field holds the original UNIX time and it is used to format the `check_job_completion_time` field. 
Fixes #1261 
Fixes #1265
> [bugfix] Fix logging crash when increasing verbosity level

- ci-scripts/ci-runner.bash
- unittests/resources/checks/frontend_checks.py
- unittests/resources/checks_unlisted/selfkill.py
It fixes the deprecation warnings on the unittests and changes jenkins script so that it treats `ReframeDeprecationWarning` as error.
Fixes #1285
> [bugfix] Fix deprecation warnings in unit tests

- cscs-checks/microbenchmarks/dgemm/dgemm.py
The dgemm check uses the linker options
-mkl -static-intel
now which are conform with the man pages of icc
Fixes UES-851.
> [test] Fix DGEMM test for PrgEnv-intel

- cscs-checks/libraries/gridtools/gridtools_tests.py
> [test] Update GridTools tests

- reframe/core/runtime.py
- reframe/frontend/cli.py
Also remove perflogdir from the output.
Fixes #1294.
> [bugfix] Use absolute path as stage and output directory prefixes

- cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
This adds a sanity check that the test has been assigned a number of processes that can be factorized as needed by the test.
Fixes UES-852.
> [test] Add specific failure message in HPCG test when number of processes cannot be factorized

- cscs-checks/system/slurm/slurm.py
I also removed unnecessary programming environments from `valid_prog_environs`.
Fixes UES-859.
> [test] Fix Slurm constraint check for cabinets

- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/torque.py
- unittests/test_schedulers.py
* Create the stdout, stderr files if the don't exist
to make the torque scheduler treat the job as finished.
Fixes #1298
> [bugfix] Fix possible deadlock in PBS-based scheduler backends when a job is cancelled immediately after submission

- docs/migration_2_to_3.rst
- reframe/core/config.py
- tools/convert-config
- tools/convert_config.py
> [feat] Allow users to set the output file in the configuration conversion tool

- docs/migration_2_to_3.rst
- reframe/core/config.py
- tools/convert_config.py
> [feat] Add JSON support to the configuration conversion tool

- reframe/frontend/cli.py
* The chosen level of verbosity was not affecting the printer after
the update of the site configuration.
Fixes #1295
> [bugfix] Fix behaviour of verbosity option

- reframe/core/config.py
- unittests/test_config.py
Now the conversion tool will create different handlers for every different `perflogdir` in the old configuration file.
Closes #1280.
> [bugfix] Fix handling of `perflogdir` in the configuration conversion tool

- docs/requirements.txt
This fixes the `jsonschema` import error when trying to build the documentation on readthedocs.
> [doc] Add 'jsonschema' to documentation requirements

- docs/tutorial_basic.rst
- reframe/frontend/cli.py
> [doc] Update help message

- reframe/core/config.py
- unittests/test_config.py
> [bugfix] Fix configuration option value for non-existent name-addressable configuration objects

- reframe/frontend/executors/policies.py
- unittests/resources/checks/frontend_checks.py
- unittests/test_policies.py
Fixes #1330 
Exceptions raised from build tasks within `compile_wait` with the async policy are not caught by `reschedule_task`, and so bubble up and stop the reframe process. Any queued jobs then get abandoned.
This PR catches exceptions that should cause the test, but not the whole reframe run, to fail
> [bugfix] Fix early abort when compile step fails with async policy

- cscs-checks/apps/quantumespresso/quantumespresso_check.py
This pull request is addressing https://jira.cscs.ch/browse/UES-880: the performance values of the new QuantumESPRESSO GPU small and large checks can be retrieved from Kibana.
Starting April 30th, there are 20 records available for the two checks, with the following statistics:
Test   |      Average (s)      |  Standard Deviation (s)
----------|-------------:|------:
small | 60.697 | 1.058
large | 53.841 | 0.868
Setting the reference values as `61 s` and `54 s` with upper threshold `0.05` will ensure that 95% of the 20 records will fall within the threshold, since only one record lies outside in both data sets.
> [test] Update QuantumESPRESSO GPU test

- docs/config_reference.rst
- reframe/core/buildsystems.py
- reframe/core/launchers/mpi.py
- unittests/test_launchers.py
testing functionality of UPC and UPC++ code requires reframe to know how to compile and run UPC code. This PR adds those features
> [feat] Add support for UPC language and launchers

- test_reframe.py
This is to prevent false failures in case the user has set a ReFrame environment variable.
> [bugfix] Unset all ReFrame environment variables before running the unit tests

- cscs-checks/system/slurm/slurm.py
Test failed due to bug in SLURM on Tsa/Arolla, see also:
https://jira.cscs.ch/browse/UES-755
> [test] Exclude Slurm memory overconsumption test from Tsa

- config/cscs.py
- The classic CCE compiler and the corresponding modules are removed for CCE 10, which is the default in CDT 20.06, so this PR removes the corresponding environment on Dom.
- Similarly we add this classic CCE environment on Daint, since it has been forgotten.
Fixes UES-927.
> [test] Remove PrgEnv-cray_classic from Dom and add it to Daint

- cscs-checks/apps/jupyter/check_ipcmagic.py
Replace `pre_run` with `prerun_cmds`
> [test] Fix deprecation warning in IPCMagicCheck

- reframe/schemas/config.json
ReFrame 3 upstreamed support for UPC and UPC++ launchers from Berkeley Lab. This PR fixes a missed change to the launcher schemes. Without this, tests which request the `upcrun` or `upcxx-run` launchers will fail because ReFrame cannot find them in this list.
> [bugfix] Add missing launchers `upcrun` and `upcxx-run` in configuration schema

- config/cscs-ci.py
- config/cscs.py
- cscs-checks/cuda/cuda_checks.py
- cscs-checks/mch/automatic_arrays_acc.py
- cscs-checks/mch/cuda_stress_test.py
- cscs-checks/mch/gpu_direct_cuda.py
- cscs-checks/prgenv/helloworld.py
- cscs-checks/system/slurm/slurm.py
- cscs-checks/tools/io/cdo.py
- cscs-checks/tools/io/nco.py
Changes to configuration and tests to include new PEs on Tsa/Arolla.
> [test] Update configuration and tests for MCH system

- reframe/frontend/cli.py
> [bugfix] Process execution modes before configuring logging

- reframe/core/decorators.py
> [doc] Expand documentation of `@require_deps` decorator

- cscs-checks/system/slurm/slurm.py
`RequiredConstraintCheck` is missing the account in the `srun` command line: see [CSCS RT 39626](https://webrt.cscs.ch/Ticket/Display.html?id=39626).
> [test] Add account in executable options of RequiredConstraintCheck

- config/cscs-ci.py
Adding an option to `./test_reframe.py` for setting the account is not so straightforward as for the standard cli. It would require either to do hacks or to modify all the unit tests that use a temporary runtime. For this reason, I believe the solution proposed here is the best.
Fixes #1406.
> [ci] Set the account dynamically in the configuration file for unit tests 

- reframe/core/schedulers/__init__.py
> [bugfix] Copy scheduler options when initializing job instances

- unittests/fixtures.py
- unittests/test_argparser.py
> [bugfix] Fix unit test failure of asynchronous execution policy

- reframe/utility/os_ext.py
- unittests/test_utility.py
I am not doing any special post processing of the values retrieved, since they are well formed strings that you can nicely compare:
```python
if cray_cle_info().release >= '7.0.UP00' and cray_cle_info().patchset < '09':
```
> [feat] Add utility function for retrieving Cray Linux Environment (CLE) information

- cscs-checks/system/slurm/slurm.py
- docs/manpage.rst
- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
* Adapt unittests, docs and the related regression checks.
> [bugfix] Use '&' to combine Slurm constraints

- reframe/utility/sanity.py
> [doc] Document that sanity functions use 're.MULTILINE'

- reframe/core/logging.py
- unittests/test_logging.py
In our cluster, we use syslog to collect reframe tests data. We have found SysLogHandler require int type port instead of str type in codes now. It works fine in our cluster after change.
> [bugfix] Convert Syslog handler port parameter into integer

- docs/manpage.rst
- reframe/frontend/cli.py
- Also rename ``RFM_GRAYLOG_SERVER`` to ``RFM_GRAYLOG_ADDRESS`` for symmetry. ``RFM_GRAYLOG_SERVER`` is now deprecated.
Fixes #1056.
> [feat] Allow Syslog's address to be set from an environment variable

- reframe/frontend/executors/policies.py
Besides `_running_tasks` and `_waiting_tasks`, we can have a more strict check in the async policy main loop. In this way we make sure that the tasks will run in the correct reframe "retry".
I couldn't find how to reproduce the bug, but it should fix #1398 .
> [bugfix] Capture all pending test tasks in the exit loop of the asynchronous execution policy

- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
* Support also passing of multiple conversion functions for
each tag to be extracted.
Fixes #1245
> [feat] Support multiple tags in `extract*` sanity functions

- cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
* Correct also the sanity pattern.
* Use f-strings instead of `%` based string formatting.
> [bugfix] Fix glob pattern to search for both txt and yaml

- bootstrap.sh
- requirements.txt
This solves the following error when installing ReFrame's dependencies with the bootstrap script:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
```
This PR also disallows pip cache in the bootstrap script.
> [bugfix] Use new the 2020 pip dependency resolver in the bootstrap script

- reframe/utility/os_ext.py
- unittests/test_utility.py
* Catch the exception thrown in case git is not installed
* Add a unittest
Fixes #1464
> [bugfix] Fix crash when git is not available

- reframe/frontend/statistics.py
> [bugfix] Remove unnecessary error message from failure report

- reframe/core/runtime.py
- unittests/test_environments.py
> [bugfix] Restore environment correctly in case of module load failures

- reframe/core/config.py
- unittests/test_config.py
> [bugfix] Load configuration even if the username cannot be retrieved

- docs/config_reference.rst
- docs/manpage.rst
- reframe/core/pipeline.py
- reframe/schemas/config.json
- unittests/test_pipeline.py
Will fix https://github.com/eth-cscs/reframe/issues/1196
> [feat] Add configuration parameter for automatically capturing command errors and exit code in job scripts

- reframe/frontend/statistics.py
Fixes https://github.com/eth-cscs/reframe/issues/1502
> [bugfix] Print current environment and partition correctly even if a test fails before the setup

- reframe/core/config.py
- reframe/core/systems.py
- reframe/frontend/cli.py
- unittests/test_config.py
> [bugfix] Do not require a configuration to be resolved always at system level

- reframe/core/systems.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- unittests/test_cli.py
- unittests/test_policies.py
- unittests/test_schedulers.py
Fixes #1511.
This PR also addresses the following:
- Fix `System` JSON representation
- Adjust sleep times in local scheduler unit tests
> [bugfix] Treat correctly forced local jobs and other small fixes

- unittests/test_modules.py
> [bugfix] Fix typo in modules system unit tests

- .travis.yml
> [ci] Remove the unit tests from the coverage report

- cscs-checks/prgenv/src/mpi/hello_world_mpi.cpp
- cscs-checks/prgenv/src/mpi_thread/mpi_init_thread.cpp
The C++ language bindings have been deprecated.
> [test] Remove C++ language bindings from MPI checks

- config/cscs-ci.py
- docs/config_reference.rst
- docs/tutorial_basics.rst
- docs/tutorial_deps.rst
- docs/tutorial_misc_topics.rst
- reframe/core/logging.py
- reframe/core/schedulers/__init__.py
- reframe/core/settings.py
- reframe/frontend/cli.py
- reframe/schemas/config.json
- tutorials/config/settings.py
- unittests/resources/settings.py
- unittests/test_cli.py
This PR renders the `name` configuration parameter of the `file` log handler optional and sets the default location to be in the system's temporary directory. The behaviour of the framework with the current configuration files that set the `name` parameter is not affected.
Documentation and the tutorials are also updated.
This PR allows the parallelization of the unit tests as discussed in #134. 
Fixes #1177.
> [feat] Set the default location for log files to be the system's temporary directory

- cscs-checks/prgenv/cuda/cuda_aware_mpi.py
- cscs-checks/prgenv/cuda/cuda_samples.py
I've also changed the alias `osx` to `osext` for compliance with the rest of the tests.
This has to be merged asap, because the tests are broken in the master.
> [test] Fix osext import in CUDA tests

- reframe/utility/osext.py
- unittests/test_utility.py
This PR also makes `osext.copytree()` errors compliant with the standard `copytree()`.
Fixes #1504.
> [bugfix] Fix `IndexError` crash of `osext.copytree()` when the source directory does not exist 

- ci-scripts/ci-runner.bash
- reframe/core/config.py
- reframe/core/deferrable.py
- reframe/core/exceptions.py
- reframe/core/fields.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- reframe/core/systems.py
- reframe/core/warnings.py
- reframe/frontend/cli.py
- unittests/resources/checks_unlisted/deprecated_test.py
- unittests/test_config.py
- unittests/test_fields.py
- unittests/test_loader.py
- unittests/test_warnings.py
Also:
- Move all the warning related parts into a separate file.
- In order to achieve the coloration of the full message, we had to replace the warning formatting method. Also the message is adjusted.
Fixes #1267.
> [feat] Color deprecation warnings

- config/cscs.py
The `cscs.py` configuration still uses the old syntax for the reservation
request. This updates to use the newer one `-Jreservation=maintenance`
> [ci] Update maintenance mode for CSCS config

- reframe/core/decorators.py
- reframe/core/exceptions.py
- reframe/frontend/cli.py
- reframe/frontend/statistics.py
- reframe/schemas/runreport.json
- reframe/utility/jsonext.py
- unittests/test_policies.py
To achieve this, the way the failure report is generated had to be redesigned:
- The former `failure_report()` and `failure_stats()` are now printing directly through a printer object, thus their output is controlled with the universal verbosity levels of the framework.
- The exception information is kept in detail in the produced JSON report.
- The former `format_exception()` function has been simplified to return only the reason of the failure (no tracebacks).
- The traceback are always stored in the JSON report and are printed either at the INFO or the VERBOSE level depending on the severity of the failure, which can be queried through the `is_severe()` method.
Fixes #491.
> [feat] Control verbosity of check failure info

- reframe/frontend/cli.py
- unittests/test_cli.py
> [bugfix] Add newline at the end of run report

- reframe/core/exceptions.py
This happens because `TaskDependencyError`s are not associated with a stack trace, so this was raising ` ValueError`:
```
./bin/reframe: Traceback (most recent call last):
File "/users/karakasv/Devel/reframe/reframe/frontend/cli.py", line 738, in main
runner.stats.print_failure_report(printer)
File "/users/karakasv/Devel/reframe/reframe/frontend/statistics.py", line 175, in print_failure_report
run_report = self.json()[-1]
File "/users/karakasv/Devel/reframe/reframe/frontend/statistics.py", line 134, in json
entry['fail_reason'] = errors.what(*t.exc_info)
File "/users/karakasv/Devel/reframe/reframe/core/exceptions.py", line 329, in what
frame = user_frame(exc_type, exc_value, tb)
File "/users/karakasv/Devel/reframe/reframe/core/exceptions.py", line 286, in user_frame
raise …
```
> [bugfix] Fix statistics crash when reporting task dependency errors

- unittests/test_schedulers.py
The `assert_process_died()` function was failing for the local scheduler when the unit tests were run inside a container. The reason for that is that the Python process was run with pid=1, thus inheriting the children that were killed in some of the unit tests. Since these children were never waited for, the remained zombies, thus having still a valid PID.
> [bugfix] Fix unit test error due the PID 1 problem when running inside a Docker container

- reframe/core/pipeline.py
- unittests/test_pipeline.py
> [bugfix] Remove duplicate entries in test listing

- config/cscs.py
- cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
- cscs-checks/microbenchmarks/gpu/memory_bandwidth/p2p_bandwidth.py
This PR extends the support of the memory bandwidth tests for all the current partitions in `ault` with NVIDIA cards.
The most relevant change to these tests is that now the `nvidia_sm` parameter is set in a hook due to the different device architectures present in this system.
> [test] Update memory bandwidth checks references

- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
- unittests/test_pipeline.py
* The SingleSource build system now raises an exception when
it fails to guess the programming language of the source file.
* Add unittests.
Fixes #1546
> [bugfix] Fail properly when the source code language cannot be guessed

- .github/workflows/main.yml
- reframe/frontend/cli.py
- reframe/frontend/loader.py
> [ci] Add Github action to check for unused imports

- docs/migration_2_to_3.rst
- reframe/core/pipeline.py
> [feat] Remove deprecated `pre_run`, `post_run`, `prebuild_cmd` and `postbuild_cmd` attributes

- docs/manpage.rst
- reframe/frontend/cli.py
- unittests/test_buildsystems.py
- unittests/test_cli.py
- unittests/test_pipeline.py
This is only the case when neither the `+` nor the `-` prefixes are used. The reason for this enhancement is to allow an easier manipulation of the path through. The unit tests are also adapted.
This blocks #1538, since the unit tests are broken in master on Dom.
> [feat] Allow using colon separated paths with the `--module-path` option

- docs/config_reference.rst
- reframe/core/buildsystems.py
- reframe/core/deferrable.py
- reframe/core/logging.py
- reframe/core/pipeline.py
- reframe/utility/jsonext.py
- unittests/test_logging.py
The implementation of the dynamic log record based on arbitrary test attributes is revised completely. It does not happen anymore in the formatter, because the formatter is not used by the Graylog handler and this was the reason for #1640. All public test attributes as well as some interesting properties are put in the logger's `extra` dict. This will be transferred to the log record by Python's logging mechanism. At this point, we do NOT format anything, except the `check_job_completion_time`, in order to be sent correctly to Graylog. The formatting of the record is an exclusive duty of the formatter object, which formats the final log message through its `formatMessage()` method. We don't format the record attributes directly, but we use a proxy dictionary, which holds the formatted …
> [bugfix] Send test attributes correctly with the Graylog handler

- docs/migration_2_to_3.rst
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_loader.py
> [feat] Drop support of pipeline stage method override

- .github/workflows/main.yml
- ci-scripts/dockerfiles/Lmod77.dockerfile
- reframe/core/modules.py
This PR introduces also a method for the module system backends that they can override in order to process the Python bindings output before executing the Python statements. We use this mechanism to fix the emitted Python commands from Lmod versions prior to 8.2, which are broken.
Fixes #1648.
> [bugfix] Fix module backend implementation for Lmod versions < 8.2

- cscs-checks/apps/gromacs/gromacs_check.py
GROMACS small and large check on Eiger: reference values are tentative as there might be room for improvement.
> [test] Adapt GROMACS test to Eiger

- reframe/core/logging.py
- unittests/test_cli.py
> [bugfix] Properly expand environment variables for the filelog log handler

- cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
GpuBurnTest
- dom:gpu
- PrgEnv-gnu
* num_tasks: 22
* perf: 4091.0 Gflop/s
* smallest_flops: 4091.0 GF/s (nid00008)
Goal is to report nidname when the test fails to meet perf. reference 
`'perf': (4115, -0.10, None, 'Gflop/s')`
but I am not sure how to do that... Feel free to push 
For now, replacing `perf:` with the last line gives some info.
> [test] Extend GPU burn test to report GPU node with smallest flops

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
> [bugfix] Pass the job id when raising job-related errors

- reframe/core/deferrable.py
- unittests/test_logging.py
- unittests/test_utility.py
We instead cache the last evaluated value and returned that one. If the deferred expression has never been evaluated, then `None` is returned.
This addresses #1646.
> [bugfix] Do not evaluate deferred expressions when dumping in JSON

- reframe/utility/sanity.py
> [bugfix] Fix documentation of sanity functions accepting a filename

- cscs-checks/apps/cp2k/cp2k_check.py
I have re-defined `self.executable = '--cpu-bind=cores cp2k.psmp'` as suggested by @jjotero, since I could not find a simpler way to add the `srun` flag `--cpu-bind=cores` to the command line. The apparently weird setting of `num_cpus_per_task=16` and `OMP_NUM_THREADS=8` yields a better performance with respect to `num_cpus_per_task=8` and `'OMP_NUM_THREADS': str(self.num_cpus_per_task)` (see the related issue https://jira.cscs.ch/projects/SD/queues/custom/48/SD-51051).
In order to improve a bit more the performance of the test, I would also like to add the following Slurm directive:
```
#SBATCH --distribution=block:block
```
I found in the documentation the `job_opts` parameter, but the warning says that in version 3.0 you may not override this method directly unless you are in special …
> [test] Adapt CP2K checks for Eiger

- reframe/frontend/executors/policies.py
When reframe catches the following errors (KeyboardInterrupt, ReframeForceExitError, AssertionError) it unnecessarily marks as failures tasks from retired tasks. This leads to confusing output, where tasks are repeated, T1 and T5 in this example:
```
[----------] waiting for spawned checks to finish
[       OK ] ( 1/10) T0 on generic:default using builtin [compile: 0.012s run: 0.183s total: 0.223s]
[       OK ] ( 2/10) T4 on generic:default using builtin [compile: 0.012s run: 0.179s total: 0.218s]
[       OK ] ( 3/10) T5 on generic:default using builtin [compile: 0.012s run: 0.208s total: 0.247s]
[       OK ] ( 4/10) T1 on generic:default using builtin [compile: 0.012s run: 0.208s total: 0.248s]
[     FAIL ] ( 5/10) T8 on generic:default using builtin [compile: n/a run: n/a total: 0.003s] …
```
> [bugfix] Fix numbering of failed tasks when reframe execution is aborted

- cscs-checks/apps/quantumespresso/quantumespresso_check.py
The fix applies to the modulefile `QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda`: the total energy of the small test case changed with the new Cray Programming Environment 20.10 and the new cudatoolkit 11.0.
> [test] Fix energy reference value and difference of QE small

- cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Removed no longer needed workaround for an issue with OMP.
> [test] Remove HPCG test workaround for unsupported OpenMP pragma

- cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
- cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
- cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
- cscs-checks/microbenchmarks/gpu/shmem/shmem.py
Extended hook for `dom:gpu` so that the tests under `microbenchmarks/gpu` load the `cdt-cuda` module.
> [test] Load cdt-cuda in dom for GPU checks

- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
> [feat] Add sanity function equivalents of some of `os.path` functions

- cscs-checks/apps/jupyter/src/tf-hvd-sgd-ipc-tf2.py
`import ipcmagic` registers the magic command `%ipcluster`. The module is not used on the rest the code but without it script crashes.
> [test] Put back import that registers magic command

- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
I came up to this when preparing the tutorials. Currently you can't write `sn.assert_found('r'something', sn.print(self.stdout))`, because `sn.print()` would return you a tuple, which you would need to unpack. But if you try to unpack, you trigger the evaluation of the deferred expression, which you don't want. So the sanity version of the `print` is restricted to getting a single object only.
> [bugfix] Fix sanity function `print` to accept a single object only

- reframe/core/launchers/mpi.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
- unittests/test_launchers.py
> [bugfix] Ensure that job options passed from the command-line are always the last in the generated job script

- reframe/frontend/dependencies.py
When `A -> B -> C -> D`, if `D` is missing, we should skip all of `A`, `B` and `C`, i.e., we need to recursively skip all the test cases that depend on the missing one. This currently leads to a crash. Since this urgent, because it breaks the tutorials in #1692 I suggest merging this asap for 3.4. We will add proper unit tests for it in 3.5.
> [bugfix] Skip test cases recursively in case of dangling dependencies

- docs/regression_test_api.rst
- reframe/core/parameters.py
- unittests/test_parameters.py
On its current state, the parameters are specified in a class as
```python
class Test(rfm.RegressionTest):
parameter('P0', 1, 2, 3 , 4, 5)
```
This PR will change the parameter definition to
```python
class Test(rfm.RegressionTest):
parameter('P0', [1, 2, 3 , 4, 5])
```
> [bugfix] Fix parameter value specification in the `parameter()` directive

- cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
The HPCG test requires the number of nodes to be factored into `N=nx*ny*nx`, where `max(nx, ny, nz)/min(nx, ny, nz) >= 8`.
Thus, since this case is a flexible test, some guidance is needed to have the 'raw' slurm node guess educated into something the HPCG tests can work with (for example, if the number of available nodes in the system is a prime number, the above factorisation is impossible).
This PR solves this issue by adding a hook into the `pre_run` stage of these tests. The hook simply does the node guess in advance and makes sure that the number of nodes is a sensible one. With this 'constrained' number of nodes we set `self.num_tasks` in the test, which avoids reframe to query for the available number of nodes again at a later stage.
> [test] Constrain flexible node allocation on the HPCG check

- docs/config_reference.rst
- reframe/core/schedulers/slurm.py
- reframe/schemas/config.json
Second, much simpler implementation of #1672. In this PR the submission blocks until slurm stops giving the `QOSMaxSubmitJobPerUserLimit` error. This could cause significant slowdown of the jobs.
Closes #1595.
> [feat] Support multiple job submissions when slurm's job submit limit is reached

- cscs-checks/libraries/gridtools/gridtools_tests.py
This is a temporary fix for the GridTools build issue on Dom reported here: https://jira.cscs.ch/browse/UES-1382
> [dom] Temporary fix for GridTools build on dom

- docs/config_reference.rst
- reframe/utility/sanity.py
I adapted the `.. versionadded::` annotation to the correct version.
> [bugfix] Fix "New in version" annotation for some sanity functions

- docs/tutorial_deps.rst
- reframe/frontend/dependencies.py
- unittests/test_dependencies.py
This is a follow up of #1714 and fixes #1717.
The implementation in #1714 is buggy. This one is correct.
> [bugfix] Fix skipping of test cases in case of unresolved dependencies

- cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
The perf value may have two space in front of it if <1000.
There is never a space between the GPU number and the (OK) value.
> [test] Fix minor bug in sanity pattern for GPU burn test

- unittests/test_ci.py
We are now fetching the JSON schema from the schema store and validate the generated YAML against it.
Fixes #1763.
> [bugfix] Fix validation of the generated Gitlab pipeline files

- README.md
- docs/config_reference.rst
- docs/configure.rst
- docs/index.rst
- docs/started.rst
- docs/tutorial_advanced.rst
- docs/tutorial_basics.rst
- docs/tutorial_deps.rst
- unittests/resources/checks/hellocheck_make.py
- unittests/test_buildsystems.py
Fixes #1723.
Fixes #1724.
Fixes #1731.
Fixes #1732.
I also reorganised substantially the "Getting Started" rtfd page and the main README. The first has more user-oriented information, whereas the second one has more developer-oriented.
> [bugfix] Various documentation fixes

- reframe/__init__.py
- reframe/core/decorators.py
- reframe/core/warnings.py
- reframe/frontend/runreport.py
- reframe/utility/osext.py
- reframe/utility/versioning.py
- requirements.txt
- setup.py
- unittests/test_versioning.py
- unittests/test_warnings.py
This PR also adds the following:
- Expand deprecation message function to issue deprecation warnings in future releases.
- Old style of version specification is set to deprecate in 3.5.0
TODO:
~~NOTE: The CI will fail due to an irrelevant reason. A separate PR will fix that (it's Gitlab CI lint failure)~~
> [feat] Comply with the semantic versioning specification

- reframe/frontend/executors/__init__.py
ReFrame will now also print `FAILURE` as the final result in cases where not all test cases have been run. This covers cases such as #1740, where errors occur during polling.
Fixes #1740.
> [bugfix] Print a FAILURE result if not all test cases have completed

- docs/regression_test_api.rst
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_parameters.py
- unittests/test_variables.py
This PR implements the attribute access to variables and parameters directly from the class body. Prior to this PR, an attempt to access either variables or parameters from the class body resulted in a `NameError` since none of these built-ins are stored in the public namespace from the class. This PR not only implements the access to these items, but also provides a more robust error handling in case of erroneous user input:
- Accessing a required (undefined) variable in the class body will raise a `ValueError`:
```python
class Foo(rfm.RegressionMixin):
v = variable(str)
x = f'{v}' # This will raise an error because `v` has no value
```
- Accessing a defined variable will return its default value:
```python
class Foo(rfm.RegressionMixin):
v = variable(int, value=4)
x = v + 1 # this sets …
```
> [feat] Support parameter and variable access directly from the class body

- reframe/core/variables.py
- unittests/test_variables.py
This PR fixes the upstream propagation of changes to variables done by the child classes. Reproducer:
```python
class Foo(rfm.RegressionMixin):
v = variable(int, value=3)
class Bar(Foo):
v = 4
Foo().v # Erroneously printed 4 instead of 3
Bar().v # Prints 4
```
A unit tests has been extended to catch this.
> [bugfix] Deepcopy inherited variables from the parent classes

- reframe/core/fields.py
- reframe/core/warnings.py
- unittests/resources/checks_unlisted/good.py
- unittests/test_fields.py
- unittests/test_policies.py
- unittests/test_warnings.py
Also:
- Make unit tests for deprecation warnings more robust
-  Ignore prereleases when filtering deprecation warnings. For example, if we are on 3.5.0-dev.0 and a feature is set to deprecate in 3.5.0, then we issue the deprecation warning also for the prerelease.
- Fix deprecation warnings introduced by #1761.
This is a follow up of #1761.
> [feat] Allow deprecation of fields in a future version and issue deprecation warnings also in prereleases

- config/cscs.py
- cscs-checks/apps/vasp/vasp_check.py
I propose a configuration of ReFrame on Pilatus with the Hierarchical module naming scheme, introducing the environments `cpeAMD`, `cpeCray`, `cpeGNU` and `cpeIntel` that correspond to the toolchain modules to be loaded before the apps. 
I also provide a modified check for VASP that works on Pilatus: we might use this configuration temporarily.
> [test] Add configuration for Pilatus and VASP check

- cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py
- cscs-checks/microbenchmarks/cpu/dgemm/src/dgemm.c
The initialisation of the arrays is now done in parallel. The appropriate OMP env variables have been added to the test.
> [test] Fix DGEMM performance in Eiger

- cscs-checks/apps/cp2k/cp2k_check.py
- cscs-checks/apps/gromacs/gromacs_check.py
- cscs-checks/apps/lammps/lammps_check.py
- cscs-checks/apps/namd/namd_check.py
- cscs-checks/apps/quantumespresso/quantumespresso_check.py
Existing checks of supported applications valid on Eiger can be easily adapted to Pilatus with the following lines (e.g.: `NAMD`):
```
if self.current_system.name == 'pilatus':
self.valid_prog_environs = ['cpeIntel']
else:
self.valid_prog_environs = ['builtin']
```
> [test] Update checks of supported applications on Pilatus

- cscs-checks/prgenv/affinity_check.py
- reframe/core/pipeline.py
The NUMA tests have been replaced by socket tests. A new NUMA node filling test has been added.
> [test] Adjust affinity tests to new Slurm config on Eiger

- reframe/core/pipeline.py
- reframe/utility/__init__.py
> [doc] Various documentation fixes

- reframe/core/pipeline.py
This makes the default behaviour of these two variables with all the others.
> [feat] Allow setting the test description and executable name directly in the class body

- cscs-checks/system/nvidia/nvidia_smi_check.py
This introduces the Nvidia SMI tests that check whether Accounting, Compute and ECC modes are set to the correct values.
> [test] Add nvidia-smi check

- config/cscs-ci.py
- config/cscs.py
- docs/config_reference.rst
- reframe/core/pipeline.py
- reframe/schemas/config.json
> [feat] Add a `time_limit` partition configuration parameter and a `build_time_limit` variable for regression tests

- reframe/core/pipeline.py
Fixed a bug in the pipeline's `_rfm_init`, where `sourcesdir` was reset to `None` if the directory didn't exist. Consequently, when `sourcesdir` is a git repo and is set in the class body, `_rfm_init` would just reset it to `None`.
> [bugfix] Do not reset `sourcesdir` to `None` if it is set to a URL

- reframe/core/pipeline.py
- reframe/frontend/loader.py
- unittests/resources/checks/bad/invalid_check.py
- unittests/resources/checks/emptycheck.py
- unittests/resources/checks/frontend_checks.py
- unittests/resources/checks_unlisted/good.py
- unittests/resources/checks_unlisted/kbd_interrupt.py
It is a common mistake to forget to define the `sanity_patterns`. Now tests not defining them, will be skipped and a warning message will be issued, similarly to `valid_systems` and `valid_prog_environs`.
> [feat] Skip test if `sanity_patterns` is undefined

- reframe/core/decorators.py
- reframe/core/exceptions.py
- reframe/core/pipeline.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- reframe/frontend/statistics.py
- unittests/resources/checks/hellocheck.py
- unittests/test_cli.py
- unittests/test_policies.py
This PR adds two `RegressionTest` methods that allow users to skip tests dynamically:
- `skip(msg=None)`: Skip test uncondintionally.
- `skip_if(cond, msg=None)`: Skip test if `cond` is true.
A test can be skipped anywhere during its lifetime, except during the `cleanup` stage.
NOTE: If a test is skipped after its stage directory is created, it will not be cleaned up.
Fixes #1474.
> [feat] Add test API methods for skipping tests

- reframe/core/meta.py
- reframe/core/parameters.py
- unittests/test_variables.py
When declaring a variable with the `variable` built-in, the corresponding `__set_name__` hook was only called if needed by the `__getitem__` method of the metaclass. This is because the variables are temporarily hidden away in their own namespace, and the `__set_name__` hooks from these variables don't get called by the base metaclass `type`.
Hence, it is a bit counterintuitive (if not just plainly wrong) that things get set when calling the `__getitem__` method; so now the `__set_name__` hook is called unconditionally for all variables in the `__setitem__` method of the metaclass.
> [bugfix] Fix the call order on the `__set_name__` hook for built-in variables

- reframe/utility/osext.py
- unittests/test_utility.py
> [bugfix] Set stdin to null when launching processes from ReFrame, so that processes do no think they are on a tty

- reframe/core/pipeline.py
- reframe/frontend/loader.py
- unittests/resources/checks/bad/invalid_check.py
- unittests/resources/checks/emptycheck.py
- unittests/resources/checks/frontend_checks.py
- unittests/resources/checks_unlisted/good.py
- unittests/resources/checks_unlisted/kbd_interrupt.py
- unittests/test_pipeline.py
This PR fixes a bug introduced by #1876, which forced the `sanity_patters` to be set directly in the class body of the test. 
The syntax for checking if required variables are set has been adapted to the newer built-in variable syntax.
Closes #1885.
> [bugfix] Do not skip test if `sanity_patterns` is not set

- bootstrap.sh
Jumping from Python 3.6.10 to 3.6.12 on Dom has caused the bootstrap script to fail.
> [bugfix] Fix bootstrap script for `pip`-less Python installations

- bootstrap.sh
> [bugfix] Color `bootstrap.sh` only if stdout is a terminal

- reframe/core/pipeline.py
- unittests/test_pipeline.py
I've also changed the automatic assignment of `sourcesdir` to `None` so as to avoid setting it so, in cases that the user has explicitly passed a directory that does not exist. For this one, I'm taking advantage of the default value that is being set by the variables.
Fixes #1869.
> [bugfix] Fix crash when `sourcesdir` is set to `None` in class body

- reframe/frontend/executors/__init__.py
> [bugfix] Fix crash when `OSError` occurs during dumping of test cases

- reframe/core/logging.py
- reframe/core/modules.py
- unittests/test_logging.py
In order to avoid multiple warnings, this PR introduces also a caching mechanism for warnings. Warnings that are intended to be cached, must be issued with `cache=True`. Currently, only warnings from `nomod` are issued in such a way.
Fixes #1892.
> [feat] Issue a warning if a module operation is attempted on the `nomod` modules system

- config/cscs.py
> [ci] Remove module collections from Alps config

- reframe/core/decorators.py
- unittests/test_parameters.py
Tests should use the `parameter()` built-in instead.
Fixes #1833.
I don't know if we should change also the `@simple_test` name to something else. And if we do, do we deprecate it from now? Or should we better deprecate `@simple_test` in 4.0 and remove it in 5.x?
> [feat] Drop the `@parameterized_test` decorator

- bootstrap.sh
> [bugfix] Properly check exit status of `ensurepip` in `bootstrap.sh`

- reframe/frontend/cli.py
- reframe/frontend/loader.py
> [bugfix] Warn when a check search path does not exist

- docs/manpage.rst
- reframe/frontend/runreport.py
* Each retry(run) is passed as an individual testsuite to the junit report.
Fixes #1963
> [feat] Support test retries in the JUnit report

- reframe/core/modules.py
- unittests/modules/testmod_bar
- Test for `ERROR` word when checking success of module command
Fixes #1967
> [bugfix] Fix error checking of module commands in the class Tmod backends

- reframe/core/containers.py
- reframe/core/pipeline.py
- reframe/core/systems.py
- unittests/test_containers.py
Fixes #1914.
Fixes #1915.
Fixes #1916.
Fixes #1919.
> [feat] Remove deprecated features from 4.x

- reframe/core/meta.py
- reframe/core/variables.py
- unittests/test_parameters.py
- unittests/test_variables.py
This PR fixes a bug that was causing variables and parameters set as class attributes to be silently overridden. Bug reproducer:
```python
class Base(rfm.RegressionTest):
...
p = parameter([1])
v = variable(int, value=1)
Base.p = [2] # This PR will disallow updating parameters like this.
Base.v = 2
@rfm.simple_test
class Derived(Base):
def __init__(self):
print(self.p) # Prints 1
print(self.v) # Prints 1. With this PR this prints 2.
```
This PR disables setting/updating parameters when accessed as class attributes. This is because such parameter update would break the internal iterators on the parameter space. If this feature is required, explicit `insert_parameter` or `update_parameter` class methods could be added.
This might be needed by #563
> [bugfix] Fix variable and parameter access as class attributes

- reframe/core/buildsystems.py
The condition `self.environment is _Undefined` is always `False`, so the error
is actually never raised.
Without this change, I get a much more obscure error message:
```
==============================================================================
SUMMARY OF FAILURES
------------------------------------------------------------------------------
FAILURE INFO for Test 
* Test Description: Test
* System partition: catalina:default
* Environment: gnu
* Stage directory: /home/mose/repo/reframe/stage/catalina/default/gnu/Test
* Node list: 
* Job type: local (id=None)
* Dependencies (conceptual): []
* Dependencies (actual): []
* Maintainers: []
* Failing phase: compile_wait
* Rerun with '-n Test -p gnu --system catalina:default -r'
* Reason: build error: stdout: 'rfm_Test_build.out', stderr: …
```
> [bugfix] Fix deep-copy of `_Undefined` constant

- reframe/core/meta.py
- reframe/core/variables.py
- unittests/test_meta.py
- unittests/test_variables.py
See linked issue for details.
Closes #2011.
> [bugfix] Restrict use of `required` keyword

- cscs-checks/prgenv/cuda/cuda_aware_mpi.py
The `CUDA_HOME` env var was missing and has to be added manually for the `PrgEnv-nvidia`
> [test] Bugfix `cuda_aware_mpi_check`

- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_loader.py
- unittests/test_meta.py
One now can do
```python
class MyTest(rfm.RegressionTest):
@final
def foo(self):
...
```
instead of having to use the `@rfm.final` syntax.
- Renamed `_rfm_special_test` to `_rfm_override_final`. This flag is only used in the metaclass to allow the override of final methods, so this name is more descriptive. Also, the "special" naming of it should just be down to the `RegressionTest` class.
- The unit test of this functionality is now in `unit tests/tests_meta.py` instead of the file with the loader tests.
- The `run` stage of the `RunOnlyRegressionTest` was calling `super().run.__wrapped__(self)`. I've replaced this line for `super.run()` since now the `final` decorator does not create a `functors.wrap` wrapper.
Closes #2001
> [feat] Expose `@final` decorator in the class body

- reframe/utility/jsonext.py
- unittests/test_utility.py
When defining a custom variable of type `dict`, the logger raised a `TypeError` from the `json.dumps` call if the dict had tuples as keys. This error is now caught and the dict keys are converted to strings using the `toalphanum` utility.
Note that fixing this in the `default` hook would not work, because dictionaries are recognised types by json. The alternative fix through the encoder would be a total overkill just for this minor issue (see https://stackoverflow.com/questions/16405969/how-to-change-json-encoding-behaviour-for-serializable-python-object for a similar issue).
Closes #2022
> [bugfix] Fix `TypeError` in logger when using tuples as dict keys

- ci-scripts/ci-runner.bash
For a couple of reasons:
1. `pytest-parallel` is not yet stable (0.x versions)
2. Running multiple instances of ReFrame at the same time is not supported and can have unpredictable side effects.
> [ci] Serialize unit tests everywhere

- unittests/resources/checks_unlisted/deps_complex.py
- unittests/test_deferrable.py
- unittests/test_logging.py
- unittests/test_pipeline.py
- unittests/test_sanity_functions.py
> [ci] Remove `sn.sanity_function` references from unit tests

- reframe/frontend/autodetect.py
- unittests/test_autodetect.py
- unittests/test_cli.py
> [bugfix] Always use `$HOME` for storing processor auto-detection results

- unittests/test_deferrable.py
When testing for deprecation warnings in unit tests, we should force them to be raised, because we might end up with CI failures on master when doing patch-level version bumps.
> [ci] Fix sanity function deprecation unit test

- reframe/frontend/autodetect.py
- reframe/utility/osext.py
> [bugfix] Remove unnecessary file locks

- reframe/core/modules.py
- unittests/test_modules.py
> [bugfix] Do not emit `module unuse <path>` after loading modules with Lmod from a specific path

- reframe/frontend/runreport.py
- unittests/test_policies.py
* Correctly treat `None` value for `time_total` of a `TestCase` when
converting to `Decimal` during the creation of the Junit report.
* Test the above in the testing of policies.
Fixes #2057
> [bugfix] Handle `None` in `Decimal` conversion of junit report

- unittests/test_schedulers.py
> [bugfix] Make `test_cancel_(with_grace|term_ignore)` unit tests more robust

- docs/tutorial_advanced.rst
- reframe/core/pipeline.py
- unittests/test_pipeline.py
- unittests/test_policies.py
`RunOnlyRegressionTest` classes must be able to set the `executable` variable as `required`. However, this variable was set a default value during class instantiation. This assignment has now been moved into the `compile` stage.
closes #2106
> [bugfix] Fix default `executable` assignment

- docs/tutorial_build_automation.rst
- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
> [feat] Automatically create a Spack environment when not set

- README.md
> [doc] Use an absolute URL for the ReFrame logo in README.md

- reframe/frontend/autodetect.py
- unittests/test_autodetect.py
Whenever the processor and device files exist but cannot be loaded (empty file, invalid syntax etc), Reframe just stops and throws a throwback. With this PR we ignore the `JSONDecodeError` and try to regenerate the file.
Closes #2110.
> [bugfix] Do not crash if processor and/or device topology files are not properly formatted JSON files

- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_meta.py
> [bugfix] Do not bypass metaclass logic in the `bind` directive

- reframe/core/schedulers/slurm.py
- reframe/frontend/autodetect.py
- reframe/utility/__init__.py
- unittests/test_utility.py
In this PR we include the partition's and system's modules in the topology autodetecting script.
- For local partitions we temporarily change the environment of Reframe to include both system's and partition's modules and variables.
- For remote partitions we temporarily change the environment to include system's modules and variables and add the partition's environment in the autodetecting script.
For this PR we also added support for addition in the `SequenceView` and `MappingView` classes.
Closes #2115.
> [bugfix] Use partition's and system's environment when autodetecting the topology

- reframe/frontend/ci.py
This PR fixes the pattern matching for the `-n` option generated in the `--ci-generate` feature.
Currently, in the CI generate the `-n` option is emitted as
```
reframe ...  -n MyTest_1 -r
```
And this PR changes it to
```
reframe ...  -n ^MyTest_1$ -r
```
This should fix the issue that `-n MyTest_1` pattern matches `MyTest_1.*`, e.g, it matches the tests `MyTest_10` and `MyTest_1_OtherOptions`. 
Closes #2165
> [bugfix] Fix pattern matching for test name in `--ci-generate` output

- cscs-checks/apps/jupyter/check_ipcmagic.py
See also https://jira.cscs.ch/browse/SD-53111 / https://jira.cscs.ch/browse/UES-1737
> [test] Fix typo in ipcmagic module version

- reframe/core/systems.py
- reframe/frontend/autodetect.py
- reframe/utility/jsonext.py
- unittests/test_autodetect.py
- unittests/test_utility.py
When we detect automatically the topology we used to set directly only the `_info` attribute of the processor of the partition. As a result the other attributes of the `ProcessorType` were not set and we would get for example `self.current_partition.processor.num_cpus` as `None` while `self.current_partition.processor.info` is a non empty dictionary. The other attributes were only set in the `_init_`: https://github.com/eth-cscs/reframe/blob/34ee3d0bc91f7c9f5e56db1c6b46a49e8e5ee623/reframe/core/systems.py#L38
Same for the devices, we should set `self.current_partition._devices` to a list of `DeviceType` objects and not dictionaries.
> [bugfix] Fix incomplete processor info object when processor topology is auto-detected

- reframe/frontend/autodetect.py
- unittests/test_autodetect.py
If you try to auto-detect a remote partition, ReFrame will crash as follows:
```
Traceback (most recent call last):
File "./bin/reframe", line 22, in <module>
cli.main()
File "/users/karakasv/Devel/reframe/reframe/frontend/cli.py", line 617, in main
autodetect.detect_topology()
File "/users/karakasv/Devel/reframe/reframe/frontend/autodetect.py", line 229, in detect_topology
with runtime.temp_environment(modules=temp_modules,
NameError: name 'temp_modules' is not defined
```
This PR fixes this and introduces a unit test that tests that.
> [bugfix] Fix remote auto-detection crash

- reframe/frontend/argparse.py
- reframe/frontend/cli.py
- unittests/test_argparser.py
- unittests/test_cli.py
The fix is easy, but there is a subtlety. In this case, we do not use the default from the configuration, which is `''`. This is used when the `--timestamp` option is not passed at all.
Fixes #2169.
> [bugfix] Fix timestamp prefix when `--timestamp` option is passed no arguments

- reframe/frontend/executors/policies.py
On my laptop quite often I get the error
```
[==========] Finished on Tue Sep 21 22:13:38 2021
Run report saved in '/Users/sarafael/.reframe/reports/run-report.json'
./bin/reframe: run session stopped: zero division error: float division by zero
./bin/reframe: Traceback (most recent call last):
File "/Users/sarafael/git_/reframe/reframe/frontend/cli.py", line 1062, in main
runner.runall(testcases, restored_cases)
File "/Users/sarafael/git_/reframe/reframe/frontend/executors/__init__.py", line 431, in runall
self._runall(testcases)
File "/Users/sarafael/git_/reframe/reframe/frontend/executors/__init__.py", line 504, in _runall
self._policy.exit()
File "/Users/sarafael/git_/reframe/reframe/frontend/executors/policies.py", line 545, in exit
self._pollctl.running_tasks(num_running).snooze() …
```
> [bugfix] Fix division by zero when calculating the poll rate

- reframe/core/exceptions.py
- reframe/utility/__init__.py
> [bugfix] Fix `--restore-session` failure when ReFrame root directory is not in `sys.path[0]`

- reframe/utility/cpuinfo.py
Closes #2202 .
In the sysctl output from @rsarm's laptop I could not find the information for the cache associativity. So in order to fix the bug in the unittest I made the `sysctl` command more generic (to avoid the `SpawnedProcessError` exception).
We don't give a warning for every item of the processor information that we cannot detect because it would unnecessarily complicate the `--detect-host-topology` option, since it's supposed to print only the json object.
> [bugfix] Fix error when cache associativity information is not available by `sysctl`

- reframe/core/decorators.py
> [doc] Indicate in the documentation that the `@required_version` decorator is deprecated

- README.md
- docs/index.rst
- setup.cfg
I updated a bit the README to make it more precise regarding the new super powerful capabilities of the framework 😂
> [doc] Update README

- reframe/core/pipeline.py
- unittests/test_pipeline.py
This is quite useful with the topology autodetection, since it should be called the the first time that the topology is requested in a test. Otherwise, users would have to write a post-setup hook doing the same thing. I am not adding for the moment an equivalent function for the device autodetection, because I would like to first see the usage scenarios in practice.
> [feat] Add a utility function to skip tests that have no topology information

- config/cscs-ci.py
We should not need that in the `config/cscs-ci.py` config file.
> [ci] Remove remote autodetect from CI

- hpctestlib/microbenchmarks/gpu/memory_bandwidth/__init__.py
The string tested on is multiline, so must not match stuff with *
> [bugfix] Fix incorrect regex for `gpu_bandwidth_check` perf results

- docs/regression_test_api.rst
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_pipeline.py
As indicated in #2268 the order of execution of inherited hooks was not documented and it was also wrong. This PR solves this issue by imposing a reverse MRO execution order, so that the hooks of the most specialized class are executed last. In the part, hooks were executed starting from the derived classes going up to the bases, but without following strict MRO order.
Fixes #2268.
> [feat] Define the execution order of hooks and implement it properly

- reframe/utility/osext.py
> [feat] Support passing arbitrary options to `git clone` in the `git_clone()` utility function

- reframe/core/pipeline.py
> [doc] Improve documentation of `(pre|post)run_cmds`

- reframe/core/hooks.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_pipeline.py
This was practically introduced because we blindly reversed the order of hooks in `RegressionTest.pipeline_hooks()`. Now the reverse MRO order is ensured as we build the global hook registry of the class. Since the local registries of the parent classes are used to update this class' registry, the order of their hooks as they are inserted is preserved.
Fixes #2284.
> [bugfix] Fix hook execution order for hooks in the same class

- cscs-checks/prgenv/helloworld.py
We need this PR before merging #2194, since it brakes all the old helloworld tests. This is anyway a more reliable way to get the compilation time since it emits some commands in the build script and it doesn't include ReFrame's overhead in the compilation phase.
> [test] Update method to get compilation time in `HelloWorldTest`s

- cscs-checks/apps/tensorflow/tf2_horovod_check.py
I'm renaming `'throughput_iteration'` to `'throughput_per_gpu'`. I think it's a clearer name.
> [test] Skip the TensorFlow checks if the processor information is not found

- hpctestlib/sciapps/gromacs/benchmarks.py
The `executable_opts` passed by the tests are overwritten by the library-defined ones. e.g.
For the CSCS checks, instead of generating these command-line options for GROMACs
```
gmx_mpi mdrun -dlb yes -ntomp 1 -npme -1 -nb cpu -s benchmark.tpr   # correct set
```
one gets
```
gmx_mpi mdrun -nb cpu -s benchmark.tpr  # wrong set
```
This PR fixes this issue.
> [testlib] Append to `executable_opts` in Gromacs library test

- reframe/core/schedulers/oar.py
Due to a bug in OAR scheduler we had to give full path to `stdout` and `stderr` files and change working directory to `stagedir` in preamble commands. This issue has been fixed at upstream OAR and so we remove these unnecessary full paths in preamble.
> [feat] Improve OAR preamble commands

- cscs-checks/apps/lammps/lammps_check.py
I provide an updated version of the LAMMPS check, addressing the warnings and adding `cray-python` in the modules loaded: without that dependency, I get a failure with ReFrame on Dom (see [PROGENV-20](https://jira.cscs.ch/browse/PROGENV-20)), while manually loading the module works instead.
> [test] Modernize syntax of LAMMPS checks

- cscs-checks/libraries/hpx/hpx_hello_world.py
- cscs-checks/libraries/hpx/hpx_stencil.py
HPX is [no longer supported in production as of Cray PE 21.09](https://github.com/eth-cscs/production/blob/master/jenkins-builds/7.0.UP03-21.09-dom-gpu), therefore [the corresponding checks fail on Dom](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-dom-production-daily/detail/reframe-dom-production-daily/1447/pipeline).
> [test] Remove production tag from HPX checks

- cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
I propose to increase the upper threshold for `alloc_speed` on Dom (see https://jira.cscs.ch/browse/PROGENV-20).
> [test] Increase upper threshold for `AllocSpeedTest` on Dom

- cscs-checks/apps/jupyter/check_ipcmagic.py
I had to add the module `JuliaExtensions` (or `Julia`) explicitly, although it is a dependency of `jupyterlab`, otherwise I was getting the error message `Tcl command execution failed` when running the command `reframe -n cscs_ipcmagic_check -t prod -r` on Dom (module `jupyterlab` built in my sandbox for the time being).
> [test] Update CSCS ipcmagic test (JupyterLab)

- reframe/core/runtime.py
- reframe/frontend/cli.py
- reframe/schemas/config.json
- unittests/test_cli.py
> [bugfix] Fix `--show-config` for `null` config options

- reframe/core/schedulers/slurm.py
Fixes #2411.
@casparvl Can you check if this works for you?
> [bugfix] Fix job cancellation when job is pending due to `ReqNodeNotAvail`

- docs/config_reference.rst
> [doc] Enhance documentation of environment variables set in the system configuration

- docs/listings/alltests_daint.txt
- docs/listings/deps_complex_run.txt
- docs/listings/deps_rerun_t6.txt
- docs/listings/deps_run_t6.txt
- docs/listings/hello1.txt
- docs/listings/hello2.txt
- docs/listings/hello2_catalina.txt
- docs/listings/hello2_print_stdout.txt
- docs/listings/hellomp1.txt
- docs/listings/hellomp2.txt
- docs/listings/osu_bench_deps.txt
- docs/listings/osu_bench_fixtures_run.txt
- docs/listings/stream1.txt
- docs/listings/stream4_daint.txt
- reframe/frontend/executors/policies.py
It might be better to remove the runtime timings from the default output, after the conversation in #2415 . 
The documentation mentions that these timings correspond only to the ReFrame stages, but it can be misleading for new users that want to use them for performance monitoring.
Normal output:
```
[----------] start processing checks
[ RUN      ] T0 @generic:default+builtin
[       OK ] ( 1/10) T0 @generic:default+builtin
[ RUN      ] T4 @generic:default+builtin
[       OK ] ( 2/10) T4 @generic:default+builtin
```
Verbose output:
```
[----------] start processing checks
[ RUN      ] T0 @generic:default+builtin
[       OK ] ( 1/10) T0 @generic:default+builtin
==> setup: 0.019s compile: 0.035s run: 0.476s sanity: 0.000s performance: 0.000s total: 0.568s
[ RUN      ] T4 …
```
> [feat] Remove runtime timings from the default output

- cscs-checks/apps/vasp/vasp_check.py
Please merge it before Piz Daint is opened after the maintenance, to avoid VASP GPU check failure (see #2423 ).
> [test] Update VASP GPU check on Piz Daint

- docs/tutorial_build_automation.rst
- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
I have two-fold motivations for this:
1. I'm trying to use reframe with spack build system on a system where activating shell support seems to screw something up
2. not enabling shell support lets us skip the line https://github.com/eth-cscs/reframe/blob/f996fabf25a35f3bb2a5b7090dd0ea4bf327bace/reframe/core/buildsystems.py#L872 which is very useful when using https://github.com/eth-cscs/spack-batteries-included/ with the single squashfs file (there is no material `$(spack location --spack-root)/share/spack/setup-env.sh` file on disk, so this line would fail).  Also, that line caused problems in the past (see #2097, now solved), and not activating the shell support just makes things more transparent.
As an added bonus, this PR has a negative net diff :slightly_smiling_face:
> [bugfix] Do not set up Spack shell support

- reframe/core/config.py
- reframe/core/runtime.py
- reframe/core/systems.py
- reframe/frontend/executors/__init__.py
- unittests/resources/settings.py
- unittests/test_config.py
- unittests/test_policies.py
This PR fixes the problem of not properly setting up the partition configuration for tests run with the asynchronous execution policy. More specifically, it provides the following:
- Every time a pipeline function is called by the execution policies, the correct subconfig is selected for the current partition.
- A caching mechanism is implemented in `_SiteConfig.select_subconfig()` so as to avoid redundant computations of the subconfig.
In addition to the above the `time_limit` attribute is added to the `SystemPartition`, as it happens with every other attribute of a partition in the configuration.
Fixes #2360.
> [bugfix] Properly select configuration when running tests

- cscs-checks/mch/openacc_cuda_mpi_cppstd.py
I propose to add the workaround reported in [PROGENV-8](https://jira.cscs.ch/browse/PROGENV-8) to the check `OpenaccCudaCpp`, namely reducing the MPI tasks per node to 11, until we get the fix by HPE Cray.
> [test] Temporary workaround for `OpenaccCudaCppCheck`

- ci-scripts/deploy.sh
- ci-scripts/genrelnotes.py
This PR provides two things:
1. When deploying ReFrame, update the version sanity check, so that it ignores the build metadata part of the version (i.e., the `+hash` thing).
2. Update the title of of the release notes.
> [ci] Minor deployment improvements

- reframe/core/launchers/mpi.py
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/lsf.py
- reframe/core/schedulers/slurm.py
- unittests/test_launchers.py
- unittests/test_schedulers.py
This PR exposes several `Job` attributes publicly by practically documenting them. It also uses the `variable` builtin to define them and also refactors a bit the arguments passed to the constructor of a `Job`. Now, the arguments that are passed to it are only those that must be set from the frontend either directly or indirectly through the configuration.
Fixes #2315.
> [feat] Extend the public API of `Job`

- cscs-checks/apps/vasp/vasp_check.py
I provide updated checks and reference values for VASP on Piz Daint after the upgrade: we will still need to monitor the performance over the next weeks, since I could not retrieve the data for the multicore check on Kibana.
> [test] Update VASP checks and reference values

- cscs-checks/apps/cpmd/cpmd_check.py
I provide an updated check for CPMD (based on #2454 for VASP), with a modified Slurm setup yielding improved performance for both `gpu` and `mc` architecture (note that the current check only runs on the `gpu` constraint of Piz Daint):
- I am setting the number of nodes for the smaller test case to 6, as we do for the other application performance checks
- the current test case does not scale beyond 72 MPI tasks and it is outdated (see warning about `XC_DRIVER IN &DFT`)
> [test] Update CPMD check

- reframe/frontend/statistics.py
Closes #2464 .
One small thing that I realized in this PR is that if we define a test like this:
```python
class X_foo(rfm.RunOnlyRegressionTest):
a = parameter(['a', 'b', 'c'])
...
```
we can rerun it with `-n X@foo@1` when `compact_test_names=True`, because of this code https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/filters.py#L29 . Should I leave it as it is or do we want to change the bahaviour there as well?
> [bugfix] Make rerun prompt consistent with the new naming scheme

- docs/regression_test_api.rst
- reframe/core/builtins.py
- reframe/core/deferrable.py
- reframe/core/fixtures.py
- reframe/core/hooks.py
- reframe/core/meta.py
- reframe/core/parameters.py
- reframe/core/variables.py
- unittests/test_pipeline.py
This PR moves all the builtins in the module `reframe.core.builtins`. This is to allow their use with the `make_test()` utility function that defines tests dynamically. Builtins that were manipulating the directly the namespace of the class were refactored so that they don't need to do it. There is one exception, which is also the only builtin that didn't move to the new module: the `bind()` builtin. This builtin needs to bind a free function to the test class and therefore needs to manipulate the test class namespace. Unit tests are also added to test `make_test()` with builtins. Finally, this PR moves all the documentation of the builtins in the source code avoiding duplication we had previously. The overall documentation for builtins is also slightly refactored.
This PR is a …
> [refactor] Move builtins in a separate module file and improve `make_test()` 

- cscs-checks/apps/cpmd/cpmd_check.py
I provide a quick fix to allocate the target `num_nodes` with a uniform number of `num_tasks_per_node` until the pull request [2712](https://github.com/eth-cscs/production/pull/2712) providing the MPI/OpenMP executable is fully tested and merged (the check will be updated accordingly).
> [test] Temporary fix for CPMD

- reframe/core/decorators.py
- reframe/frontend/loader.py
Fixtures are instantiated in the `instantiate_all()` method of the `TestRegistry`. This will allow us to use the `TestRegistry.instantiate_all()` to instantiate all the tests and their fixtures that will be dynamically generated in #2458.
> [refactor] Refactor fixture instantiation

- reframe/core/exceptions.py
When a `modulecmd python load` fails with a module file, the frame's code context being `None` causes `reframe` to terminate prematurely.
```
SUMMARY OF FAILURES
/home/chungsy/projects/reframe.git/bin/reframe: run session stopped: type error: can only join an iterable
/home/chungsy/projects/reframe.git/bin/reframe: Traceback (most recent call last):
File "/home/chungsy/projects/reframe.git/reframe/frontend/cli.py", line 1210, in main
runner.stats.print_failure_report(printer)
File "/home/chungsy/projects/reframe.git/reframe/frontend/statistics.py", line 210, in print_failure_report
run_report = self.json()[-1]
File "/home/chungsy/projects/reframe.git/reframe/frontend/statistics.py", line 164, in json
entry['fail_reason'] = errors.what(*t.exc_info)
File …
```
> [bugfix] Treat empty source code context when reporting errors

- reframe/core/fixtures.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_fixtures.py
The problem we have faced trying to implement the OSU benchmarks as a library in #2421 is that in the CSCS specialisation we wanted to set the `valid_systems` and `valid_prog_environs` based on the `osu_binaries.build_type` fixture parameter. This was only possible to achieve by creating explicitly different specialized tests for each build type, because we were not allowed to access fixtures before the setup stage. This PR solves this, allowing users to access fixtures as early as in a post-init hook. However, only fixture parameters are allowed to be accessed at this point, but it should be enough to serve us in almost all if not all scenarios. From the setup stage onward, there is no change in the behaviour compared to the past.
> [feat] Support early access to fixtures

- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
> [feat] Add new build system backend for custom builds

- reframe/core/schedulers/pbs.py
Pbs jobs can appear as completed before the stdout and stderr are written back to the working directory.
Fixes #2518 .
It might also be the reason @cblackworth-anl was getting this error in #1930.
> [bugfix] Check that PBS output is written back to working directory before setting the job as completed

- hpctestlib/microbenchmarks/gpu/dgemm/src/Xdevice
- hpctestlib/microbenchmarks/gpu/kernel_latency/src/Xdevice
- hpctestlib/microbenchmarks/gpu/memory_bandwidth/src/Xdevice
- hpctestlib/microbenchmarks/gpu/pointer_chase/src/Xdevice
- hpctestlib/microbenchmarks/gpu/shmem/src/Xdevice
That's a bug introduced with #2503 and exposed by the CI of https://github.com/eth-cscs/cscs-reframe-tests/pull/2.
> [testlib] Fix broken symlinks to the Xdevice header library

- reframe/frontend/executors/policies.py
One other thing we have talked about and would make sense to do in this PR is to expose `SLEEP_MIN`, `SLEEP_MAX` and `SLEEP_INC_RATE` in the configuration. It would be better to do it by partition but it would require more changes so maybe it's better to open an issue and do it in the next sprint. What do you think @vkarak ?
Fixes #2531.
> [bugfix] Reset poll rate every time a test finishes the compilation or run phase

- docs/config_reference.rst
- docs/tutorial_advanced.rst
- reframe/core/containers.py
- reframe/core/pipeline.py
- reframe/core/systems.py
- reframe/schemas/config.json
- reframe/utility/__init__.py
- tutorials/advanced/containers/gromacs_test.py
- unittests/resources/settings.py
- unittests/test_config.py
- unittests/test_containers.py
- unittests/test_pipeline.py
This PR improves how tests handle the `container_platform` attribute. Users are no more required to set the `container_platform` in their tests. This will be taken from the default `container_platform` defined for the current partition in the configuration. Also, this PR brings back the `workdir` attribute of the container platform and each backend emits the right option.
The documentation and the tutorial are also adapted and a new tutorial example is added which show cases a tests of GROMACS that runs both natively and from different containers.
In order to allow setting the `container_platform` attributes in the class body, we have employed the following trick. We assign a bogus `ContainerPlatform` that implements its abstract methods simply by raising a `NotImplementedError`. The …
> [feat] Do not require to set `container_platform` for running containerised tests

- reframe/frontend/statistics.py
- unittests/resources/checks/frontend_checks.py
- unittests/test_schedulers.py
We print `<undefined>` in case a variable is not yet defined. This can be the case when a test exits early. An example is [here](https://jenkins.cscs.ch/blue/rest/organizations/jenkins/pipelines/reframe-pilatus-production-daily/runs/396/nodes/7/steps/21/log/?start=0) where the tests fail during the setup stage.
This bug was introduced by #2543.
> [bugfix] Treat undefined variables correctly in run report

- docs/manpage.rst
> [doc] Add note about test dependencies in `--repeat` option docs

- requirements.txt
This makes `requests` compatible with `chardet` v5: https://github.com/psf/requests/pull/6179
> [packaging] Bump version of `requests` in `requirements.txt`

- docs/config_reference.rst
- docs/manpage.rst
- reframe/core/logging.py
- reframe/core/meta.py
- reframe/core/pipeline.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/filters.py
- unittests/test_dependencies.py
- unittests/test_filters.py
- unittests/test_fixtures.py
- unittests/test_logging.py
Each test is now associated with a hash code, which is generated by the test name and the key value pairs of its parameters. This hash code is printed along with the display name with the `-l` option and tests can be selected also by their hash code with the `-n` option, by passing `-n /<hash>`. Tests do still have their unique name that is comprised by the class name and the variant number. Test-specific files associated with the test execution, such as the stage and output directories and the performance log file of the `filelog` handler use the test's hash code in their filename. Conversely to the variant number, the test's hash code does not change if new values are added to a parameter, or values are deleted or the list of values are shuffled. However, you might get filesystem …
> [feat] Associate a unique hash with each test

- reframe/core/containers.py
- unittests/test_containers.py
> [bugfix] Fix singularity cli option to change to the mounted stage directory with the Singularity container platform

- hpctestlib/microbenchmarks/gpu/memory_bandwidth/src/memory_bandwidth.cu
The default of 1GB might be too small for newer systems to get a consistent measurement of memory bandwidth.
Need to be able to five larger values so fuse std:.stol instead of std:.stoi
> [testlib] memory_bandwidth.cu: Handle `size` argument larger than int

- reframe/core/pipeline.py
It's like a mild deprecation for the moment.
Closes #2153.
> [doc] Add a warning in documentation about the usage of `perf_patterns`

- ci-scripts/ci-runner.bash
- docs/manpage.rst
- reframe/frontend/cli.py
`RFM_AUTODETECT_FQDN` and `RFM_AUTODETECT_XTHOSTNAME` are now set to `0` by default.
Please note that site-specific scripts relying on the previous defaults should now set these environment variables properly.
Fixes #2576.
> [feat] Change default hostname autodetection parameters

- ci-scripts/genrelnotes.py
It seems that now the text in the release notes does not understand the `#PRNUM` notation, or more accurately, it seems not to render it correctly. It could be a bug in Github, so this is a workaround.
> [ci] Fix script that auto-generates the release notes

- reframe/utility/__init__.py
- reframe/utility/osext.py
- unittests/test_utility.py
ReFrame's version is retrieved though the `osext.reframe_version()` function throughout the framework. This checks if you are running a version from the repo and appends the commit hash to the standard version number. This is called literally everywhere, as the default log format has the `%(version)s` specifier, which means we call `git rev-parse` in every single log call! In this PR, I'm introducing a utility decorator to cache the return value of a function eternally and I'm decorating with this the `reframe_version()`. The speed up is (of course) impressive.
w/ caching
```
time ./bin/reframe --system sys1 -C unittests/resources/settings.py -c unittests/resources/checks_unlisted/fixtures_complex.py -r
[...]
Executed in    6.91 secs   fish           external
usr time    3.96 secs  143.00 …
```
> [bugfix] Remove redundant calls to git when trying to retrieve the version number

- docs/config_reference.rst
- reframe/schemas/config.json
I think it's better, because it allows you to look up previous runs by default.
> [feat] Revert to generating unique run reports

- reframe/frontend/cli.py
- unittests/test_cli.py
The output will look something like this:
```bash
$ reframe -m wrong_module -v ...
[ReFrame Setup]
...
./bin/reframe: could not load module 'wrong_module' correctly
Log file(s) saved in ...
```
With `-vv` then the output is:
```bash
$ reframe -m wrong_module -vv ...
[ReFrame Setup]
...
./bin/reframe: could not load module 'wrong_module' correctly
./bin/reframe: could not execute module operation: command 'modulecmd python show wrong_module' failed with exit code 0:
--- stdout ---
--- stdout ---
--- stderr ---
ModuleCmd_Display.c(157):ERROR:105: Unable to locate a modulefile for 'wrong_module'
--- stderr ---
Log file(s) saved in ...
```
Closes #2597 .
> [feat] Stop execution with an error when a cli module fails to load

- .github/workflows/test-flux.yaml
- docs/config_reference.rst
- docs/tutorial_flux.rst
- docs/tutorials.rst
- reframe/core/backends.py
- reframe/core/schedulers/flux.py
- reframe/core/schedulers/registry.py
- reframe/core/systems.py
- reframe/schemas/config.json
- tutorials/flux/Dockerfile
- tutorials/flux/README.md
- tutorials/flux/example1.py
- tutorials/flux/settings.py
- unittests/test_schedulers.py
This will add a basic scheduler that can interact with Flux: https://github.com/flux-framework/flux-core
Today is the first day I've ever used (and developed for) reframe, so I will need to ask for guidance on the best way to run tests, as either we will need a container base with flux or to mock something. The way I was able to develop and test is by adding a tutorial that I ran in a container! I also suspect I'll need to add proper documentation, if you could point me to the best places to do that. Thank you!
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> [feat] Add support for the Flux scheduler

- unittests/test_schedulers.py
> [bugfix] Submit jobs using the correct module path when testing scheduler backends

- docs/config_reference.rst
- reframe/core/containers.py
- unittests/test_containers.py
> [feat] Add support for the Apptainer container platform

- docs/config_reference.rst
- docs/tutorial_advanced.rst
- reframe/core/launchers/__init__.py
- reframe/schemas/config.json
Based on @giordano 's suggestion I removed the schema restriction and added an example in the documentation.
Closes #2560 .
@jgphpc @teojgo this will also make it easier for us to test on hohgant
> [feat] Allow user defined launchers in the configuration

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/frontend/cli.py
- reframe/schemas/config.json
Since Kibana rejects a record that includes a list of values of different types (for example `check_perfvalues`) I added the `perflog_ignore` in the configuration which will exclude these attributes from the json that we eventually send.
I don't think we should exclude the key  from all logs. What do you think?
> [feat] Add `perflog_ignore` attribute in httpjson handler

- README.md
- README_minimal.md
- README_pypi.md
- setup.cfg
@rsarm found an example from DeepSpeed's README.md https://github.com/microsoft/DeepSpeed/blob/master/README.md
You can see directly how it looks in https://github.com/ekouts/reframe/tree/dark_logo
(Hadn't noticed that there was an issue and a slightly different solution from Teo actually 😅)
Closes #2204
> [doc] Adapt README for dark and light Github modes

- docs/manpage.rst
- reframe/frontend/cli.py
> [feat] Remove the deprecated `RFM_GRAYLOG_SERVER` environment variable

- reframe/core/pipeline.py
- unittests/test_pipeline.py
This PR adds a new boolean test variable, named `require_reference`, that if set to true, it will cause the test to fail if there is no reference defined for the current system.
I believe that this is probable better than introducing a global configuration parameter, since variables give you both the ability to set them globally, but also per test.
> [feat] Allow tests to require references

- reframe/frontend/cli.py
> [bugfix] Filter out unnecessary fixtures when listing or running tests

- reframe/utility/osext.py
For this I guess with should change the name of the function since it has `cdt`. Maybe `cray_pe_version` and deprecate `cray_cdt_version `?
> [feat] Extend `cray_cdt_version()` utility function to recognise CPE versions too

- reframe/core/pipeline.py
This is to match the rest of non-required resource-related variables that default to `None`. This will also make `num_gpus_per_node` disappear from the new performance report, if it is not set, as it happens with the rest of the variables.
> [feat] Change default value of `num_gpus_per_node` to `None`

- docs/conf.py
- reframe/core/meta.py
- reframe/core/variables.py
- unittests/test_logging.py
- unittests/test_variables.py
This practically extends on the field aliasing that we used to have and brings the same concept to variables. Users can now define a variable as an alias of another one. This is quite useful for transitional periods and deprecations when a variable is renamed. An aliased can be defined as follows:
```python
x = variable(int, value=3)
y = variable(alias=x)
```
The variable `y` may not have a default value, but it can be independently loggable. Any update of variable `x` will be visible to `y` and vice versa. Aliased variables can refer also to inherited variables.
This feature is useful for transitional periods when a variable is renamed and a deprecation is introduced and we want to keep both names for a while. The new variable can also be wrapped with `deprecate()` to mark a deprecation. …
> [feat] Introduce variable aliases

- reframe/core/schedulers/slurm.py
- reframe/utility/__init__.py
- unittests/test_utility.py
> [bugfix] Keep updating the node list during the job

- reframe/core/environments.py
- reframe/core/pipeline.py
- reframe/core/runtime.py
- tutorials/advanced/parameterized/stream.py
- tutorials/basics/stream/stream4.py
- tutorials/cscs-webinar-2022/tests/stream4.py
- tutorials/cscs-webinar-2022/tests/stream5.py
- tutorials/cscs-webinar-2022/tests/stream6.py
- tutorials/cscs-webinar-2022/tests/stream7.py
- tutorials/cscs-webinar-2022/tests/stream8.py
- tutorials/cscs-webinar-2022/tests/stream9.py
- unittests/test_environments.py
- unittests/test_pipeline.py
Now the value of environment variables can accept any Python type. ReFrame will invoke `str(value)` automatically to emit it in a script.
This PR depends on #2648.
Fixes #56.
> [feat] Relax the value syntax of `env_vars`

- reframe/core/launchers/mpi.py
- unittests/test_launchers.py
For Slurm version >= 22.05 we pass explicitly `--cpus-per-task` to `srun` if `num_cpus_per_task` is set. For older versions we simply emit the `srun` command. If we cannot get the version of Slurm we also pass the option since it shouldn't hurt in theory for older versions.
Fixes #2655 .
> [bugfix] Pass explicitly the `--cpus-per-task` option to `srun` for Slurm >= 22.05

- reframe/core/pipeline.py
This is a small bugfix, because currently all tests are skipped because of errors like this with `--non-default-craype`:
```bash
WARNING: skipping test 'MKLResolveTest': type error: __init__() got an unexpected keyword argument 'variables' (rerun with '-v' for more information)
Traceback (most recent call last):
File "/users/eirinik/repos/reframe/reframe/core/decorators.py", line 74, in instantiate_all
leaf_tests.append(test(*args, **kwargs))
File "/users/eirinik/repos/reframe/reframe/core/meta.py", line 439, in __call__
obj.__init__(*args, **kwargs)
File "/users/eirinik/repos/reframe/reframe/core/hooks.py", line 97, in _fn
getattr(obj, h.__name__)()
File "/users/eirinik/repos/reframe/reframe/core/pipeline.py", line 972, in __pre_init__
self.__deferred_rfm_init.evaluate()
File …
```
> [bugfix] Fix injection of env variables for non default craype

- reframe/core/variables.py
- unittests/test_pipeline.py
> [bugfix] Fix variable assignment when aliases are set in subclasses

- .github/workflows/main.yml
- setup.cfg
We need to use an older container to test python 3.6 now, as the Github action with `ubuntu-latest` does not include it.
> [ci] Add support for Python 3.11 and update CI workflow for Python 3.6

- reframe/core/config.py
- reframe/schemas/config.json
- unittests/test_config.py
This allows config files to define logging partially for specific systems and inherit its value from the builtin config.
> [bugfix] Do not require `handlers$` in the logging config

- reframe/core/runtime.py
- reframe/core/schedulers/slurm.py
- reframe/frontend/autodetect.py
- unittests/test_argparser.py
This is a leftover from the change of `variables` to `env_vars`.
> [feat] Update `temp_environment` to use `env_vars`  as an argument

- docs/config_reference.rst
- docs/configure.rst
- docs/pipeline.rst
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/flux.py
- reframe/core/schedulers/lsf.py
- reframe/core/schedulers/oar.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/sge.py
- reframe/core/schedulers/slurm.py
- reframe/core/systems.py
- reframe/frontend/cli.py
- reframe/schemas/config.json
- unittests/test_schedulers.py
The scheduler options are now moved under in the `sched_options` inside each partition definition.
Closes #2669.
> [feat] Remove the `schedulers` section from the configuration

- reframe/core/meta.py
- reframe/core/pipeline.py
- unittests/test_fixtures.py
If a test had a join fixture over a parameterised test, whose parameterisation space is a single point only, ReFrame will erroneously include the fixture's parameter name in the display name of the test that is using it. This is not correct as tests with join fixtures do not inherit the fixture parameters. This bug was due to how `display_name` was checking if a fixture was a join or not; it was relying on the `get_variant_info()` information, which encodes the fixture space as a tuple only if it has more than two points. We instead use a much more robust check by checking directly the `action` of the fixture instance. The same bug was present also when constructing the `FixtureProxy` to allow early access to fixtures. Early access to join fixtures is not allowed, but the current …
> [bugfix] Properly set display name of tests with join fixtures

- reframe/core/pipeline.py
- reframe/utility/typecheck.py
- unittests/test_pipeline.py
- unittests/test_typecheck.py
Reference tuples cannot accept a deferrable as their elements.
This is achieved nicely by extending the type checking system to support composite types and by allowing to insert in the type check subsystem any custom type. For example, one can do the following:
```python
Deferrable = typ.make_meta_type('Deferrable', _DeferredExpression)
x = variable(typ.Integer|Deferrable|typ.List[typ.Integer|typ.Float])
y = variable(~typ.Deferrable)
```
This mechanism allows us to remove the `other_type` argument of `TypedField`, but it will probably break existing `variable` definitions of users.
Fixes #2630.
> [bugfix] Restrict reference tuples acceptable types

- reframe/core/pipeline.py
- unittests/test_filters.py
- unittests/test_pipeline.py
While I was working with parameterised tests, I noticed some hash clashes, where a test with a single parameter value was being assigned the same hash even if the parameter value changed. It turned out the bug was a missing `()` ! The `hashcode`  property was treating `is_fixture` as a property instead of a function, so the test was always returning true, thus the has was actually being computed based on the test's unique name and not based on its display name... I've added a unit test to avoid that from happening again.
> [bugfix] Fix hash clashes for parameterised tests

- docs/regression_test_api.rst
- reframe/core/schedulers/__init__.py
> [doc] Document the rest of `Job`'s properties

- reframe/core/logging.py
- reframe/frontend/executors/__init__.py
- unittests/test_policies.py
This is first attempt to fix the bug, but maybe we should investigate more:
1. how to handle errors in `log_performance`. It's not a good idea to completely suppress them, because the error that ReFrame gives in this case can be very confusing
2. if it's correct to have `check == None` for non-performance tests
Fixes #2715 .
> [bugfix] Fix cleanup crash for non-performance tests when the `perflog_compat` option is on

- MANIFEST.in
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
A file not following the README.* pattern is not included in the build dists and therefore the `long_description` remains empty.
Fixes #2730
> [bugfix] Add MANIFEST.in to include the README_minimal.md

- docs/manpage.rst
- reframe/frontend/filters.py
- unittests/test_cli.py
- unittests/test_testgenerators.py
We now use `re.search()` instead of `re.match()` for matching the name or tag patterns in the related cli options. So there is no need any more to prepend  `.*` to a name pattern so as to match something in the middle of the test name.
Closes #2658
> [feat] Relax the regex matching for test names and tags

- docs/manpage.rst
Based on the discussion on Slack [here](https://reframetalk.slack.com/archives/CF8ENLUDB/p1673859739976689).
@akesandgren How does it read now?
> [doc] Improve documentation for the `RFM_CONFIG_PATH`

- reframe/core/logging.py
- reframe/frontend/executors/__init__.py
- unittests/test_policies.py
> [bugfix] Fix performance logging when `perf_variables` are set in a performance stage hook

- reframe/frontend/filters.py
- unittests/test_filters.py
It also adapts the unit tests so that they fail with the erroneous implementation.
Fixes #2764.
> [bugfix] Fix broken `--cpu-only` and `--gpu-only` options

- hpctestlib/microbenchmarks/mpi/osu.py
This change should allow applying more fine-grained test customizations (see, e.g., https://github.com/eth-cscs/cscs-reframe-tests/pull/52) in the OSU micro-benchmarks. 
Thanks to @rsarm for suggesting this solution!
> [testlib] Change execution stage in OSU test library

- reframe/frontend/cli.py
Fixes #2745.
@flx42 Could you test this, as I don't have access to a Slurm cluster as a [privileged](https://slurm.schedmd.com/srun.html#OPT_nice) user?
> [bugfix] Pass long job options with `=`

- reframe/frontend/statistics.py
We do something similar in case of `BuildError`, where we add the `stderr` in the message of the exception: https://github.com/reframe-hpc/reframe/blob/develop/reframe/core/exceptions.py#L164
I print stderr and stdout in statistics because we have checks at CSCS that raise their own `SanityError` ([like this example](https://github.com/eth-cscs/cscs-reframe-tests/blob/main/checks/prgenv/affinity_check.py#L335)) and I thought other people may be using it like this.
What do you think? Should I change the PR and go with the approach of `BuildError`?
Closes #2668 .
> [feat] Print the first lines of stderr and stdout in case of sanity failures

- reframe/frontend/executors/policies.py
This is more general than a logging error, but this is the case that exposes the bug to the users. The problem was that we were unwittingly suppressing all exceptions (except `TaskExit`, which effectively denotes test errors) inside the `_advance_completing()` function. This was also posing a problem during development as it was masquerading programming errors that caused exceptions to be thrown from within this function. So much intricate was the bug to spot as so much trivial is the fix!
Fixes #2747.
> [bugfix] Fix confusing stack trace dump when a logging error occurs

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/schemas/config.json
- unittests/test_logging.py
This PR introduces two new configuration parameters for the `httpjson` handler:
1. `json_formatter`: this is a callable that will be passed the log record and it should return a valid JSON-encoded string. This configuration parameter is only valid for the Python config.
2. `debug`: if specified, then the server will not be contacted, but instead the encoded record will be dumped in a file in the current working directory.
This PR also changes how `check_perfvalues` are logged by the `httpjson` handler. Similarly to the `filelog` handler these are flattened and a separate batch of properties is created for each performance variable. For example, the various performance variables of the STREAM benchmark (Copy, Scale, etc.) are logged as follows:
```json
{
"check_perf_Copy_value": 16940.8, …
```
> [feat] Allow custom JSON formatting for log records in the `httpjson` handler

- reframe/frontend/cli.py
- reframe/frontend/loader.py
The fix turned out to be easy, since we were already storing the unset variables. This is now moved at the loader level and we warn only after all test filtering has happened in the cli (but before the treatment of the special options `--failed`, `--distribute` and `--repeat`).
Fixes #2672.
> [bugfix] Warn for unset variables only for the tests that are selected

- ci-scripts/genrelnotes.py
Now the script recognises also the `[enhancement]` prefix and a new section about enhancement is added. Also, empty sections are skipped.
> [ci] Improve the release notes generation

- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/lsf.py
- reframe/core/schedulers/oar.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
Replaces #2768.
As in the discussion in #2693, we now allow `num_tasks` be `None`. If set so, it is the user's responsibility to generate a valid job file. Scheduler backends will try not to (re)set `num_tasks` if it is not specified. See documentation for the exact behaviour of every backend.
> [feat] Allow `num_tasks` to be `None`

- docs/manpage.rst
- reframe/frontend/cli.py
When listing fixtures, we also print the variable name to which they are bound, so that users are able to select them in the `-S` option without having to inspect the test file. I have also enhanced the docs. This is how the new listing looks like:
```console
- osu_latency_test /d2c978ad
^build_osu_benchmarks ~generic:default+builtin 'osu_binaries /5cf701b0
^fetch_osu_benchmarks ~generic 'osu_benchmarks /9fc7952e
```
Closes #2763.
> [enhancement] Print the fixture variable names in test listings

- reframe/core/logging.py
> [bugfix] Correctly silence the `stream` handlers only when the `-q` option is passed

- docs/config_reference.rst
- docs/manpage.rst
- reframe/frontend/argparse.py
- unittests/test_argparser.py
The documentation for this case is a bit grey area. In documentation of the `modes` configuration parameter it is stated:
> The options of an execution mode will be passed to ReFrame as if they were specified in the command line.
And the docs for the `--mode` read as:
> If an option is specified both in an execution mode and in the command-line, then command-line takes precedence.
These are consistent for the options that can be specified only once: every time such an option is re-passed, it overwrites the previous one. But it's unclear what happens with options that are of an `append` type. The first excerpt implies that the options will be simply unpacked and combined with the same options in the command line (desired behaviour that this PR provides), but the second excerpt allows the …
> [enhancement] Properly combine `append`-type command-line options defined in execution modes

- docs/deferrable_functions_reference.rst
- docs/tutorial_basics.rst
- reframe/core/pipeline.py
Although this PR is primarily about the updating and improving the docs, I use the bug fix as a title, so that it shows up in the release notes.
Closes #2704.
> [bugfix] Register performance functions even if `perf_variables` are defined in the class body and improve the performance function docs

- reframe/frontend/cli.py
- unittests/test_cli.py
> [enhancement] Raise warning for invalid mode cli option

- docs/config_reference.rst
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/slurm.py
- reframe/schemas/config.json
- unittests/resources/config/settings.py
- unittests/test_config.py
- unittests/test_schedulers.py
This PR fixes three bugs related to `sched_options`. Two were introduced in 4.0 and one was present since the introduction of the `use_nodes_option` parameter.
1. Scheduler backends were not accessing the correct configuration section due in order to get the partition's `sched_options` due to a typo! This is fixed, unit tests are added to verify it and the configuration schema for accessing the `sched_options` has become stricter in order to avoid typos going undetected in the future.
2. Fix the configuration schema and allow `sched_options` to be defined inside the `systems` section, as it is also stated in the docs.
3. Fix crash of the `use_nodes_option` when then `num_tasks_per_node` was not set. This bug was present since the introduction of the `use_nodes_option`. If …
> [bugfix] Fix use of `sched_options` by the backend schedulers

- docs/tutorial_build_automation.rst
- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
`reframe.core.buildsystems.Spack` supports setting `install_tree`, but there are many other ways to configure a Spack environment. This proposal introduces support for setting arbitrary Spack environment configuration options. The implementation is nearly identical to how `install_tree` works.
As an example with the changes proposed here, one could set the following:
`self.build_system.config_opts = ['concretizer:unify:false']`
If the configuration option is not already present in the default `spack.yaml`, it is added. If the configuration option is present in the default `spack.yaml`, Spack overwrites them with the values given via `spack config add`.
> [feat] Support arbitrary Spack environment configuration

- reframe/core/fields.py
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/utility/typecheck.py
- unittests/test_fields.py
- unittests/test_typecheck.py
This PR fixes the same problem for all other `TimerField` variables. 
To allow setting these fields properly from the command line, we get rid of the `TimerField` and replace it with the augmented type `Duration`, which is similar in concept with the `Bool` type. This type allows conversion from floats, int and strings and applies essentially the logic of the former `TimerField`. Since for this field we want to allow conversions also when it's set from inside the test, e.g., `time_limit = '10s'`, we add a new argument `allow_implicit` to the `TypedField` constructor (also exposed through the `variable` builtin), which make the field try implicit conversions before assigning the value to the test attribute. Therefore a variable declared as `x = variable(int, allow_implicit=True)` can be …
> [bugfix] Allow proper assignment of `time_limit` from command line

- hpctestlib/microbenchmarks/gpu/gpu_burn.py
> [testlib] Set `executable_opts` of GPU burn test in a pre-run hook

- .readthedocs.yaml
Setting the "Advanced settings" from the readthedocs page in the yaml file.
Closes #2753 .
> [doc] Add a `.readthedocs.yaml` for generating the docs

- reframe/frontend/cli.py
- unittests/test_cli.py
This PR adds a `latest.json` symlink to the latest run report. This is useful when there are many reports and you would like to see all the details of the last run. Another extension that we could consider is to add an option to "tag" a report for quick future reference. This would create a symlink to the report using the tag name. What do you think?
> [feat] Add a symlink to the latest run report

- reframe/core/pipeline.py
- reframe/frontend/ci.py
- unittests/test_ci.py
This PR allows to use Gitlab CI options to filter tests, e.g. based on [downstream pipelines](https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html) or [changes of the file](https://docs.gitlab.com/ee/ci/jobs/job_control.html). A minimal working example is provided in the repository https://gitlab.com/latticeqcd/reframe-debug, see [hello1.py](https://gitlab.com/latticeqcd/reframe-debug/-/blob/master/hello1.py)
- [Pipeline 810057836](https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/810057836) runs for a branch that is in merge request, but has unmodified source file. Hence the test `HelloMergeRequest` is run.
- [Pipeline 810072116](https://gitlab.com/latticeqcd/reframe-debug/-/pipelines/810072116) now has modified source file and thus runs additionally `HelloModified`.
> [feat] Add new `ci_extras` test variable that allows passing test-specific options to the pipeline generated by `--ci-generate`

- docs/manpage.rst
- reframe/core/exceptions.py
- reframe/core/schedulers/local.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- reframe/frontend/printer.py
- reframe/frontend/statistics.py
- unittests/test_cli.py
- unittests/test_policies.py
This PR introduces the following two options that are meant to allow users to use reframe for stress testing a target system:
- The `--reruns=N` option will rerun the same test suite N times (N+1 total runs).
- The `--duration=TIMEOUT` option will run the same test suite repeatedly until `TIMEOUT` expires.
Compared to the similar `--max-retries` option that reruns the failed tests, these options will report statistics as well as failures from _all_ runs.
Closes #619.
@brandongc FYI
> [feat] Add support for repeated testing through two new options: `--reruns` and `--duration`

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/core/settings.py
- unittests/test_policies.py
ReFrame 4.0 erroneously changed the `check_perf_lower/upper_thres` log record attributes to `check_perf_lower/upper`, but only for the single line output of perflog. The multiline output still recognised the original names. This PR fixes this inconsistency by using the original names everywhere.
Closes #2809.
> [bugfix] Fix log record attribute names of performance thresholds

- docs/manpage.rst
- reframe/core/runtime.py
- reframe/frontend/cli.py
- reframe/frontend/runreport.py
- test_reframe.py
- unittests/resources/config/settings.py
- unittests/test_cli.py
This is a follow up of #2834 and fixes #2849.
The implementation of this feature is refactored as well as some of the unit tests. The `run_reframe()` is now running from the temp path, so some of the of the unit tests had to be adapted.
> [bugfix] Do not symlink against report files in non-default locations

- README.md
We will discontinue the use of the Heroku app for two reasons: (a) it's not anymore free and (b) it's not working for a while. This PR uses an official permanent invite link for the workspace.
> [doc] Use official Slack permanent invite link

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/schemas/config.json
I tested this with ncat and a small config file as 
```python
site_configuration = {
'logging': [
{
'handlers_perflog': [
{
'type': 'httpjson',
'url': 'http://localhost:12345',
'level': 'info',
'extras': {
'facility': 'reframe',
'data-version': '1.0'
},
'debug': False,
'extra_headers': {
'ApiKey': 'test'
}
}
]
}
]
}
```
Closes #2850.
~~Should we implement a test ?~~
> [feat] Allow custom HTTP headers with the `httpjson` log handler

- docs/config_reference.rst
- docs/configure.rst
- docs/manpage.rst
- reframe/core/config.py
- reframe/core/settings.py
- reframe/frontend/cli.py
- reframe/frontend/loader.py
- reframe/schemas/config.json
- reframe/utility/__init__.py
- unittests/resources/config/settings.py
- unittests/test_config.py
~~There is a new section in the configuration that defines how to detect the system:~~
```python
site_configuration = {
'autodetect': [
{
"method": "hostname",
},
{
"method": "fqdn",
},
{
"method": "xthostname",
},
{
"method": "custom_cmd",
"cmd": "echo sys",
},
{
"method": "custom_file",
"file": "myhostnameo.txt"
},
],
'systems': [
...
```
~~Reframe will check the list and pick the system based on the first successful method. The default configuration has the standard `hostname` method. Reframe picks the first method that will be successful so as a result additional autodetect sections will be put on top of the list, like we do for systems.~~
EDIT from @vkarak 
I updated this PR so that the syntax of autodection methods is simplified but also generalised. More specifically, we introduce …
> [feat] Support custom system auto-detection methods

- docs/started.rst
- requirements.txt
Due to https://github.com/reframe-hpc/reframe/security/dependabot/4
> [dependencies] Update requests version and add a Python 3.6 disclaimer

- reframe/utility/sanity.py
> [doc] Fix broken formatting in `extractall_s()` docs

- docs/tutorial_advanced.rst
Re-applying #2892 to `master`.
> [doc] Fixed a typo in documentation - `JobLaucher` to `JobLauncher`

- reframe/core/pipeline.py
> [doc] Fix broken docs links in `valid_systems` and `valid_prog_environs` sections

- reframe/frontend/dependencies.py
- unittests/test_dependencies.py
The fix was straightforward; we need to re-calculate the the in-degree of the nodes of the pruned graph, which is the testcase graph after filtering.
Closes #2916.
> [bugfix] Properly cleanup resources of dependencies when their dependents are filtered

- reframe/core/buildsystems.py
- unittests/test_buildsystems.py
ReFrame, unless targeting a user-specified existing Spack environment, automatically passes the `-d rfm_spack_env` option to create an ephemeral environment. This is a small addition that allows users to define extra `spack env create` options ([link to Spack docs for list of options](https://spack.readthedocs.io/en/latest/command_index.html#spack-env-create)). 
With the changes proposed here, a user could define the following:
```python
self.build_system.env_create_opts = ["--without-view"]
```
which produces following in the build job script:
```sh
spack env create -d rfm_spack_env --without-view
```
While technically this allows for any `spack env create` options, my motivation for this feature is use of `--without-view`. ReFrame's use of temporary Spack environments leaves little use …
> [feat] Additional Spack build system options

- docs/manpage.rst
- reframe/core/meta.py
- reframe/frontend/cli.py
- reframe/frontend/testgenerators.py
- unittests/test_cli.py
- unittests/test_testgenerators.py
This PR introduces parameterisation from the command line on existing variables. Passing `-P num_tasks=1,2,4,8` will create a parameterised version of a test with different `num_tasks` values. This feature cannot parameterise fixtures.
Closes #2665.
> [feat] Parameterise test from command line

- reframe/core/runtime.py
- reframe/frontend/cli.py
- unittests/test_cli.py
The new format is `%y%m%dT%H%M%S%z` which translates to `230620T005733+0200`.
Closes #2867.
> [feat] Update default `--timestamp` format

- docs/manpage.rst
- reframe/utility/typecheck.py
- unittests/test_typecheck.py
The advantage is that we can automatically convert nested mappings, like for example the `extra_resources` attribute, which can thus be set from the command line.
This is the kind of change I'd like to propose to fix #2868.  If this is deemed acceptable, I'll add some tests.
> [feat] Allow setting nested mapping types using the `-S` option

- reframe/core/schedulers/oar.py
The `oarstat` regular expression now supports `id: XXX` as well as `Job_Id: XXX`, thereby supporting all possible values of `$OAR_OARSTAT_OUTPUT_FORMAT` (1, 2 and 3).
Additionally, the link to the oarstat source is updated.
Fixes https://github.com/reframe-hpc/reframe/issues/2944
> [bugfix] Update OAR scheduler backend to accept the `Job_Id:` syntax

- reframe/core/config.py
…would get the configuration options.
Resolves #2932
> [bugfix] Properly apply logging configuration to all systems listed in `target_systems`

- reframe/core/decorators.py
- reframe/frontend/cli.py
- reframe/frontend/loader.py
- tutorials/cscs-webinar-2022/config/mysettings.py
> [enhancement] Warn on unset variables in fixtures when using the `-S` option

- .github/workflows/test-flux.yaml
- bootstrap.sh
- ci-scripts/dockerfiles/Lmod-base.dockerfile
- ci-scripts/dockerfiles/Lmod77-base.dockerfile
- ci-scripts/dockerfiles/Spack.dockerfile
- ci-scripts/dockerfiles/Tmod4-base.dockerfile
> [enhancement] Run `./bootstrap.sh` in a virtual environment

- reframe/schemas/config.json
Allow users to define and integrate custom schedulers without having to modify the framework. This simply boils down to relaxing the configuration schema. Then users can simply import their scheduler code in the configuration and use the name that it is registered with.
The docs are deferred for #2610.
Closes #2954.
> [feat] Support for custom schedulers

- hpctestlib/system/ssh/host_keys.py
This test checks the ssh host keys age. The list of host keys and the maximum age allowed are parameters and variables of the test.
If the key file is not found, the test is skipped
> [testlib] New test for testing SSH host keys

- reframe/utility/typecheck.py
- unittests/test_typecheck.py
And also string comparisons are case-insensitive when converting to boolean.
Closing #2971.
> [bugfix] Accept `y` and `n` for boolean conversions

- docs/config_reference.rst
> [doc] Document default value of `format_perfvars`

- reframe/frontend/autodetect.py
What we do essentially is to fall back in a venv+pip install solution if we can't copy the standard source structure. In that case, we install reframe from pip in a venv and invoke `reframe --detect-host-topology`.
Also this PR removes the parallel launcher from the remote detection script as suggested in #2926.
Closes #2914.
FYI: @casparvl @jack-morrison.
> [bugfix] Fix remote topology detection for pip installations

- docs/regression_test_api.rst
- reframe/core/builtins.py
- reframe/core/hooks.py
- reframe/core/pipeline.py
- unittests/test_meta.py
- unittests/test_pipeline.py
This PR introduces a new argument `always_last` to the `@run_before` and `@run_after` decorators that will pin the current hook as the last of its stage. Only one such hook can exist for each stage in a test hierarchy. This feature should make writing test libraries easier, as they can pin their hooks at the end of a stage overriding therefore therefore the default hook execution order.
Closes #2749.
> [feat] Allow pinning a hook as the last of its stage

- reframe/core/hooks.py
- reframe/core/meta.py
- unittests/test_pipeline.py
> [bugfix] Respect execution order of overriden hooks

- reframe/core/schedulers/pbs.py
This is a start to address #2936.  It doesn't quite work as desired at the moment, because I don't know what to do exactly with the exit status, how do I use it to make ReFrame error if the job failed?
Closes #2936.
> [bugfix] Properly retrieve exit status for PBS Pro jobs

- docs/config_reference.rst
- reframe/core/backends.py
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/ssh.py
- reframe/schemas/config.json
- reframe/utility/osext.py
- unittests/test_schedulers.py
- unittests/test_utility.py
The new backend is called `ssh` and will spawn a test job on a remote host. More specifically, it will copy the test's stage directory to the remote host, execute the job and copy back the results.
Multiple hosts can be assigned to a partition with an `ssh` scheduler, in which case the scheduler will pick the next free host to spawn a test on.
This PR also introduced a new `run_command_async2` utility for executing asynchronous commands. Conversely to the `run_command_async`, this returns a "future" encapsulating the spawned process. Process futures can be chained with the `then()` method and the chained futures will be called upon termination of the predecessor in the chain.
The SSH scheduler backend uses the process futures and spawns a chain of push artefacts-execute job-pull artefacts …
> [feat] Add an SSH-based scheduler backend

- docs/manpage.rst
- reframe/frontend/cli.py
- reframe/frontend/filters.py
- unittests/test_cli.py
- unittests/test_filters.py
This PR introduces a new option, `-E` or `--filter-expr`, that allows user to filter tests on arbitrary expressions on any test variable or parameter, e.g., `-E 'num_nodes>10'` will select all tests that define set the custom variable `num_nodes` greater than 10.
It also deprecates the `--cpu-only` and `--gpu-only` options as these can be expressed 1-1 with `-E`.
Closes #2847.
> [feat] Filter tests using arbitrary expressions

- reframe/frontend/autodetect.py
Closes #3023.
@casparvl Could you test if this work for your case?
> [bugfix] Upgrade pip before pip-installing reframe for CPU autodetection

- reframe/utility/__init__.py
- unittests/test_utility.py
> [bugfix] Treat node name suffixes properly in abbreviated node lists

- docs/hpctestlib.rst
- hpctestlib/system/fs/mnt_opts.py
The filesystem_option_check check if the file systems were properly configured based on their type
> [testlib] Add fs mount options check to hpctstlib

- docs/config_reference.rst
> [doc] Fix typo in `file` log handler docs

- docs/tutorial_tips_tricks.rst
> [doc] Fix typo in docs about sanity patterns debugging

- reframe/core/launchers/mpi.py
- unittests/test_launchers.py
> [bugfix] Do not pass the stdout/stderr options to `srun` when using the `srunalloc` launcher

- docs/configure.rst
> [doc] Remove outdated text in configuration docs

- docs/config_reference.rst
- docs/manpage.rst
- reframe/core/modules.py
- reframe/core/systems.py
Not sure if this PR is more suitable for `master` or `develop`. I can change it in any case.
> [enhancement] Skip modules system sanity checking when module conflict resolution is off

- reframe/frontend/testgenerators.py
- unittests/resources/checks_unlisted/distribute.py
- unittests/test_cli.py
> [bugfix] Fix crash when `--distribute` option is applied to a run-only test

- docs/manpage.rst
- reframe/frontend/cli.py
I've also re-org'ed of the related docs a bit and have created a new options group in the CLI for the test generation options.
Closes #3072.
> [doc] Document the limitations of the test generation options

- reframe/core/parameters.py
- reframe/core/pipeline.py
- reframe/core/variables.py
- unittests/resources/checks/frontend_checks.py
- unittests/test_logging.py
- unittests/test_meta.py
> [enhancement] Make variables and parameters loggable by default

- docs/regression_test_api.rst
- reframe/core/builtins.py
- reframe/core/pipeline.py
- unittests/test_pipeline.py
> [enhancement] Allow `always_last` to be defined in multiple hooks and add a note about users' workaround code for enforcing hook execution order

- docs/config_reference.rst
- reframe/core/pipeline.py
> [feat] Expose job submit time as a loggable property

- bootstrap.sh
Curl is not a default package on most Linux distributions, and is not listed as a requirement for reFrame.
When curl is missing, bootstrap.sh will blow right past the curl failure and continue to attempt to execute commands.
Add a check for curl, and print a meaningful message + exit if it is not found.
> [bugfix] Detect missing `curl` in `bootstrap.sh`

- docs/config_reference.rst
- reframe/core/environments.py
- reframe/core/systems.py
- reframe/schemas/config.json
- unittests/test_config.py
This commit allows you to specify the path to nvidia's nvcc a part of a system environment. This allows for multiple environments with different paths to nvcc without the use of modules or the PATH environment. It allows for nvcc being unset in the environment and will default to 'nvcc'.
> [feat] Add `nvcc` as an environment configuration parameter

- reframe/frontend/autodetect.py
This is useful for the firecrest scheduler, but probably also for other schedulers.
> [bugfix] Do not ignore the `use_login_shell` configuration option when generation the auto-detection script

- reframe/core/launchers/mpi.py
This covers also the cases when Slurm is installed through apt, where it's name is `slurm-wlm`.
> [bugfix] Better version check for Slurm in the  `srun` backend

- reframe/schemas/config.json
- reframe/utility/cpuinfo.py
By having the CPU vendor identifier available, test authors can use "GeniuneIntel", "AuthenticAMD", etc. as a logic condition where high-level characterization is acceptable. There are cases where this may actually be more useful than the particular CPU model name.
Fixes #https://github.com/reframe-hpc/reframe/issues/2995
> [feat] Add CPU vendor and model name to topology files

- reframe/core/launchers/__init__.py
- reframe/core/launchers/rsh.py
- unittests/test_launchers.py
This PR introduces two new variables in `JobLauncher`: `modifier` and `modifier_options`. These are combined and prepended to the emitted parallel launcher command. The use of `LauncherWrapper` is depreceted.
Closes #3100.
> [feat] Introduce launcher modifiers replacing `LauncherWrapper`

- docs/regression_test_api.rst
- reframe/core/buildsystems.py
- reframe/core/containers.py
- reframe/core/decorators.py
- reframe/core/fields.py
- reframe/core/variables.py
- unittests/test_pipeline.py
- unittests/test_variables.py
Currently, the default values of variables or the values assigned to them in the test class body are not type checked and no implicit conversions are applied to the value being assigned. This is deferred at the class instantiation time where the default values of variables are injected to the newly created test object and type checked through the associated descriptor.
This PR moves the type checking and implicit conversions, i.e., the functionality of the descriptors at the class level. We do so, with two tricks:
1. We extend the Python descriptor model by having `__set__()` return the value that the descriptor would write into the object if the object passed to `__set__()` is `None`.
2. We anticipate the call to the descriptor's `__set_name__()` at the same time that this function is …
> [feat] Enable default value type checking and implicit conversions at the variable declaration level

- reframe/core/schedulers/slurm.py
> [bugfix] Do not fail if `squeue` cannot retrieve the reason that a job is pending

- docs/tutorial_deps.rst
This PR fixes a typo in the documentation
> [doc] Fix spelling mistake in the documentation

- setup.cfg
This fixes the failures of the "wheelvalidation" GH action in random PRs after archspec 0.2.3 release which breaks ReFrame. The problem is the following:
The `install_requires` in our `setup.cfg` is too loose, stating only the package names not versions. When the CI tries to create the wheel, it fetches the latest archspec which then breaks us. I've made the `install_requires` stricter to avoid such problems. We should make sure to update also `setup.cfg` in the next release of archspec.
> [packaging] Stricter install requirements in `setup.cfg`

- reframe/core/systems.py
- reframe/schemas/config.json
- unittests/resources/config/settings.py
- unittests/test_autodetect.py
- unittests/test_config.py
> [feat] Add a `model` property to the devices configuration

- docs/hpctestlib.rst
- hpctestlib/sciapps/qespresso/benchmarks.py
This PR adds a reframe reusable test for QuantumESPRESSO, aimed at testing the scaling  `pw.x` executable.
The parameters `ecut` and `nbnd` can be tuned in order to increase the usage of either FFTW or diagonalization routines.
For now the input file is baked into the source code, but it could be easily moved to a separate repo, like for the GROMACS test
> [testlib] Added QuantumESPRESSO scalability test for `pw.x`

- docs/manpage.rst
- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/slurm.py
- reframe/frontend/cli.py
- reframe/frontend/testgenerators.py
The key problem with those options currently is that there is no way to select a node that is exclusively in the ``idle`` state. As a result, nodes in `idle+drain` etc. states will be selected and jobs will be blocked forever. This PR fixes this by introducing exclusive state selection. More specifically, the following changes are made:
1. The `STATE` argument implies exclusive state selection.
2. The old behaviour is preserved with `STATE*`, meaning that a node to be selected must be at least in state `STATE`.
3. The new special argument `avail` is added which will selected all the nodes available for running a job. For Slurm, these are nodes in `IDLE`, `ALLOCATED` or `COMPLETING` states.
Closes #2258.
> [feat] Improve state selection criteria in the `--distribute` and the `--flex-alloc-nodes` option

- reframe/core/logging.py
- unittests/test_policies.py
I hit this subtle and nasty bug while working on the new tutorial. It is exposed more easily now that the variables and parameters are by default loggable. The problem is the following:
When a series of tests that define different variables is set, ReFrame's logging will crash with an error like this:
```console
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
msg = self.format(record)
File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
return fmt.format(record)
File "/usr/lib/python3.10/logging/__init__.py", line 681, in format
s = self.formatMessage(record)
File "/usr/local/share/reframe/reframe/core/logging.py", line 366, in formatMessage
return self.__fmt % record_proxy
KeyError: 'check_nthr' …
```
> [bugfix] Fix logging crash when the `check_#ALL` placeholder is used

- docs/config_reference.rst
- reframe/core/systems.py
- unittests/resources/config/settings.py
- unittests/test_config.py
This is a follow up of #3107 and defines the `model` attribute in `ProcessorInfo`.
> [feat] Make processor model available through `ProcessorInfo`

- reframe/core/pipeline.py
- reframe/frontend/cli.py
Although `--disable-hook` works fine, the `--describe` option still lists the disabled hooks.
> [bugfix] Hide disabled hooks from `--describe` option's output

- docs/config_reference.rst
- reframe/core/systems.py
- reframe/schemas/config.json
- reframe/utility/cpuinfo.py
- unittests/resources/config/settings.py
- unittests/test_config.py
> [feat] Include hardware platform info in `ProcessorInfo`

- reframe/core/schedulers/__init__.py
Fixes #3143.
@vkarak I'm not seeing the recent PBS change you mentioned on #3143 - do you mind pointing me to it? Am I correct in assuming that Slurm is no longer the only backend where this attribute is reliably set?
> [doc] Update `Job.nodelist` description

- reframe/core/pipeline.py
- unittests/resources/checks/hellocheck.py
> [feat] Do not require a sanity function for compile-only tests

- docs/config_reference.rst
- docs/manpage.rst
- reframe/core/launchers/__init__.py
- reframe/core/schedulers/slurm.py
- unittests/test_schedulers.py
This PR fixes also the way `sched_access` constraints are combined with those specified in the CLI or in the `job.options` by parenthesizing appropriately. It also updates the docs.
> [bugfix] Treat OR Slurm constraints in flexible node allocation

- docs/config_reference.rst
- reframe/core/environments.py
- reframe/core/pipeline.py
- reframe/core/systems.py
- reframe/schemas/config.json
- unittests/resources/config/settings.py
- unittests/test_config.py
This is a second attempt for this issue. ~I am missing the documentation + unittests but I would like first to agree on the api.~
It would be very similar to the resources of the test. And the configuration would look like this.
```python
site_configuration = {
'systems': [
{
...
'partitions': [
{
'resources': [
{
'name': 'switches',
'options': ['--switches={num_switches}']
},
{
'name': 'gres',
'options': ['--gres={gres}']
},
{
'name': 'uenv',
'options': [
'--uenv-file={file}',
'--uenv-mount={mount}',
]
}
]
}
]
}
],
'environments': [
{
'name': 'myenv',
'resources': {
'uenv': {
'mount': 'one',
'file': 'two',
}
}
}
]
}
```
That would translate to the following options in the job script:
```bash
#SBATCH --uenv-file=two
#SBATCH --uenv_mount=one
```
Closes #2991 .
> [feat] Add support for associating scheduler resources with an environment

- docs/requirements.txt
- reframe/utility/cpuinfo.py
- requirements.txt
- setup.cfg
This follows https://github.com/reframe-hpc/reframe/pull/3107 and https://github.com/reframe-hpc/reframe/pull/3132 to adopt the new function from [archspec v0.2.4](https://github.com/archspec/archspec/releases/tag/v0.2.4) returning a CPU brand string.
> [feat] Update `archspec` and topology file call for CPU model name

- .github/workflows/main.yml
This action is no more reliable and leads to CI failures. Codecov will be set up again with #3024.
> [ci] Do not upload to Codecov through a GH action

- docs/config_reference.rst
- docs/manpage.rst
- reframe/core/pipeline.py
- reframe/core/schedulers/__init__.py
- reframe/frontend/cli.py
- unittests/test_schedulers.py
Flexible tests are now by default skipped when not enough nodes are found. We introduce a new option, `--flex-alloc-strict` that will cause the test to fail instead (the current default).
Closes #3164.
> [feat] Skip by default flexible tests when not enough nodes found

- examples/tutorial/dockerfiles/slurm-cluster/reframe/Dockerfile
- reframe/core/schedulers/slurm.py
> [bugfix] Retrieve the test job's nodelist when using the `squeue` backend

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/core/pipeline.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- unittests/test_cli.py
- unittests/test_policies.py
The idea is the same as exposed in the issue.
In case of sanity failures, we execute also the performance stage but in dry-run mode suppressing any non-aborting exception. To achieve so, we also extended the dry-run mode inside the performance stage to also generate the `perfvalues` which are required by the logging handlers for emitting the performance record.
In case of sanity failures, the performance values will be logged as `None`.
Closes #3186.
> [feat] Add a perflog entry also when sanity fails

- reframe/utility/cpuinfo.py
> [bugfix] Handle `None` cpu model name returned from `archspec`

- docs/tutorial.rst
Long options are more self-documenting.
> [doc] Use long options in places

- docs/tutorial.rst
The tutorial was skipping the two imports
import reframe as rfm
import reframe.utility.sanity as sn
by using the :pyobject: option to only highlight stream_test. This is the first example shown in the tutorial and it is important that the entire file is displayed.
Presumably this technique is used to avoid the license notice; we can use :start-at: instead.
> [doc] Display Python imports in the first tutorial example

- docs/regression_test_api.rst
- docs/tutorial.rst
Closes #3198. Also corrects a mischaracterization of `builtin`; it
is not a partition, it is an environment.
> [doc] Improve description of `valid_systems` and `valid_prog_environs` in the tutorial and other minor tutorial fixes

- reframe/core/logging.py
> [bugfix] Fix logging crash when `timestamp=True` for the `file` log handler

- requirements.txt
Reverts reframe-hpc/reframe#3235
This is not needed, we are already in the latest and most secure version.
> Revert "Bump setuptools from 70.1.1 to 70.0.0"

- docs/manpage.rst
- reframe/frontend/cli.py
- reframe/frontend/printer.py
- unittests/test_cli.py
This is a follow up of #3227 as a means to let users reduce the size of the produced tables on-demand. For example, `sysenv` is essential for uniquely identifying test cases and grouping them together, but users may not want to list this column in certain contexts.
This PR also introduces some minor fixes in the profiling of the storage options and removes alignment of numbers on the dot in tables.
> [feat] Introduce new option `--table-hide-columns` for hiding columns in tabular data output

- docs/manpage.rst
- reframe/frontend/cli.py
- reframe/schemas/config.json
This is a follow up of #3227.
The default for `--performance-report` is now just listing the performance of the current run. This is done to (a) to keep compatibility with current behaviour and (b) the previous default could lead to increased times for producing the report in case a large results DB had to be scanned. Now the default `--performance-report` output is O(1) time.
The default for `--list-stored-sessions` is now limited to a week back. The previous default (`all`) could lead to very long output for large results DBs.
> [enhancement] Change default values for `--performance-report` and `--list-stored-sessions` options

- reframe/frontend/reporting/storage.py
This is a follow up fix on #3227 and build on top of #3253.
This PR eliminates the JOIN between the `testcases` and `sessions` arrays as is this very detrimental to performance for sessions that run many testcases. The problem with the current implementation is that the JOIN will replicate the whole session `json_blob` for *every* testcase record bloating the memory consumption and hurting performance significantly!
The approach taken in this PR is replacing the single JOIN query with 2+1 SELECT. First we get the distinct session UUIDs that correspond to the test cases matching the selection criteria. Then we use those session UUIDs to extract their blobs from the `sessions` table decoding them and indexing them in memory. Finally, we get the testcase UUIDs matching the criteria selection …
> [bugfix] Optimize testcase queries over time period

- docs/tutorial.rst
- examples/tutorial/dockerfiles/slurm-cluster/docker-compose.yml
- reframe/core/meta.py
- reframe/core/pipeline.py
- reframe/frontend/cli.py
- reframe/frontend/filters.py
- reframe/frontend/testgenerators.py
The `name` test attribute is not anymore a full alias of `display_name`. It hides all special parameters starting with `$` that are inserted by the automatic test generation options, such as `--repeat`, `--distribute` etc.
Also the test name of the parameterized test with `--distribute` does not contain any more the partition name, but instead the partition has become a special test parameter.
Finally, all the special parameters are converted to non-loggable.
The motivation behind these changes is that previously both the special parameters and the different name of the "distributed" tests were causing confusion with logging (e.g., different log files, different headers etc.) and were preventing results comparisons with the new `--performance-compare` option.
> [enhancement] Improve naming of automatically generated tests

- reframe/core/modules.py
Running a typical subset of NERSC's test suite with ~500 tests, there are ~30 unique values passed to this routine and the result of call for a given input is static. `module` commands can take a surprisingly long amount of time to return.
This change reduces the time for
```
reframe -C ./nersc-config.py -c checks --dry-run --mode checkout
```
from ~735s to <600s.
> [enhancement] Improve performance of module backend when detecting module conflicts

- docs/manpage.rst
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- unittests/test_policies.py
Closes #3139.
This option will skip retries if failures are above the given threshold. This is useful when something is obviously wrong and you don't want ReFrame to continue looping with retrying tests that will most likely fail again.
> [feat] Add new `--retries-threshold` option

- docs/manpage.rst
- reframe/frontend/cli.py
- reframe/frontend/printer.py
- reframe/frontend/reporting/__init__.py
- unittests/test_cli.py
This option will add arbitrary key/value pairs to the session, which allows users to append extra metadata when storing the current session (e.g., add the CI job id if the session is being run as part of a CI pipeline).
> [feat] Support session annotations with a new `--session-extras` option

- reframe/core/schedulers/slurm.py
This PR fixes an issue with flexible node allocations when no partition is specified and there is no default partition in slurm. 
At NERSC, users specify a qos rather than a partition and Slurm chooses a partition for a job based on the combination of several options. A sys admin at our site suggested using `srun --test-only` to see which partition Slurm would chose for a job with a given set of options.
> [bugfix] Let Slurm decide partition in flexible node allocation if no default partition is defined

- reframe/core/decorators.py
The rationale behind this is that skipping tests during initialization could be part of a parameterization pruning process. The skip message is printed in verbose mode now.
Closes #3284.
> [enhancement] Do not issue warning when skipping tests during the init phase

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/slurm.py
This PR is an implementation of the suggestions in #3216 to better handle reserved nodes in Slurm when guessing the number of nodes/tasks to use with`--flex-node-alloc`:
* include `RESERVED` as an "avail" state for Slurm nodes (and filter out reserved nodes when no reservation is specified).
* allow a node to be in any combination of the "avail" states
I also added a few log statements that were helpful to me while testing this interactively and cleaned up a few typos in nearby code.
Closes #3216.
> [bugfix] Allow RESERVED nodes for Slurm "avail" state

- .github/workflows/main.yml
- setup.cfg
I converted several Github workflows to test on multiple Python versions.
> [ci] Enable Python 3.13 in CI + expand Github test workflows

- reframe/core/config.py
- reframe/core/exceptions.py
- reframe/frontend/autodetect.py
- reframe/frontend/reporting/__init__.py
- unittests/resources/config/settings.py
We modify our core code for chaining exception message to only print the `message` of the validation error and not its verbose string representation. This is now printed in debug mode at the error site.
Closes #3168.
> [enhancement] Issue a more compact message when JSON schema validation fails

- reframe/frontend/executors/__init__.py
- reframe/frontend/filters.py
- unittests/test_filters.py
Instead of failing the whole filtering process and issuing a hard error, we now issue a warning and the test is skipped. Example output:
```console
WARNING: error while evaluating expression `num_nodes > 1` for test case `TestX @generic:default+builtin`: name 'num_nodes' is not defined
```
> [enhancement] Warn instead of failing when a filter expression is invalid for test

- docs/manpage.rst
- docs/tutorial.rst
- reframe/frontend/cli.py
- reframe/frontend/printer.py
- reframe/frontend/reporting/__init__.py
- reframe/schemas/config.json
- unittests/test_cli.py
We reduce again the options to `csv`, `plain` and `pretty` as it was originally, but now `pretty` is the former  `grid` that can handle multi-line cells and `plain` is a single line output per row, so that it can be easily grep-ed.
> [enhancement] Update `--table-format` arguments

- reframe/core/decorators.py
- reframe/core/fixtures.py
- reframe/core/parameters.py
- unittests/test_fixtures.py
- unittests/test_parameters.py
This PR is to improve the error reporting when skipping tests or reporting ReframeSyntaxErrors.
- Tests skipped because of undefined parameters now print information regarding the undefined parameters.
Closes #3254
> [enhancement] Report the undefined parameters if an instantiation of an abstract test or fixture is attempted

- docs/config_reference.rst
- reframe/core/pipeline.py
- reframe/core/runtime.py
- unittests/test_pipeline.py
We do this already for partition resources but I think it makes sense to do it for extras as sometimes a test cares that an extra is defined so as to take its value rather than constrain the test to a specific value, such as `%key=val`.
> [feat] Allow partition/environment extras to be used also as feature constraints in `valid_systems` and `valid_prog_environs`

- docs/config_reference.rst
- reframe/frontend/autodetect.py
- reframe/schemas/config.json
This was the only place (excluding the module systems backends) where access to an environment variable (`$HOME`) was hardcoded. Now this configurable and assigned a default value.
Closes #3091.
> [feat] Make directory prefix for topology files configurable

- docs/tutorial.rst
Since #3313, the tip is unnecessary. Currently the results' storage is disabled by default.
> [doc] Remove tip for disabling storage results from documentation

- docs/index.rst
It also adds the recent intro talk given at CINECA last June.
This is how the new list looks like:
> [doc] Update formatting of list of talks in the documentation

- reframe/frontend/loader.py
- unittests/resources/checks_unlisted/testlib/nested/dummy.py
- unittests/resources/checks_unlisted/testlib/simple.py
- unittests/test_cli.py
- unittests/test_loader.py
This is practically a follow up of #3110 by fixing relative imports of deeply nested tests. Currently, given the following structure:
```console
unittests/resources/checks_unlisted/testlib/
├── __init__.py
├── nested
│   ├── __init__.py
│   └── dummy.py
├── simple.py
└── utility
└── __init__.py
```
the following import in  `nested/dummy.py` will crash:
```python
from ..utility import dummy_fixture
```
> [bugfix] Fix relative imports in deeply nested tests

- docs/manpage.rst
- reframe/frontend/testgenerators.py
- unittests/test_testgenerators.py
The problem with `$` is two-fold: it has a special meaning both for shells and for the regex pattern, so it makes it tricky to select a generated test's name with `-n`.
> [enhancement] Prefix special (generated) parameters with `.` instead of `$`

- reframe/utility/__init__.py
- unittests/test_utility.py
> [bugfix] Fix nodelist abbreviation when last node number is a multiple of 10

- reframe/core/schedulers/slurm.py
When converting the constraint expression to a Python one we replace hyphens in constraints and node features with `_` and then evaluate the validity.
Ideally, we would need to properly support the Slurm constraint syntax, but that would an enhancements on its own.
Closes #3325.
> [bugfix] Treat correctly Slurm constrains with hyphens when filtering nodes

- reframe/frontend/cli.py
- unittests/test_cli.py
Also if `--reruns` or `--duration` is used, then failures are accounted from all runs.
Closes #3324.
> [bugfix] Exit successfully if `--duration` limit is reached

- docs/config_reference.rst
- reframe/core/logging.py
Also:
- Make consistent the use of `placeholder`, `log attribute` and `specifier` in the docs
Closes #3345.
> [feat] Introduce `%(hostname)s` log format placeholder

- .github/workflows/main.yml
GH actions move Ubuntu latest to 24.04 where Python 3.7 is not available. So I am creating a new GH action for that, exactly as we do for Python 3.6. 
For `docvalidation` and `wheelvalidation` I'm simply removing Python 3.7.
> [ci] Update GH actions for Python 3.7 after the move of runners to Ubuntu 24.04

- reframe/core/pipeline.py
- reframe/frontend/printer.py
In case of a single failing performance variable the output doesn't change. If multiple are failing, this are listed in separate lines as follows:
```
* Reason: performance error: failed to meet references:
bw1=92 GB/s, expected 190 (l=180.5, u=199.5)
bw2=58 GB/s, expected 190 (l=184.3, u=195.7)
bw3=92 GB/s, expected 190 (l=186.2, u=193.8)
```
> [enhancement] Report all failed performance variables in `FAILURE INFO`

- reframe/core/schedulers/slurm.py
A node is put in `PLANNED` state by the backfill plugin. Currently, ReFrame will treat such node as unavailable causing it to cancel a pending job requesting such node if `RFM_IGNORE_REQNODENOTAVAIL` is not set (default).
Related to #303 and #1049.
> [bugfix] Treat a node in `PLANNED` Slurm state as available

- docs/config_reference.rst
- reframe/core/logging.py
- reframe/frontend/executors/__init__.py
- reframe/schemas/config.json
Reopening https://github.com/reframe-hpc/reframe/pull/3354 on a branch based on master.
Fixes https://github.com/reframe-hpc/reframe/issues/3353 .
> [bugfix] Check response status in the `httpjson` log handler and retry in case of `TOO_MANY_REQUESTS`

- reframe/schemas/config.json
> [bugfix] Add missing `topology_prefix` option in the configuration schema

- reframe/frontend/executors/policies.py
`dump_pipeline_progress` is in within the `general` part of the configuration
> [bugfix] Fix use of `dump_pipeline_progress` and `RFM_DUMP_PIPELINE_PROGRESS` options

- docs/config_reference.rst
Fix default value for results storage
Following #3313 the results storage is now disabled by default.
> [doc] Fix default value for results storage in documentation

- reframe/utility/osext.py
This fixes the unit test failures on MacOS for Python 3.7/3.8 which we occasionally see in the CI.
> [bugfix] Make `getsid()` call persistent in `_ProcFuture.start()`

- reframe/frontend/executors/policies.py
Now output is the following:
```console
[     SKIP ] (1/3) SkipTest /dbb6b33c @generic:default+builtin [unsupported]
[       OK ] (2/3) CompileOnlyHelloTest /ecfc0900 @generic:default+builtin
[     SKIP ] (3/3) HelloTest /2b3e4546 @generic:default+builtin [could not satisfy the minimum task requirement: required 2, found 1]
```
Closes #3351.
> [bugfix] Include test info when skipping tests

- docs/tutorial.rst
> [doc] Fix tutorial on `--performance-report` default behaviour

- reframe/frontend/cli.py
- unittests/resources/config/settings.py
- unittests/test_cli.py
- unittests/test_config.py
We now expand environment variables once we resolve the execution mode and do not wait for a later expansion during the resolution of the various configuration parameters.
Closes #3306.
> [bugfix] Properly expand environment variables in execution modes

- docs/manpage.rst
- reframe/core/pipeline.py
- unittests/test_cli.py
There was a more general problem with `--dont-restage` apart from trying to re-issue a `git clone` command if `sourcesdir` was a url. Even if it wasn't, it would still copy the contents of the `sourcesdir` to stagedir. Now we neither copy nor clone if `--dont-restage` is passed. 
However, since we now disallow a copy if `--dont-restage` is passed, that would mean that `--dont-restage` would cause a test to fail if it was run for the first time with `--dont-restage` as its resources wouldn't be copied. To overcome this, each test now write a mark in the stage directory. Before copying the resources to the stage directory, it checks if the mark exists. If it does, it means that there has been a previous run and that the stagedir contents haven't been wiped out, which means `--dont-restage` …
> [bugfix] Do not copy or `git clone` `sourcesdir` if `--dont-restage` is passed

- .github/workflows/main.yml
The `dist/ReFrame_HPC*.whl` pattern is no longer valid due to https://github.com/pypa/setuptools/pull/4766 which was incorporated in setuptools 75.8.1.
> [ci] Fix wheel file pattern in the wheel validation Github action

- .github/workflows/main.yml
- ci-scripts/dockerfiles/reframe-python.dockerfile
> [ci] Add GH action to test older python versions

- docs/config_reference.rst
- reframe/core/schedulers/slurm.py
- reframe/schemas/config.json
- unittests/test_config.py
Closes #3415 
For me it's useful to have the failure logged as a warning, so that people would be aware that the system is not stable. Now the output looks like this when it happens:
```
[ RUN      ] PyTorch...
[S] slurm: sacct failed with error: sacct: error: _open_persist_conn: failed to open persistent connection to host:beverin-slurmctl.tds.cscs.ch:6819: Connection timed out
sacct: error: Sending PersistInit msg: Connection timed out
sacct: error: Problem talking to the database: Connection timed out
: have tried 1 time(s)
[       OK ] (27/42) ...
```
> Make ReFrame more resilient to `sacct` temporary errors

- reframe/core/pipeline.py
> [doc] Add warning about combining `build_locally=0` and scheduler backends that cannot reliably retrieve the job's exit code

- reframe/frontend/cli.py
Now output is
```console
┍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━━┯━━━━━━━┯━━━━━━━┑
│ UUID                                 │ Start time           │ End time             │ Num runs   │ Num cases   │ x     │ y     │
┝━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━┿━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━┥
│ 6c27c7c0-725a-4f9b-9449-6b91cda3dc91 │ 20250313T221426+0100 │ 20250313T221427+0100 │ 1          │ 1           │ 12.30 │ 12.31 │
┕━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━┷━━━━━━━━━━━━━┷━━━━━━━┷━━━━━━━┙
```
Fixes #3404.
> [bugfix] Disable number parsing when in `--list-stored-sessions`

- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
> [bugfix] Fix calculation of lower/upper reference bounds when their absolute value reaches zero

- reframe/core/pipeline.py
- reframe/utility/sanity.py
- unittests/test_sanity_functions.py
Partially addresses #2857.
The spirit of #2857 is for fully supporting both relative and absolute value reference thresholds. That's not what's provided here. Rather, this PR specifically supports the case for reference values of 0. When a reference value of 0 is provided, lower and upper thresholds are treated as absolute values.
> [feat] Support reference values of zero

- reframe/core/decorators.py
- unittests/test_testgenerators.py
Although the parameterized tests were instantiated in the order they appear in the test file and in the order of their parameter list, they were listed in reverse order, which was annoying, although technically not a bug (the default listing is implementation-defined).
The problem was that we were iterating over them in reverse order in order to instantiate any fixtures, so the final list of tests was reverted. This is fixed by using a `deque` list and popping from the left side.
> [enhancement] List parameterized tests in their instantiation order

- docs/manpage.rst
- reframe/frontend/reporting/__init__.py
- unittests/test_cli.py
When doing performance comparisons (`--performance-compare` or `--performance-report`), users can now explicitly select the A or B variant for extra columns, e.g., `+result_A` will only list the aggregated results of the first set.
Closes #3341.
> [feat] Support selecting A/B column variants in performance comparisons

- docs/config_reference.rst
- docs/manpage.rst
- reframe/frontend/argparse.py
- reframe/frontend/cli.py
- unittests/test_argparser.py
Execution modes are not allowed to use command/action options. This was never the intent of execution modes and since 4.7, since `--mode` is not a command option, it was required to pass one in the command line. If the mode had already a command option, then which of the two would take effect was implementation defined. This PR disallows completely the use of command options in execution modes to avoid such abmiguities.
Closes #3424.
> [bugfix] Disallow command options from execution modes

- reframe/core/containers.py
- reframe/core/pipeline.py
- unittests/test_containers.py
- unittests/test_pipeline.py
This introduces a new `mount_stagedir` variable that controls the mount point of the stagedir. If `None`, the stagedir will not be mounted.
This PR also refactors the `ContainerPlatform` so as to use the builtin variables instead of the raw fields.
Closes #3367.
> [feat] Allow changing the default mount location of stagedir inside containers

- reframe/core/pipeline.py
The `name` test property was not updated when the special parameter character was changed from `$` to `.` in #3330.
> [bugfix] Update special parameter character in test name

- reframe/core/pipeline.py
- reframe/core/schedulers/pbs.py
- unittests/test_schedulers.py
Users can then specify it manually through `self.job.options`.
Closes #3315.
> [feat] Do not emit the `-lselect` option if `num_tasks=None`

- reframe/frontend/reporting/storage.py
We should acquire the file lock before attempting to connect to the database as we do for session removal already. This way we avoid connection timeouts when there are multiple writers.
> [bugfix] Fix lock order when storing reports to the database

- docs/manpage.rst
- reframe/utility/typecheck.py
- unittests/test_typecheck.py
This solves the issue when the default `,` separator is not sufficient to separate the list elements as well as allows for nested list assignments.
Closes #3264.
> [feat] Support list assignment from JSON using the `-S` option

- README.md
- README_minimal.md
- docs/index.rst
> [doc] Add a note about results storage and analytics in README

- reframe/core/schedulers/slurm.py
Features starting with a number (e.g. `4xA40`) seem valid to slurm, but are not valid python identifiers. Currently this causes nodes getting filtered out when such feature is used as constraints. ~~This prefixes all variables during eval with underscore to get around it.~~ 
Edit: this now inserts boolean values directly into the constraints to support such Slurm features.
> [bugfix] Fix constraint evaluation for Slurm features starting with numbers

- reframe/frontend/printer.py
This PR tries to address the following error when using the `--failure-stats` command line option
```
ERROR: run session stopped: type error: unsupported format string passed to NoneType.__format__
ERROR: Traceback (most recent call last):
File "/hpcdc/project/scilib/libsci_acc/csml-libsci-acc-testing/python-libs/x86_64/python3.11/site-packages/reframe/frontend/cli.py", line 1654, in main
printer.failure_stats(
File "/hpcdc/project/scilib/libsci_acc/csml-libsci-acc-testing/python-libs/x86_64/python3.11/site-packages/reframe/frontend/printer.py", line 227, in failure_stats
stats_body.append(row_format.format(p, len(l), l[0]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```
The problem is that successful tests are stored with …
> [bugfix] Treat correctly `failed_stage=None` in failure stats report

- reframe/frontend/autodetect.py
> [bugfix] Handle explicit scheduler options passed in the CLI in the remote auto-detection script

- docs/config_reference.rst
- reframe/core/schedulers/slurm.py
- unittests/test_environments.py
> [bugfix] Unset all `SBATCH_*` environment variables before submitting a job

- docs/requirements.txt
- reframe/utility/__init__.py
- requirements.txt
- setup.cfg
- unittests/test_utility.py
> [enhancement] Use `ClusterShell` to manipulate node lists instead of our own code

- reframe/frontend/reporting/__init__.py
> [bugfix] Use always `|` to join unique values in column aggregations except for `--table-format=pretty`

- bootstrap.sh
This is to avoid deprecation warnings from dependencies that are not yet updated (see ClusterShell):
```
DEPRECATION: Building 'ClusterShell' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'ClusterShell'. Discussion can be found at https://github.com/pypa/pip/issues/6334
```
This is a follow up from #3470.
> [enhancement] Use the `--use-pep517` option in `bootstrap.sh`

- docs/config_reference.rst
- reframe/core/launchers/__init__.py
- reframe/core/launchers/mpi.py
- unittests/test_launchers.py
Support for environment variable forwarding is added to the `srun` launcher, as well as two new launchers `mpirun-openmpi` and `mpirun-intelmpi`.
Closes #3207.
References: 
* [`srun --export`](https://slurm.schedmd.com/srun.html#OPT_export)
* [IntelMPI mpirun (hydra) options](https://www.intel.com/content/www/us/en/docs/mpi-library/developer-reference-linux/2021-15/global-hydra-options.html), see `-genv`
* [OpenMPI `mpirun -x`](https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man1/mpirun.1.html#the-x-option)
> [feat] Enable launchers to forward environment variables

- docs/manpage.rst
- reframe/core/exceptions.py
- reframe/frontend/cli.py
- reframe/frontend/executors/__init__.py
- reframe/frontend/executors/policies.py
- reframe/frontend/printer.py
- reframe/frontend/reporting/__init__.py
- unittests/test_cli.py
- unittests/test_policies.py
When a test's dependencies fail, the test is now simply skipped and is put in a special state `fail_deps`. This is needed to be able to differentiate the tests that have been skipped due to failed dependencies in order to retry them in case of `--max-retries` or restore them with `--restore-session --failed`.
Closes #3480.
> [enhancement] Skip tests if their dependencies fail

- .github/pseudo-cluster/reframe/docker-entrypoint.sh
- .github/workflows/main.yml
- .github/workflows/test-flux.yaml
- .github/workflows/test-schedulers.yaml
- ci-scripts/dockerfiles/reframe-lmod.dockerfile
- ci-scripts/dockerfiles/reframe-lmod77.dockerfile
- ci-scripts/dockerfiles/reframe-python.dockerfile
- ci-scripts/dockerfiles/reframe-tmod32.dockerfile
- ci-scripts/dockerfiles/reframe-tmod4.dockerfile
- reframe/__init__.py
We now run coverage with all unit tests from all pipelines, so we now have the full coverage of the project
Closes #3024.
> [ci] Re-enable codecov in the project

- reframe/frontend/cli.py
This means that spaces are not allowed when selecting test names with parameters as is the case with normal test filtering. E.g., 
```
reframe -n MyTest%param=1 -l
reframe --list-stored-testcases=now-1d:now/mean:/ -n MyTest%param=1
reframe --list-stored-testcases=now-1d:now/mean:/ -n 'MyTest %param=1'
```
Closes #3503.
> [bugfix] Make `-n` option syntax consistent across test filtering and results storage queries

- reframe/core/schedulers/__init__.py
- reframe/core/schedulers/flux.py
- reframe/core/schedulers/local.py
- reframe/core/schedulers/lsf.py
- reframe/core/schedulers/pbs.py
- reframe/core/schedulers/sge.py
- reframe/core/schedulers/slurm.py
- reframe/core/schedulers/ssh.py
- reframe/frontend/executors/__init__.py
- unittests/resources/checks/src/sleep_deeply.sh
- unittests/test_schedulers.py
- unittests/test_shell.py
This PR fixes a race condition in the local scheduler when the submitted job times out. The problem was that the scheduler assumed that the job has finished before it has actually finished, therefore allowing the execution policies to submit further jobs. The problem was due to how we were checking that a job has finished in the local scheduler. This had multiple problems, one of them affecting all scheduler backends:
1. The scheduler's `Job.finished()` method checks if an exception is associated with the job and immediately raises it before even ensuring that the job has actually finished. This has multiple problems, one of which is the race condition above, but also leaving behind zombie processes. Now the `JobScheduler.finished()` method only checks whether the job has finished or not …
> [bugfix] Fix race condition in local scheduler during timeout and properly reap done processes

- reframe/frontend/executors/__init__.py
Although we log the filtering of test cases by the various criteria, we don't log their generation and this can render difficult debugging errors in `valid_systems` and/or `valid_prog_environs`, where no test cases are generated. This PR logs this test case generation in more detail, so that debugging of such scenarios can be facilitated.
> Improve logging of test case generation

- reframe/frontend/printer.py
- unittests/test_cli.py
I've added also a unit test that reproduces the original error.
Closes #3526.
> [bugfix] Fix failure report crash in case of expected failures

- reframe/core/logging.py
- reframe/frontend/cli.py
- reframe/frontend/reporting/storage.py
We essentially increase the log level to WARNING for all non-stream handlers while printing DB records.
Closes #3519.
> [bugfix] Disable file logging when emitting DB records

- reframe/frontend/cli.py
Currently, all the loggable properties are skipped. This PR fixes this by showing all loggable attributes and therefore any loggable properties. This is the same information that is also logged in the report.
> [enhancement] Show more test attributes with `--describe`

- docs/regression_test_api.rst
> [doc] Add some notes and tips in the documentation of pipeline hooks

- reframe/core/pipeline.py
- unittests/test_cli.py
> [bugfix] Do not wipe the output dir of a test if run with `--dry-run`

- docs/manpage.rst
- reframe/core/parameters.py
- reframe/frontend/testgenerators.py
- unittests/test_testgenerators.py
To achieve this we add type information to parameters, so that the user-supplied arguments can be correctly converted by the test. The change is seamless, as by default no type information is required for parameters, but if users want to re-parameterize a test, then the parameters must have a type.
Closes #2674.
> [feat] Allow the `-P` option to redefine existing parameters
