Jenkinsfile
=> Parse Github comments to trigger the CI on specific machines

ci-scripts/ci-runner.bash, config/generic.py
This caused frontend to crash immediately.
A CI test is also added to guard against future regressions.
Fixes #88.
=> Fix logging config in generic settings

Jenkinsfile
=> CI: use machinesToRun in the "cleanup stale" phase

reframe/core/schedulers/__init__.py, unittests/test_launchers.py, unittests/test_schedulers.py
* Make minimal unittest changes to reflect the change
in the job name.
Closes #122
=> Add prefix 'rfm_' to the given job name

reframe/core/schedulers/slurm.py, unittests/test_schedulers.py
Also added the associated unit tests to avoid future regressions.
Fixes #127.
=> Fix emission of Slurm's --exclusive flag

README.md, docs/advanced.rst, reframe/core/pipeline.py, reframe/core/schedulers/__init__.py, reframe/core/schedulers/local.py, reframe/core/schedulers/slurm.py, reframe/settings.py, tutorial/advanced/advanced_example7.py, tutorial/advanced/src/advanced_example6.sh, tutorial/advanced/src/random_numbers.sh, tutorial/advanced/src/scripts/limits.sh, unittests/test_launchers.py, unittests/test_pipeline.py
This PR also adds a tutorial example for using `pre_run` and `post_run`.
Fixes #91.
Fixes #35.
=> Submit jobs from the stage directory

unittests/resources/frontend_checks.py
=> Fix occasional unit test failure in async policy.

cscs-checks/apps/icon/rrtmgp_check.py
=> Add ICON RRTMGP regression test.

Jenkinsfile
* Clone the repository manually.
* Checkout at the correspondint commit.
=> Fix git cloning for Leone

reframe/frontend/executors/policies.py
=> Fix confusing error messages in serial execution policy.

config/cscs.py, cscs-checks/microbenchmarks/mch/g2g_meteoswiss_check.py
* Add PrgEnv-gdr for kesch in `config/cscs.py`
* Create dir `mch` under `cscs-checks/microbenchmarks`.
Closes #93
=> Add G2G meteoswiss check

config/cscs.py
=> Reenable 'switches' resource in 'cscs' settings

docs/tutorial.rst, reframe/utility/sanity.py, unittests/test_sanity_functions.py
=> Allow upper thresholds >= 1.0 in 'assert_reference'

cscs-checks/apps/tensorflow/tensorflow_check.py
* Add `mnist` and `wide_deep` official model tests for TensorFlow.
Closes #103
=> Add check for TensorFlow

reframe/frontend/cli.py
=> Expand environment variables in the -c option

cscs-checks/microbenchmarks/mpi/src/mpi_helloworld.c
As soon as this is merged the ReFrame test must be adapted accordingly.
=> Better implementation of the sample program

cscs-checks/apps/amber/amber_check.py, cscs-checks/apps/namd/namd_check.py, cscs-checks/libraries/magma/magma_checks.py
=> Separate maintenance and production checks

reframe/utility/versioning.py, unittests/test_versioning.py
=> Implement a versioning abstraction and the corresponding unit tests

cscs-checks/apps/amber/amber_check.py
=> Add numerical sanity check in Amber test

cscs-checks/apps/cpmd/cpmd_check.py
=> Check numerical sanity in CPMD test

cscs-checks/apps/namd/namd_check.py
=> Check numerical sanity in NAMD test

reframe/core/environments.py, reframe/core/modules.py, unittests/test_modules.py
=> Fix job script generation to take into account module mappings

cscs-checks/apps/namd/namd_check.py
=> Add namd cpu to production

cscs-checks/apps/namd/namd_check.py
* Fix assignment of `self.num_tasks` by moving it to base class.
* Move common assignment of fields to base class.
=> Fix assignment of num_tasks

unittests/resources/frontend_checks.py, unittests/test_cli.py, unittests/test_loader.py, unittests/test_policies.py
=> Fix silent crash of unit tests introduced by #266

docs/running.rst, reframe/core/pipeline.py
Also:
- Update listings in documentation.
Fixes #292.
=> Fix filename printing in test listing

cscs-checks/microbenchmarks/osu/flexible_a2a.py
=> Add flexible A2A check

reframe/core/schedulers/slurm.py
* Handle the above case which means that the job is pending.
* Minor codestyle fix.
Fixes #303
=> More reliable check for jobs pending indefinitely

reframe/utility/__init__.py, reframe/utility/sanity.py
- Rationale on special treatment of generators in allx.
- Document the sanity function correctly.
- Correct line splits.
=> Code organisation fixes

cscs-checks/prgenv/gpu_direct_acc.py, cscs-checks/prgenv/gpu_direct_cuda.py
- Set `LD_PRELOAD` as a `pre_run` command.
=> Fix failures of GPU direct tests on Kesch

config/cscs-pbs.py, config/cscs.py
=> [bugfix] Change the resources dir path

cscs-checks/tools/profiling_and_debugging/notool.py
=> [test] Adapt notools check to build systems

reframe/frontend/cli.py
=> [feat] List only the checks that are supported on the current system

cscs-checks/libraries/math/scalapack_compile_run.py
=> [test] Remove `PrgEnv-gnu` support from the Scalapack test on Kesch

cscs-checks/apps/lammps/lammps_check.py
Fixes https://github.com/eth-cscs/reframe-tests/issues/31
=> [test] Adjust LAMMPS performance values

cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
* Adapt the module names to reflect the latest PE, 18.08.
=> [test] Adapt Score-P modules to PE 18.08

cscs-checks/mch/cuda_stress_test.py, cscs-checks/mch/src/cuda_stencil_test.cu
=> [test] Add MCH CUDA stress test

cscs-checks/libraries/io/netcdf_compile_run.py
Practically, I removed static compilation for PGI on Kesch.
=> [test] Fix NetCDF test on Kesch

reframe/frontend/executors/policies.py, unittests/resources/checks/frontend_checks.py, unittests/test_policies.py
=> [bugfix] Do not silently abort tasks in hold when all currently running tasks fail

cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py, cscs-checks/microbenchmarks/gpu_burn/src/gpu_burn.cu
* Adapt the gpu burn test to run also for multi-gpu nodes.
* Make the source code available and move to the public repository.
Closes #546
=> [test] Adapt the GPU burn test for multi-gpu nodes

cscs-checks/libraries/magma/magma_checks.py
Fixes https://github.com/eth-cscs/reframe-tests/issues/37
=> [test] Update MAGMA tests

cscs-checks/prgenv/cpu_target_check.py
=> [test] Add test checking if CRAY_CPU_TARGET is set

cscs-checks/apps/gromacs/gromacs_check.py
Modifications due to Jenkins tests failing on DOM.
=> [test] Update GROMACS  test for Dom

reframe/utility/sanity.py, unittests/test_sanity_functions.py
* Add the corresponding unit tests.
Closes #556
=> [feat] Add a new `count_uniq()` sanity function

ci-scripts/deploy.sh
=> [ci] Use integer comparison for ReFrame versions in deployment script

cscs-checks/mch/automatic_arrays.py, cscs-checks/mch/check_ruby.py, cscs-checks/mch/collectives_halo.py, cscs-checks/mch/cuda_stress_test.py, cscs-checks/mch/g2g_meteoswiss_check.py, cscs-checks/mch/gpu_direct_acc.py, cscs-checks/mch/gpu_direct_cuda.py, cscs-checks/mch/openacc_cuda_mpi_cppstd.py, cscs-checks/tools/io/cdo.py, cscs-checks/tools/io/nco.py, reframe/__init__.py
Also:
- Remove `kesch:cn` from CDO/NCO tests
=> [test] Add specific tag for MCH tests

cscs-checks/mch/collectives_halo.py
=> [test] Make Alltoallv tests non-strict

config/cscs.py, cscs-checks/tools/io/cdo.py, cscs-checks/tools/io/nco.py
=> [test] Enable NCO and CDO for the C2SM-RCM environments

reframe/core/schedulers/slurm.py
=> [bugfix] Fix bug in variable names in Slurm backend

Jenkinsfile
=> [ci] Add option to disable CSCS CI tests

unittests/test_pipeline.py
* Rename `self.keepfiles` to `self.keep_files`.
=> [bugfix] Fix bug in 'keep_files' unit tests

cscs-checks/tools/profiling_and_debugging/intel_vtune.py
https://jira.cscs.ch/browse/UES-271
=> [test] Add Intel Vtune test

cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
https://jira.cscs.ch/browse/UES-307
=> [test] Add gperftools parallel test

cscs-checks/tools/profiling_and_debugging/mpip.py, cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py, cscs-checks/tools/profiling_and_debugging/src/C++/Makefile
https://jira.cscs.ch/browse/UES-310
=> [test] Add mpiP parallel test

cscs-checks/apps/amber/amber_check.py, cscs-checks/apps/cp2k/cp2k_check.py, cscs-checks/apps/cpmd/cpmd_check.py, cscs-checks/apps/espresso/espresso_check.py, cscs-checks/apps/gromacs/gromacs_check.py, cscs-checks/apps/lammps/lammps_check.py, cscs-checks/apps/namd/namd_check.py, cscs-checks/apps/tensorflow/tf_horovod_check.py, cscs-checks/microbenchmarks/osu/osu_tests.py
- Several tests were also refactored.
Fixes: https://jira.cscs.ch/browse/UES-314
=> [test] Enable small scale application tests also on Daint

cscs-checks/tools/profiling_and_debugging/gdb4hpc.py, cscs-checks/tools/profiling_and_debugging/src/C++/gdb4hpc.in
Fixes https://jira.cscs.ch/browse/UES-338
=> [bugfix] Fix gdb4hpc failure with C++

ci-scripts/deploy.sh
- Relax requirement for Python version. Since we are not building the documentation anymore, any Python >= 3.5 is ok.
=> [ci] Update deployment script

cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
Fixes https://jira.cscs.ch/browse/MAINT-54
=> [bugfix] Force units in gperftools report

cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Will fix https://jira.cscs.ch/browse/MAINT-70
=> [test] Update IPM check for PE/19.03

cscs-checks/tools/profiling_and_debugging/ddt.py
Will fix https://jira.cscs.ch/browse/MAINT-19
=> [test] Fix ddt+cuda/10.0 check 

cscs-checks/tools/profiling_and_debugging/intel_sde_berkeley_stream.py, cscs-checks/tools/profiling_and_debugging/intel_sde_roofline.py
Will fix https://jira.cscs.ch/browse/UES-213 (partially)
=> [test] Add sde roofline check

config/cscs.py
Will fix https://jira.cscs.ch/browse/UES-288
=> [ci] Add Ault TDS to the config file

docs/advanced.rst, docs/tutorial.rst, reframe/core/schedulers/__init__.py, reframe/core/schedulers/pbs.py, unittests/test_launchers.py, unittests/test_policies.py
=> [feat] Do not use absolute paths in generated batch scripts

cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Will fix https://jira.cscs.ch/browse/MAINT-75
=> [test] Hardcode version in Intel Vtune test to prevent failure when default changes

reframe/core/exceptions.py
=> [bugfix] Fix filename order in build error message

config/cscs.py
Will fix [395](https://jira.cscs.ch/browse/UES-395)
=> [config] Fix configuration for Ault

cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
Addresses [UES-339](https://jira.cscs.ch/browse/UES-339)
=> [test] Make alloc_speed check generic

cscs-checks/microbenchmarks/mpi/halo_cell_exchange.py
=> [test] Make `HaloCellExchangeTest` generic

cscs-checks/tools/profiling_and_debugging/notool.py
=> [test] Make the Jacobi check generic

config/cscs.py
=> [config] Add configuration for Tave

cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
=> [test] Make GPU burn test generic

cscs-checks/microbenchmarks/shmem/shmem.py
Also:
- Fix reference thresholds
- Remove irrelevant test variants
Fixes UES-405.
=> [test] Make GPU shared memory bandwidth test generic

cscs-checks/microbenchmarks/dgemm/dgemm.py
=> [test] Make DGEMM test generic

cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Only the basic test is converted to a generic one. The other two are already quite specific.
Fixes UES-404.
=> [test] Make HPCG basic test generic

cscs-checks/system/slurm/slurm.py
Recent Slurm have changed the message when a job is OOM killed.
Fixes MAINT-78.
=> [test] Fix MemoryOverconsumptionCheck message check

cscs-checks/libraries/math/trilinos_compile_run.py
* Enable dynamic tests.
* Update test for cdt/19.06
=> [test] Enable dynamic linking tests for Trilinos

config/cscs.py, cscs-checks/compile/haswell_fma_check.py
* Test also for PrgEnv-cray_classic.
=> [test] Adapt Haswell FMA check for CCE 9.0.x

config/cscs-ci.py, config/cscs.py
Also:
- Simplify CI site config settings
CI settings should be very simple. Unit tests need just a single programming environment and a single partition to submit jobs to.
=> [ci] Re-enable PGI on GPU/MC partitions on Dom

cscs-checks/tools/profiling_and_debugging/intel_inspector.py
Will fix [484](https://jira.cscs.ch/browse/UES-484)
=> [test] inspector

cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Will fix [485](https://jira.cscs.ch/browse/UES-485)
=> [test] Update Intel VTune test

cscs-checks/apps/cp2k/cp2k_check.py
Update of the reference value on Dom using the multicore: see https://jira.cscs.ch/browse/MAINT-82
=> [test] Update reference for CP2K cpu check small

reframe/frontend/cli.py
=> [feat] Print debug info when preload environment fails to load

setup.py
* Remove Slack badge from the description in `setup.py`.
=> [deploy] Fix project description in setup of PyPI package

cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py, cscs-checks/microbenchmarks/kernel_latency/src/kernel_latency.cu
* Add PrgEnv-cray_classic in programming environments
=> [test] Increase iterations for async kernel latency test

cscs-checks/tools/profiling_and_debugging/intel_inspector.py
I couldn't cherry pick the commits, because they were spread over multiple PRs, so I just copied the file that is currently on master.
=> [bugfix] Back port Intel Inspector test

config/cscs.py, cscs-checks/system/io/ior_check.py, cscs-checks/tools/profiling_and_debugging/intel_vtune.py
This PR also back ports the configuration.
Fixes UES-536
=> [test] Back port Intel VTune and IOR tests to 2.17

cscs-checks/cuda/cuda_checks.py, cscs-checks/microbenchmarks/osu/osu_tests.py, cscs-checks/tools/profiling_and_debugging/cuda_gdb.py, cscs-checks/tools/profiling_and_debugging/ddt.py, cscs-checks/tools/profiling_and_debugging/nvprof.py
Fixing cuda checks as #924 was intending to do. Currently the checks are failing on Kesch:
https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-kesch-production-daily/detail/reframe-kesch-production-daily/180/pipeline/
=> [test] Fix cuda checks on Kesch

unittests/test_pipeline.py
=> [bugfix] Fix unit tests leaving stale files behind

cscs-checks/system/openstack/s3_check.py, cscs-checks/system/openstack/src/s3_create_bucket.py, cscs-checks/system/openstack/src/s3_create_small_object.py, cscs-checks/system/openstack/src/s3_delete.py, cscs-checks/system/openstack/src/s3_download_large_object.py, cscs-checks/system/openstack/src/s3_test.sh, cscs-checks/system/openstack/src/s3_upload_large_object.py, cscs-checks/system/openstack/src/tools.py
First version for openstack swift s3 tests
=> [test] Add OpenStack SWIFT S3 tests

cscs-checks/microbenchmarks/simd/nsimd.py, cscs-checks/microbenchmarks/simd/vc.py
will fix https://jira.cscs.ch/browse/MAINT-179 and https://jira.cscs.ch/browse/MAINT-180
=> [test] Remove tags from nsimd checks

ci-scripts/ci-runner.bash, cscs-checks/apps/paraview/paraview_check.py, cscs-checks/apps/paraview/src/coloredSphere.py
=> [test] Backport Paraview check to 2.17

cscs-checks/mch/gpu_direct_cuda.py
Will fix UES-580
Changes needed to run on tiger, is there a better way to do it ?
=> [test] Port GPUDirect check to Tiger

cscs-checks/libraries/io/netcdf_compile_run.py
=> [test] Port NETCDF check to Tiger

cscs-checks/mch/collectives_halo.py
=> [test] Port collectives halo exchange check to Tiger

cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
=> [test] Port GPUBURN check to Tiger

cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
=> [test] Port KERNEL_LATENCY check to Tiger

cscs-checks/microbenchmarks/fft/fftw_benchmark.py
=> [test] Port FFTW check to Tiger

cscs-checks/microbenchmarks/shmem/shmem.py
=> [test] Port SHMEM to Tiger

cscs-checks/prgenv/cpu_target_check.py, cscs-checks/prgenv/ssh_environ_check.py
=> [test] Port CPUTARGET check to Tiger

cscs-checks/mch/gpu_direct_cuda.py
=> [test] Port GPUDIRECTCUDA check to Tiger

cscs-checks/mch/openacc_cuda_mpi_cppstd.py
=> [test] Port OPENACCCUDACPP to Tiger

cscs-checks/microbenchmarks/dgemm/dgemm.py
=> [test] Port DGEMM check to Tiger

cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
=> [test] Remove cce compiler from SCORE-P check

cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
=> [test] Add mem-per-cpu resources to ALLOC_SPEED check for Tiger

cscs-checks/microbenchmarks/osu/osu_tests.py
This check needs some change, run on tiger and push the fixes please
=> [test] Port OSU check to Tiger

cscs-checks/mch/gpu_direct_acc.py
=> [test] Port GPUDIRECTACC check to Tiger

cscs-checks/microbenchmarks/dgemm/dgemm.py
=> [test] Remove unnecessary scheduler options from the DGEMM benchmark

reframe/core/pipeline.py
=> [bugfix] Do not use login shell when submitting jobs

cscs-checks/cuda/multi_gpu.py
=> [test] Port GpuBandwidthCheck to Tiger

cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Will fix [MAINT-207](https://jira.cscs.ch/browse/MAINT-207)
=> [test] Update Intel_VTuneAmplifier

cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py, cscs-checks/tools/profiling_and_debugging/src/F90/_main.F90
Will fix [MAINT-171](https://jira.cscs.ch/browse/MAINT-171)
=> [test] Fix Scorep_mpi_omp check

cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
Will fix https://jira.cscs.ch/browse/MAINT-229
=> [test] Fix buffer decode error in MpiP check

cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
I've forward ported the updated values for Daint, too.
Fixes [MAINT-196](https://jira.cscs.ch/browse/MAINT-196).
=> [test] Update reference performance for alloc speed test

cscs-checks/libraries/gridtools/gridtools_tests.py
=> [test] Fix tags in Gridtools checks

ci-scripts/ci-runner.bash
=> Revert "[ci] Fix quotes in CI script"

cscs-checks/tools/profiling_and_debugging/intel_inspector.py, cscs-checks/tools/profiling_and_debugging/intel_vtune.py
=> [test] Update tool version for Intel tools check

cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
=> [test] Update compiler version for Mpip check

reframe/frontend/executors/__init__.py, reframe/frontend/executors/policies.py
=> [refactor] Remove obsolete environment handling code from the async execution policy

docs/index.rst
- Also minor fixes in the publications listing.
=> [doc] Add slides from SC19

config/cscs.py, cscs-checks/apps/gromacs/gromacs_check.py
Dom doesn't have multiple switches. This option makes gromacs jobs on dom wait 5 min to start.
=> [test] Remove slurm switch option from dom

docs/configure.rst
=> [doc] Stress out that hostnames are Python regexes

cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
Fixes [UES-660](https://jira.cscs.ch/browse/UES-660).
=> [test] Update AllocSpeed check for Kesch

cscs-checks/libraries/io/netcdf_compile_run.py
Fix compilation error of netCDF tests on Kesch due to missing modules. See https://jira.cscs.ch/browse/UES-663
=> [test] Fix netCDF tests for Kesch

cscs-checks/mch/collectives_halo.py
Based on changes experienced during kesch daily production runs.
See https://jira.cscs.ch/browse/UES-665 and https://jira.cscs.ch/browse/UES-664
=> [test] Adapt HaloExchangeTest/Alltoallv for Kesch

README.md, setup.py
I have also updated a bit the layout of the shields.
=> [misc] Add more shields in README

reframe/__init__.py
We will start heading to 3.0 with some changes that might break slightly compatibility to the 2.x versions.
=> [misc] Bump major version

ci-scripts/ci-runner.bash, config/cscs-ci.py
Please review and merge asap, because it's blocking other PRs.
=> [ci] Fix CI for Tsa

reframe/frontend/cli.py
=> [bugfix] Include commit hash in ReFrame version when running

setup.py
This should have been included in #1195
=> [bugfix] Fix long description in setup script

cscs-checks/microbenchmarks/simd/nsimd.py, cscs-checks/microbenchmarks/simd/vc.py
Will fix [770](https://jira.cscs.ch/browse/UES-770) and [771](https://jira.cscs.ch/browse/UES-771).
=> [test] Update Vc and nsimd tests to Cray PE/19.10

docs/advanced.rst, docs/running.rst, docs/tutorial.rst, reframe/frontend/executors/__init__.py, reframe/frontend/printer.py
The output is based on @vkarak 's comment on the issue. Patching the `status()` method seemed to me like a better solution, but it would also be easy to add `test_ok(check)`, `test_fail(check)`, `test_error(check)` calls if you think it's better after all.
Closes #1092 .
Sample output:
**Asynchronous policy**
```
Command line: ./bin/reframe -c unittests/resources/checks_unlisted/deps_complex.py -r --max-retries=2
...
[==========] Running 10 check(s)
[==========] Started on Wed Mar 25 09:14:44 2020 
[----------] started processing T0 (T0)
[ RUN      ] T0 on generic:login using builtin-gcc
[----------] finished processing T0 (T0)
[----------] started processing T4 (T4)
[ RUN      ] T4 on generic:login using builtin-gcc
[      DEP ] T4 on generic:login using builtin-gcc
[----------] finished …
```
=> [feat] Include progress report in output

cscs-checks/mch/collectives_halo.py
Based on Jira issue https://jira.cscs.ch/browse/UES-772
=> [test] Remove unnecessary tags in the HaloExchangeTest 

cscs-checks/tools/profiling_and_debugging/nvprof.py
Will fix [UES-721](https://jira.cscs.ch/browse/UES-721)
=> [test] Update nvprof test and add maintenance tag

cscs-checks/prgenv/environ_check.py
=> [test] Modernize the default programming environment check

ci-scripts/ci-runner.bash
This needs to be merged asap since it blocks other PRs.
=> [ci] Implement XALT workaround for unit tests on Dom

reframe/core/meta.py
=> [bugfix] Improve the message of the deprecation warning about pipeline methods overrides

cscs-checks/microbenchmarks/osu/osu_tests.py
=> [test] Update OSU Allreduce check

cscs-checks/microbenchmarks/osu/osu_tests.py
=> [test] Update G2G latency check

cscs-checks/apps/lammps/lammps_check.py
=> [test] Update LAMMPS test

reframe/core/config.py
=> [feat] Insert 'noqa' annotations in long lines generated by the configuration conversion tool 

docs/config_reference.rst, schemas/config.json, tutorial/config/settings.py, unittests/test_argparser.py
=> [bugfix] Disable recursive search of checks by default

reframe/frontend/cli.py
=> [feat] Print the config file loaded by ReFrame

reframe/core/meta.py
=> [bugfix] Fix AttributeError when pipeline hooks are defined in a mixin class

docs/Makefile
=> [doc] Create man pages in proper man subdirectories

cscs-checks/mch/automatic_arrays_acc.py, cscs-checks/mch/gpu_direct_acc.py, cscs-checks/mch/openacc_cuda_mpi_cppstd.py, cscs-checks/prgenv/openacc_checks.py, cscs-checks/prgenv/opencl_check.py
=> [test] PrgEnv-pgi workaround for CDT 20.06

bin/reframe, reframe/__init__.py
=> [bugfix] Normalize ReFrame path prefixes

config/cscs.py, cscs-checks/mch/gpu_direct_acc.py
=> [ci] Dynamically set the account in CSCS config

cscs-checks/libraries/io/netcdf_compile_run.py
=> [test] Workaround for NetCDF tests for CDT20.06

docs/config_reference.rst, docs/tutorial_basics.rst, reframe/schemas/config.json, tutorials/config/settings.py, unittests/test_config.py
Also tutorial is adapted.
Fixes #1391.
=> [feat] Increase default concurrency of asynchronous execution policy to 8 jobs

config/cscs-ci.py, config/cscs.py
* Hardcode singularity module to singularity/3.5.3 for dom.
=> [ci] Change modules system for Dom to TMod4

reframe/schemas/config.json, reframe/schemas/runreport.json
=> [bugfix] Fix JSON schema $id parameter

reframe/core/pipeline.py, reframe/frontend/statistics.py
=> [bugfix] Add always units in the default reference tuple

cscs-checks/system/io/ior_check.py
Scratch partition no longer available.
=> [bugfix] Remove snx1600tds from test

config/cscs.py
- Adapt the production and maintenance execution modes
Currently all reports end up in Jenkins' user home.
=> [ci] Set save location for JSON report files for CSCS

reframe/core/fields.py, reframe/core/pipeline.py, unittests/test_fields.py
=> [feat] Drop tuple syntax for timer fields

reframe/frontend/cli.py
This is fixing a formatting issue introduced by #1462.
=> [bugfix] Fix formatting of summary listing of checks

config/cscs.py, cscs-checks/apps/quantumespresso/quantumespresso_check.py, cscs-checks/compile/haswell_fma_check.py, cscs-checks/compile/libsci_acc_symlink.py, cscs-checks/compile/libsci_resolve.py, cscs-checks/libraries/boost/boost_python_check.py, cscs-checks/libraries/boost/src/Makefile
I've also simplified some tests and made others more generic.
Fixes UES-1107.
=> [test] Align tests for Daint and Dom

cscs-checks/system/slurm/cscs_usertools.py
- Remove monthly_usage test
- Change sbucheck to accounting
Fixes UES-112
=> [test] Adjust CSCS user tools test

bootstrap.sh, docs/started.rst
=> [bugfix] Fix bootstrap script for Ubuntu/Debian installation

ci-scripts/ci-runner.bash
Also:
* Remove kesch specific `module load`
EDIT: This is due to the random hangs of the unit tests on Tsa.
=> [ci] Disable parallel unit testing on tsa

reframe/core/pipeline.py, unittests/resources/checks/src/hello.sh.link, unittests/test_pipeline.py
=> [feat] Preserve symbolic links in sources directory

.dockerignore, ci-scripts/dockerfiles/Lmod.dockerfile, ci-scripts/dockerfiles/Tmod32.dockerfile, ci-scripts/dockerfiles/Tmod4.dockerfile, unittests/test_utility.py
=> [ci] Skip unit tests requiring git if git is not available

docs/started.rst
=> [doc] Update ReFrame's requirements in the documentation

docs/migration_2_to_3.rst, reframe/core/config.py, unittests/test_config.py
=> [feat] Drop support for old configuration syntax

config/cscs.py, cscs-checks/system/slurm/slurm.py
=> [test] Update configuration and tests for the new batch policies

reframe/frontend/cli.py
=> [bugfix] Fix detailed listing message for node allocation scheme

bootstrap.sh
=> [feat] Remove the --use-feature=2020-resolver from bootstrap

cscs-checks/microbenchmarks/gpu/gpu_burn/src/gpu_burn.cu
Bugfix on the `gpu_burn` output.
=> [test] Fix GPU burn test output

reframe/core/modules.py, unittests/test_modules.py
=> [bugfix] Restore module paths specified in command line when restoring module collections

.github/workflows/publish.yml, ci-scripts/deploy.sh
=> [ci] Use Github Action for uploading ReFrame releases on PyPI

setup.py
=> [bugfix] Add missing required packages in 'setup.py'

cscs-checks/prgenv/ulimit_check.py
=> [test] Include Eiger in the ulimit test

.github/workflows/main.yml, docs/requirements.txt
=> [ci] Add Github Action to test the documentation build

reframe/utility/osext.py
=> [bugfix] Document `osext.cray_cdt_version()` more precisely

cscs-checks/libraries/io/netcdf_compile_run.py, cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py, cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
This fixes some syntax errors in certain systems when listing/searching tests.
=> [test] Fix checks not defining valid_prog_environs

cscs-checks/libraries/gridtools/gridtools_tests.py
Fixes https://jira.cscs.ch/browse/UES-1441
=> [test] Remove version of `cdt-cuda` module for GridTools test on Dom

docs/Makefile
=> [bugfix] Remove VERSION variable from docs Makefile

reframe/core/pipeline.py
=> [bugfix] Fix typo in variable name

cscs-checks/apps/pytorch/pytorch_horovod_check.py
=> [test] Update PyTorch test

config/cscs.py
Account for updated PGI compiler version on Tsa.
=> [ci] Adapt configuration to new Tsa PE

reframe/frontend/executors/policies.py
=> [bugfix] Fix rescheduling condition for asynchronous execution policy

reframe/core/schedulers/slurm.py
=> [bugfix] Fix squeue backend scheduler crash

reframe/frontend/cli.py
The bug was introduced in #1941
=> [bugfix] Fix regression in setting the graylog server address

config/cscs.py, docs/config_reference.rst, docs/manpage.rst, reframe/core/logging.py, reframe/frontend/cli.py, reframe/schemas/config.json
=> [feat] Add new logging handler for sending test data in JSON to an HTTP server

unittests/test_pipeline.py
=> [code quality] Test that stagedir is mounted inside container

docs/requirements.txt
=> [packaging] Add docutils 0.16 for sphinx-rtd-theme compatibility

reframe/core/runtime.py
=> [bugfix] Respect default values for module objects in the configuration

cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
Add `PrgEnv-nvidia` in OSU benchmark and update syntax of the tests
=> [test] Update OSU benchmark to include prgenv nvidia

cscs-checks/mch/openacc_cuda_mpi_cppstd.py
=> [test] Update `openacc_cuda_mpi_cppstd`

cscs-checks/mch/gpu_direct_acc.py
=> [test] Update nvidia gpu direct acc

docs/configure.rst
=> [doc] Fix documentation about processor auto-detection

reframe/core/pipeline.py
=> [bugfix] Remove redundant whitespace in local launcher's command

cscs-checks/apps/quantumespresso/quantumespresso_check.py
Fixing https://jira.cscs.ch/browse/UES-1735
=> [test] Fix QuantumESPRESSO 6.8.0 with 21.08

cscs-checks/apps/namd/namd_check.py
Closes [UES-1742](https://jira.cscs.ch/browse/UES-1742)
=> [test] Fix NAMD valid prog. environments

docs/manpage.rst, reframe/frontend/cli.py
=> [doc] Sort command line options and environment variables alphabetically in `-h` output and the man page

cscs-checks/libraries/math/trilinos_compile_run.py
* Cleanup Trilinos test removing obsolete workarounds.
=> [test] Use https instead of ftp to download the matrix in trilinos test

unittests/test_ci.py
=> [ci] Fix reference URL for Gitlab CI validation

docs/manpage.rst, reframe/frontend/argparse.py
=> [feat] Accept `0` and `1` for boolean env variables

config/cscs.py
The config was very sparsely written since it was auto-generated from the old config when we transitioned to ReFrame 3.0. I've now made it much more compact by removing redundant new lines.
=> [cscs] Make CSCS config more compact

cscs-checks/apps/tensorflow/tf2_horovod_check.py
We were allowing the large scale version on Dom instead of the small one. I have also fixed the reference key to have the right number of nodes.
=> [test] Fix `num_nodes` of Horovod test for Dom

reframe/core/schedulers/pbs.py, unittests/test_schedulers.py
=> [bugfix] Use conformant job names for Torque backend

cscs-checks/microbenchmarks/cpu/simd/nsimd.py
@jgphpc There is no way I can test this, since the required modules are not available. Can you review it?
=> [test] Modernise nsimd test

cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py
There are still a couple of improvements that this test can take, but the first one needs a change in the configuration and the second one is missing a feature. Nonetheless, this PR modernises the syntax and removes any deprecation warnings.
=> [test] Modernise DGEMM test

cscs-checks/compile/libsci_resolve.py, cscs-checks/libraries/cray-libsci/libsci_acc.py
Temporary fix loading `cray-libsci_acc` with PrgEnv-gnu: see [PROGENV-24](https://jira.cscs.ch/browse/PROGENV-24).
=> [test] Temporary fix for `cray-libsci_acc` with CDT 21.09

config/cscs.py
Set a time limit of 10 minutes for all checks on Alps.
=> [test] Set time limit for tests on Alps

reframe/utility/__init__.py, unittests/test_utility.py
=> [bugfix] Fix regex pattern for matching node lists

README.md
=> [doc] Add PyPI download badges

reframe/utility/__init__.py, unittests/test_utility.py
=> [bugfix] Fix `find_modules` to return unique module names

config/cscs.py, cscs-checks/system/slurm/slurm.py
Sometimes the xfer partition is down on dom and nobody notices, so I extended the `HostnameCheck` test and the CSCS configuration.
=> [test] Add Slurm check for the xfer queue on Dom

cscs-checks/prgenv/affinity_check.py
Update affinity checks with `PrgEnv-nvidia` and remove `PrgEnv-pgi` from all systems (see [SD-54790](https://jira.cscs.ch/browse/SD-54790)).
=> [test] Update affinity checks

cscs-checks/apps/amber/amber_check.py, cscs-checks/apps/gromacs/gromacs_check.py, hpctestlib/sciapps/amber/nve.py, hpctestlib/sciapps/gromacs/benchmarks.py
I have also aligned the implementation of the Amber library test with that of Gromacs.
=> [test] Make parameters loggable in Amber and Gromacs tests

cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
See discussion in [PROGENV-20](https://jira.cscs.ch/browse/PROGENV-20) and comment in [PROGENV-28](https://jira.cscs.ch/browse/PROGENV-28).
=> [test] Update `AllocSpeedTest` performance reference on Dom and Piz Daint

reframe/frontend/statistics.py
Closes #2465 .
I think it's better to print both names, but if you don't like it we can completely remove the unique name.
=> [feat] Add display name to the failure statistics

reframe/core/exceptions.py
=> [bugfix] Skip test file when an import error is encountered

reframe/frontend/filters.py, reframe/frontend/runreport.py, reframe/frontend/statistics.py, reframe/schemas/runreport.json, unittests/test_filters.py
=> [bugfix] Improve test selection by their variant id

reframe/frontend/executors/policies.py
=> [bugfix] Snooze between polls in serial policy

docs/config_reference.rst
=> [doc] Fix documentation of execution modes' `target_systems`

docs/config_reference.rst
=> [bugfix] Document missing log record attributes

hpctestlib/microbenchmarks/gpu/shmem/__init__.py
=> [test] Fix sanity pattern in GpuShmem test

reframe/frontend/filters.py, unittests/test_cli.py
=> [bugfix] Fix filtering of tests with hashcode

reframe/core/logging.py
=> [feat] Print better error message when pygelf cannot be imported

reframe/utility/__init__.py, unittests/test_utility.py
=> [bugfix] Fix nodelist compaction for single digitless nodes

README.md
I have reconnected codecov to this repo.
=> [doc] Update link in codecov badge

reframe/core/logging.py, reframe/frontend/executors/__init__.py, unittests/test_policies.py
=> [bugfix] Fix `perflog_compat` crash when performance test fails in sanity

.github/workflows/main.yml, .github/workflows/publish.yml
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
Fixes #2639
=> [ci] Update GitHub Actions to use setup-python@v4

reframe/schemas/config.json, unittests/resources/config/settings.py, unittests/test_config.py
The unit tests are also adapted in order to reproduce the initial error.
Fixes #2792.
=> [bugfix] Properly define `sched_options` in the configuration schema

reframe/core/meta.py
=> [doc] Fix typo in `make_test` docs

docs/config_reference.rst, docs/manpage.rst, docs/pipeline.rst
=> [doc] Provide further documentation about the `pipeline_timeout` attribute

docs/config_reference.rst
=> [doc] Add a note about `sched_options` being broken in 4.0

reframe/frontend/ci.py
Closes #2836.
@cedricjourdain This should fix your problem.
=> [bugfix] Fix test selection in Gitlab child pipelines

.github/workflows/main.yml, requirements.txt
=> [ci] Replace `codecov` with `coverage` in CI

reframe/schemas/config.json, unittests/test_config.py
=> [bugfix] Fix definition of default values for `sched_options` parameters

bootstrap.sh
=> [packaging] Fail on errors in `bootstrap.sh` and add a new `--ignore-errors` option

reframe/core/pipeline.py, reframe/core/schedulers/__init__.py
=> [bugfix] Use tests's short name as the name of the job

docs/manpage.rst
=> [doc] Add note about test generation options and `--ci-generate`

.github/workflows/test-flux.yaml
See https://github.com/flux-framework/flux-sched/issues/1068
=> [ci] Pin version of flux scheduler in CI

hpctestlib/system/ssh/host_keys.py
The test references the self.host_keys variable but it should be self.ssh_host_keys instead
=> [testlib] Fix the `ssh_host_keys` library test

docs/config_reference.rst
=> [doc] Update `filelog` log handler docs

reframe/frontend/autodetect.py
=> [bugfix] Always remove temporary directory when remote auto-detection fails

reframe/utility/__init__.py, unittests/test_utility.py
=> [bugfix] Show test references with `--describe` option

setup.cfg
=> [packaging] Add hpctestlib to the PyPI package

.github/workflows/main.yml
=> [ci] Validate docs everywhere

docs/requirements.txt
=> [doc] Update doc dependencies

.github/workflows/main.yml, setup.cfg
=> [ci] Enable Python 3.12 in CI

reframe/frontend/cli.py, unittests/test_cli.py
=> [feat] Issue an error when invoking an invalid mode

docs/config_reference.rst, reframe/core/systems.py, unittests/test_config.py
=> [feat] Include scheduler and launcher as default partition extras

docs/requirements.txt
=> [doc] Fix broken link to older versions of the documentation

docs/conf.py, docs/requirements.txt
=> [doc] Fix missing JQuery dependency in documentation's `conf.py`

reframe/utility/osext.py
We now only add the version suffix is the install prefix contains a `.git` directory.
Also, we only do the hash retrieval if needed (i.e. when in a dev release)
Fixes #3120.
=> [bugfix] Make version hash suffix calculation more robust

reframe/frontend/cli.py
=> [bugfix] Do not use CLI defaults for options that are backed by a configuration option

docs/manpage.rst
=> [doc] Update description of the configuration in the manpage

reframe/schemas/runreport.json
Closes #3219.
Requires #3222 to be merged.
=> [bugfix] Fix report schema to properly accept all test results

ci-scripts/dockerfiles/Tmod32.dockerfile
=> [ci] Fix Tmod32 container due to Centos 7 EOL

docs/manpage.rst
=> [bugfix] Fix typo in the `--distribute` docs

README.md, README_minimal.md, docs/index.rst
=> [doc] Add information on how to cite ReFrame

reframe/frontend/statistics.py
=> [enhancement] Print the test file in failure info

reframe/frontend/reporting/utility.py
This will fix the failing unit test that blocks other PRs.
=> [bugfix] Fix DST skew in `CMPSPEC` period calculations

docs/config_reference.rst, reframe/core/logging.py
=> [feat] Add a `check_fail_phase` log formatting specifier

reframe/frontend/reporting/storage.py
This improves considerably the decoding performance as we avoid our wrapper package's (`jsonext`) redirections.
=> [enhancement] Use builtin `json` package for decoding testcase data

reframe/utility/osext.py
This a proper fix for #3379. The current code could trigger a deadlock.
The problem was that the spawned process was finishing too early, before the call to `getsid()` and in this case we were getting `ESRCH`. This solution treats this case, by waiting the finished process.
=> [bugfix] Fix `ESRCH` error due to race condition when spawning fast futures

reframe/core/config.py, unittests/resources/config/settings.py, unittests/test_config.py
=> [bugfix] Fix assignment of default configuration parameters across systems

reframe/frontend/executors/policies.py
Fix the pipeline progress statistics
=> [bugfix] Fix bug in update of pipeline progress statistics

ci-scripts/dockerfiles/reframe-lmod77.dockerfile, reframe/core/pipeline.py, unittests/test_pipeline.py, unittests/test_utility.py
=> [bugfix] Mark the stagedir after the copy or clone of resources

unittests/resources/config/settings.yaml
This fixes the CI failures after the merge with master.
=> [ci] Update YAML unit test config

reframe/frontend/printer.py
=> [bugfix] Insert new line between stdout/stderr listings in failures

docs/manpage.rst
=> [doc] Document the requirement of file lock support for enabling results storage

reframe/frontend/cli.py
=> [enhancement] Show up front if result storage is enabled

reframe/frontend/printer.py
=> [bugfix] Fix progress numbering for XFAIL/XPASS tests
